// Code generated by ent, DO NOT EDIT.

package invoicedelivery

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/BrandonVee/TokenRouter/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldLTE(FieldID, id))
}

// InvoiceRequestID applies equality check predicate on the "invoice_request_id" field. It's identical to InvoiceRequestIDEQ.
func InvoiceRequestID(v int64) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldEQ(FieldInvoiceRequestID, v))
}

// RecipientEmail applies equality check predicate on the "recipient_email" field. It's identical to RecipientEmailEQ.
func RecipientEmail(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldEQ(FieldRecipientEmail, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldEQ(FieldStatus, v))
}

// MessageID applies equality check predicate on the "message_id" field. It's identical to MessageIDEQ.
func MessageID(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldEQ(FieldMessageID, v))
}

// AttachmentSummary applies equality check predicate on the "attachment_summary" field. It's identical to AttachmentSummaryEQ.
func AttachmentSummary(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldEQ(FieldAttachmentSummary, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldEQ(FieldErrorMessage, v))
}

// SentBy applies equality check predicate on the "sent_by" field. It's identical to SentByEQ.
func SentBy(v int64) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldEQ(FieldSentBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldEQ(FieldCreatedAt, v))
}

// InvoiceRequestIDEQ applies the EQ predicate on the "invoice_request_id" field.
func InvoiceRequestIDEQ(v int64) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldEQ(FieldInvoiceRequestID, v))
}

// InvoiceRequestIDNEQ applies the NEQ predicate on the "invoice_request_id" field.
func InvoiceRequestIDNEQ(v int64) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldNEQ(FieldInvoiceRequestID, v))
}

// InvoiceRequestIDIn applies the In predicate on the "invoice_request_id" field.
func InvoiceRequestIDIn(vs ...int64) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldIn(FieldInvoiceRequestID, vs...))
}

// InvoiceRequestIDNotIn applies the NotIn predicate on the "invoice_request_id" field.
func InvoiceRequestIDNotIn(vs ...int64) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldNotIn(FieldInvoiceRequestID, vs...))
}

// InvoiceRequestIDGT applies the GT predicate on the "invoice_request_id" field.
func InvoiceRequestIDGT(v int64) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldGT(FieldInvoiceRequestID, v))
}

// InvoiceRequestIDGTE applies the GTE predicate on the "invoice_request_id" field.
func InvoiceRequestIDGTE(v int64) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldGTE(FieldInvoiceRequestID, v))
}

// InvoiceRequestIDLT applies the LT predicate on the "invoice_request_id" field.
func InvoiceRequestIDLT(v int64) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldLT(FieldInvoiceRequestID, v))
}

// InvoiceRequestIDLTE applies the LTE predicate on the "invoice_request_id" field.
func InvoiceRequestIDLTE(v int64) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldLTE(FieldInvoiceRequestID, v))
}

// RecipientEmailEQ applies the EQ predicate on the "recipient_email" field.
func RecipientEmailEQ(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldEQ(FieldRecipientEmail, v))
}

// RecipientEmailNEQ applies the NEQ predicate on the "recipient_email" field.
func RecipientEmailNEQ(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldNEQ(FieldRecipientEmail, v))
}

// RecipientEmailIn applies the In predicate on the "recipient_email" field.
func RecipientEmailIn(vs ...string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldIn(FieldRecipientEmail, vs...))
}

// RecipientEmailNotIn applies the NotIn predicate on the "recipient_email" field.
func RecipientEmailNotIn(vs ...string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldNotIn(FieldRecipientEmail, vs...))
}

// RecipientEmailGT applies the GT predicate on the "recipient_email" field.
func RecipientEmailGT(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldGT(FieldRecipientEmail, v))
}

// RecipientEmailGTE applies the GTE predicate on the "recipient_email" field.
func RecipientEmailGTE(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldGTE(FieldRecipientEmail, v))
}

// RecipientEmailLT applies the LT predicate on the "recipient_email" field.
func RecipientEmailLT(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldLT(FieldRecipientEmail, v))
}

// RecipientEmailLTE applies the LTE predicate on the "recipient_email" field.
func RecipientEmailLTE(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldLTE(FieldRecipientEmail, v))
}

// RecipientEmailContains applies the Contains predicate on the "recipient_email" field.
func RecipientEmailContains(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldContains(FieldRecipientEmail, v))
}

// RecipientEmailHasPrefix applies the HasPrefix predicate on the "recipient_email" field.
func RecipientEmailHasPrefix(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldHasPrefix(FieldRecipientEmail, v))
}

// RecipientEmailHasSuffix applies the HasSuffix predicate on the "recipient_email" field.
func RecipientEmailHasSuffix(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldHasSuffix(FieldRecipientEmail, v))
}

// RecipientEmailEqualFold applies the EqualFold predicate on the "recipient_email" field.
func RecipientEmailEqualFold(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldEqualFold(FieldRecipientEmail, v))
}

// RecipientEmailContainsFold applies the ContainsFold predicate on the "recipient_email" field.
func RecipientEmailContainsFold(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldContainsFold(FieldRecipientEmail, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldContainsFold(FieldStatus, v))
}

// MessageIDEQ applies the EQ predicate on the "message_id" field.
func MessageIDEQ(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldEQ(FieldMessageID, v))
}

// MessageIDNEQ applies the NEQ predicate on the "message_id" field.
func MessageIDNEQ(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldNEQ(FieldMessageID, v))
}

// MessageIDIn applies the In predicate on the "message_id" field.
func MessageIDIn(vs ...string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldIn(FieldMessageID, vs...))
}

// MessageIDNotIn applies the NotIn predicate on the "message_id" field.
func MessageIDNotIn(vs ...string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldNotIn(FieldMessageID, vs...))
}

// MessageIDGT applies the GT predicate on the "message_id" field.
func MessageIDGT(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldGT(FieldMessageID, v))
}

// MessageIDGTE applies the GTE predicate on the "message_id" field.
func MessageIDGTE(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldGTE(FieldMessageID, v))
}

// MessageIDLT applies the LT predicate on the "message_id" field.
func MessageIDLT(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldLT(FieldMessageID, v))
}

// MessageIDLTE applies the LTE predicate on the "message_id" field.
func MessageIDLTE(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldLTE(FieldMessageID, v))
}

// MessageIDContains applies the Contains predicate on the "message_id" field.
func MessageIDContains(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldContains(FieldMessageID, v))
}

// MessageIDHasPrefix applies the HasPrefix predicate on the "message_id" field.
func MessageIDHasPrefix(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldHasPrefix(FieldMessageID, v))
}

// MessageIDHasSuffix applies the HasSuffix predicate on the "message_id" field.
func MessageIDHasSuffix(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldHasSuffix(FieldMessageID, v))
}

// MessageIDIsNil applies the IsNil predicate on the "message_id" field.
func MessageIDIsNil() predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldIsNull(FieldMessageID))
}

// MessageIDNotNil applies the NotNil predicate on the "message_id" field.
func MessageIDNotNil() predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldNotNull(FieldMessageID))
}

// MessageIDEqualFold applies the EqualFold predicate on the "message_id" field.
func MessageIDEqualFold(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldEqualFold(FieldMessageID, v))
}

// MessageIDContainsFold applies the ContainsFold predicate on the "message_id" field.
func MessageIDContainsFold(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldContainsFold(FieldMessageID, v))
}

// AttachmentSummaryEQ applies the EQ predicate on the "attachment_summary" field.
func AttachmentSummaryEQ(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldEQ(FieldAttachmentSummary, v))
}

// AttachmentSummaryNEQ applies the NEQ predicate on the "attachment_summary" field.
func AttachmentSummaryNEQ(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldNEQ(FieldAttachmentSummary, v))
}

// AttachmentSummaryIn applies the In predicate on the "attachment_summary" field.
func AttachmentSummaryIn(vs ...string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldIn(FieldAttachmentSummary, vs...))
}

// AttachmentSummaryNotIn applies the NotIn predicate on the "attachment_summary" field.
func AttachmentSummaryNotIn(vs ...string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldNotIn(FieldAttachmentSummary, vs...))
}

// AttachmentSummaryGT applies the GT predicate on the "attachment_summary" field.
func AttachmentSummaryGT(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldGT(FieldAttachmentSummary, v))
}

// AttachmentSummaryGTE applies the GTE predicate on the "attachment_summary" field.
func AttachmentSummaryGTE(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldGTE(FieldAttachmentSummary, v))
}

// AttachmentSummaryLT applies the LT predicate on the "attachment_summary" field.
func AttachmentSummaryLT(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldLT(FieldAttachmentSummary, v))
}

// AttachmentSummaryLTE applies the LTE predicate on the "attachment_summary" field.
func AttachmentSummaryLTE(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldLTE(FieldAttachmentSummary, v))
}

// AttachmentSummaryContains applies the Contains predicate on the "attachment_summary" field.
func AttachmentSummaryContains(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldContains(FieldAttachmentSummary, v))
}

// AttachmentSummaryHasPrefix applies the HasPrefix predicate on the "attachment_summary" field.
func AttachmentSummaryHasPrefix(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldHasPrefix(FieldAttachmentSummary, v))
}

// AttachmentSummaryHasSuffix applies the HasSuffix predicate on the "attachment_summary" field.
func AttachmentSummaryHasSuffix(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldHasSuffix(FieldAttachmentSummary, v))
}

// AttachmentSummaryIsNil applies the IsNil predicate on the "attachment_summary" field.
func AttachmentSummaryIsNil() predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldIsNull(FieldAttachmentSummary))
}

// AttachmentSummaryNotNil applies the NotNil predicate on the "attachment_summary" field.
func AttachmentSummaryNotNil() predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldNotNull(FieldAttachmentSummary))
}

// AttachmentSummaryEqualFold applies the EqualFold predicate on the "attachment_summary" field.
func AttachmentSummaryEqualFold(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldEqualFold(FieldAttachmentSummary, v))
}

// AttachmentSummaryContainsFold applies the ContainsFold predicate on the "attachment_summary" field.
func AttachmentSummaryContainsFold(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldContainsFold(FieldAttachmentSummary, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldContainsFold(FieldErrorMessage, v))
}

// SentByEQ applies the EQ predicate on the "sent_by" field.
func SentByEQ(v int64) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldEQ(FieldSentBy, v))
}

// SentByNEQ applies the NEQ predicate on the "sent_by" field.
func SentByNEQ(v int64) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldNEQ(FieldSentBy, v))
}

// SentByIn applies the In predicate on the "sent_by" field.
func SentByIn(vs ...int64) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldIn(FieldSentBy, vs...))
}

// SentByNotIn applies the NotIn predicate on the "sent_by" field.
func SentByNotIn(vs ...int64) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldNotIn(FieldSentBy, vs...))
}

// SentByGT applies the GT predicate on the "sent_by" field.
func SentByGT(v int64) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldGT(FieldSentBy, v))
}

// SentByGTE applies the GTE predicate on the "sent_by" field.
func SentByGTE(v int64) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldGTE(FieldSentBy, v))
}

// SentByLT applies the LT predicate on the "sent_by" field.
func SentByLT(v int64) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldLT(FieldSentBy, v))
}

// SentByLTE applies the LTE predicate on the "sent_by" field.
func SentByLTE(v int64) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldLTE(FieldSentBy, v))
}

// SentByIsNil applies the IsNil predicate on the "sent_by" field.
func SentByIsNil() predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldIsNull(FieldSentBy))
}

// SentByNotNil applies the NotNil predicate on the "sent_by" field.
func SentByNotNil() predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldNotNull(FieldSentBy))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InvoiceDelivery) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InvoiceDelivery) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InvoiceDelivery) predicate.InvoiceDelivery {
	return predicate.InvoiceDelivery(sql.NotPredicates(p))
}
