// Code generated by ent, DO NOT EDIT.

package invoicerequestitem

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/BrandonVee/TokenRouter/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldLTE(FieldID, id))
}

// InvoiceRequestID applies equality check predicate on the "invoice_request_id" field. It's identical to InvoiceRequestIDEQ.
func InvoiceRequestID(v int64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldEQ(FieldInvoiceRequestID, v))
}

// PaymentOrderID applies equality check predicate on the "payment_order_id" field. It's identical to PaymentOrderIDEQ.
func PaymentOrderID(v int64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldEQ(FieldPaymentOrderID, v))
}

// Active applies equality check predicate on the "active" field. It's identical to ActiveEQ.
func Active(v bool) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldEQ(FieldActive, v))
}

// OrderNo applies equality check predicate on the "order_no" field. It's identical to OrderNoEQ.
func OrderNo(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldEQ(FieldOrderNo, v))
}

// OrderType applies equality check predicate on the "order_type" field. It's identical to OrderTypeEQ.
func OrderType(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldEQ(FieldOrderType, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldEQ(FieldCurrency, v))
}

// PayAmount applies equality check predicate on the "pay_amount" field. It's identical to PayAmountEQ.
func PayAmount(v float64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldEQ(FieldPayAmount, v))
}

// CreditedAmount applies equality check predicate on the "credited_amount" field. It's identical to CreditedAmountEQ.
func CreditedAmount(v float64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldEQ(FieldCreditedAmount, v))
}

// RechargeCode applies equality check predicate on the "recharge_code" field. It's identical to RechargeCodeEQ.
func RechargeCode(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldEQ(FieldRechargeCode, v))
}

// PaidAt applies equality check predicate on the "paid_at" field. It's identical to PaidAtEQ.
func PaidAt(v time.Time) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldEQ(FieldPaidAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldEQ(FieldCreatedAt, v))
}

// InvoiceRequestIDEQ applies the EQ predicate on the "invoice_request_id" field.
func InvoiceRequestIDEQ(v int64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldEQ(FieldInvoiceRequestID, v))
}

// InvoiceRequestIDNEQ applies the NEQ predicate on the "invoice_request_id" field.
func InvoiceRequestIDNEQ(v int64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldNEQ(FieldInvoiceRequestID, v))
}

// InvoiceRequestIDIn applies the In predicate on the "invoice_request_id" field.
func InvoiceRequestIDIn(vs ...int64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldIn(FieldInvoiceRequestID, vs...))
}

// InvoiceRequestIDNotIn applies the NotIn predicate on the "invoice_request_id" field.
func InvoiceRequestIDNotIn(vs ...int64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldNotIn(FieldInvoiceRequestID, vs...))
}

// InvoiceRequestIDGT applies the GT predicate on the "invoice_request_id" field.
func InvoiceRequestIDGT(v int64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldGT(FieldInvoiceRequestID, v))
}

// InvoiceRequestIDGTE applies the GTE predicate on the "invoice_request_id" field.
func InvoiceRequestIDGTE(v int64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldGTE(FieldInvoiceRequestID, v))
}

// InvoiceRequestIDLT applies the LT predicate on the "invoice_request_id" field.
func InvoiceRequestIDLT(v int64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldLT(FieldInvoiceRequestID, v))
}

// InvoiceRequestIDLTE applies the LTE predicate on the "invoice_request_id" field.
func InvoiceRequestIDLTE(v int64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldLTE(FieldInvoiceRequestID, v))
}

// PaymentOrderIDEQ applies the EQ predicate on the "payment_order_id" field.
func PaymentOrderIDEQ(v int64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldEQ(FieldPaymentOrderID, v))
}

// PaymentOrderIDNEQ applies the NEQ predicate on the "payment_order_id" field.
func PaymentOrderIDNEQ(v int64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldNEQ(FieldPaymentOrderID, v))
}

// PaymentOrderIDIn applies the In predicate on the "payment_order_id" field.
func PaymentOrderIDIn(vs ...int64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldIn(FieldPaymentOrderID, vs...))
}

// PaymentOrderIDNotIn applies the NotIn predicate on the "payment_order_id" field.
func PaymentOrderIDNotIn(vs ...int64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldNotIn(FieldPaymentOrderID, vs...))
}

// PaymentOrderIDGT applies the GT predicate on the "payment_order_id" field.
func PaymentOrderIDGT(v int64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldGT(FieldPaymentOrderID, v))
}

// PaymentOrderIDGTE applies the GTE predicate on the "payment_order_id" field.
func PaymentOrderIDGTE(v int64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldGTE(FieldPaymentOrderID, v))
}

// PaymentOrderIDLT applies the LT predicate on the "payment_order_id" field.
func PaymentOrderIDLT(v int64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldLT(FieldPaymentOrderID, v))
}

// PaymentOrderIDLTE applies the LTE predicate on the "payment_order_id" field.
func PaymentOrderIDLTE(v int64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldLTE(FieldPaymentOrderID, v))
}

// ActiveEQ applies the EQ predicate on the "active" field.
func ActiveEQ(v bool) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldEQ(FieldActive, v))
}

// ActiveNEQ applies the NEQ predicate on the "active" field.
func ActiveNEQ(v bool) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldNEQ(FieldActive, v))
}

// OrderNoEQ applies the EQ predicate on the "order_no" field.
func OrderNoEQ(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldEQ(FieldOrderNo, v))
}

// OrderNoNEQ applies the NEQ predicate on the "order_no" field.
func OrderNoNEQ(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldNEQ(FieldOrderNo, v))
}

// OrderNoIn applies the In predicate on the "order_no" field.
func OrderNoIn(vs ...string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldIn(FieldOrderNo, vs...))
}

// OrderNoNotIn applies the NotIn predicate on the "order_no" field.
func OrderNoNotIn(vs ...string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldNotIn(FieldOrderNo, vs...))
}

// OrderNoGT applies the GT predicate on the "order_no" field.
func OrderNoGT(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldGT(FieldOrderNo, v))
}

// OrderNoGTE applies the GTE predicate on the "order_no" field.
func OrderNoGTE(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldGTE(FieldOrderNo, v))
}

// OrderNoLT applies the LT predicate on the "order_no" field.
func OrderNoLT(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldLT(FieldOrderNo, v))
}

// OrderNoLTE applies the LTE predicate on the "order_no" field.
func OrderNoLTE(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldLTE(FieldOrderNo, v))
}

// OrderNoContains applies the Contains predicate on the "order_no" field.
func OrderNoContains(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldContains(FieldOrderNo, v))
}

// OrderNoHasPrefix applies the HasPrefix predicate on the "order_no" field.
func OrderNoHasPrefix(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldHasPrefix(FieldOrderNo, v))
}

// OrderNoHasSuffix applies the HasSuffix predicate on the "order_no" field.
func OrderNoHasSuffix(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldHasSuffix(FieldOrderNo, v))
}

// OrderNoEqualFold applies the EqualFold predicate on the "order_no" field.
func OrderNoEqualFold(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldEqualFold(FieldOrderNo, v))
}

// OrderNoContainsFold applies the ContainsFold predicate on the "order_no" field.
func OrderNoContainsFold(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldContainsFold(FieldOrderNo, v))
}

// OrderTypeEQ applies the EQ predicate on the "order_type" field.
func OrderTypeEQ(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldEQ(FieldOrderType, v))
}

// OrderTypeNEQ applies the NEQ predicate on the "order_type" field.
func OrderTypeNEQ(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldNEQ(FieldOrderType, v))
}

// OrderTypeIn applies the In predicate on the "order_type" field.
func OrderTypeIn(vs ...string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldIn(FieldOrderType, vs...))
}

// OrderTypeNotIn applies the NotIn predicate on the "order_type" field.
func OrderTypeNotIn(vs ...string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldNotIn(FieldOrderType, vs...))
}

// OrderTypeGT applies the GT predicate on the "order_type" field.
func OrderTypeGT(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldGT(FieldOrderType, v))
}

// OrderTypeGTE applies the GTE predicate on the "order_type" field.
func OrderTypeGTE(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldGTE(FieldOrderType, v))
}

// OrderTypeLT applies the LT predicate on the "order_type" field.
func OrderTypeLT(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldLT(FieldOrderType, v))
}

// OrderTypeLTE applies the LTE predicate on the "order_type" field.
func OrderTypeLTE(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldLTE(FieldOrderType, v))
}

// OrderTypeContains applies the Contains predicate on the "order_type" field.
func OrderTypeContains(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldContains(FieldOrderType, v))
}

// OrderTypeHasPrefix applies the HasPrefix predicate on the "order_type" field.
func OrderTypeHasPrefix(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldHasPrefix(FieldOrderType, v))
}

// OrderTypeHasSuffix applies the HasSuffix predicate on the "order_type" field.
func OrderTypeHasSuffix(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldHasSuffix(FieldOrderType, v))
}

// OrderTypeEqualFold applies the EqualFold predicate on the "order_type" field.
func OrderTypeEqualFold(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldEqualFold(FieldOrderType, v))
}

// OrderTypeContainsFold applies the ContainsFold predicate on the "order_type" field.
func OrderTypeContainsFold(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldContainsFold(FieldOrderType, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldContainsFold(FieldCurrency, v))
}

// PayAmountEQ applies the EQ predicate on the "pay_amount" field.
func PayAmountEQ(v float64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldEQ(FieldPayAmount, v))
}

// PayAmountNEQ applies the NEQ predicate on the "pay_amount" field.
func PayAmountNEQ(v float64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldNEQ(FieldPayAmount, v))
}

// PayAmountIn applies the In predicate on the "pay_amount" field.
func PayAmountIn(vs ...float64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldIn(FieldPayAmount, vs...))
}

// PayAmountNotIn applies the NotIn predicate on the "pay_amount" field.
func PayAmountNotIn(vs ...float64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldNotIn(FieldPayAmount, vs...))
}

// PayAmountGT applies the GT predicate on the "pay_amount" field.
func PayAmountGT(v float64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldGT(FieldPayAmount, v))
}

// PayAmountGTE applies the GTE predicate on the "pay_amount" field.
func PayAmountGTE(v float64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldGTE(FieldPayAmount, v))
}

// PayAmountLT applies the LT predicate on the "pay_amount" field.
func PayAmountLT(v float64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldLT(FieldPayAmount, v))
}

// PayAmountLTE applies the LTE predicate on the "pay_amount" field.
func PayAmountLTE(v float64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldLTE(FieldPayAmount, v))
}

// CreditedAmountEQ applies the EQ predicate on the "credited_amount" field.
func CreditedAmountEQ(v float64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldEQ(FieldCreditedAmount, v))
}

// CreditedAmountNEQ applies the NEQ predicate on the "credited_amount" field.
func CreditedAmountNEQ(v float64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldNEQ(FieldCreditedAmount, v))
}

// CreditedAmountIn applies the In predicate on the "credited_amount" field.
func CreditedAmountIn(vs ...float64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldIn(FieldCreditedAmount, vs...))
}

// CreditedAmountNotIn applies the NotIn predicate on the "credited_amount" field.
func CreditedAmountNotIn(vs ...float64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldNotIn(FieldCreditedAmount, vs...))
}

// CreditedAmountGT applies the GT predicate on the "credited_amount" field.
func CreditedAmountGT(v float64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldGT(FieldCreditedAmount, v))
}

// CreditedAmountGTE applies the GTE predicate on the "credited_amount" field.
func CreditedAmountGTE(v float64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldGTE(FieldCreditedAmount, v))
}

// CreditedAmountLT applies the LT predicate on the "credited_amount" field.
func CreditedAmountLT(v float64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldLT(FieldCreditedAmount, v))
}

// CreditedAmountLTE applies the LTE predicate on the "credited_amount" field.
func CreditedAmountLTE(v float64) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldLTE(FieldCreditedAmount, v))
}

// RechargeCodeEQ applies the EQ predicate on the "recharge_code" field.
func RechargeCodeEQ(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldEQ(FieldRechargeCode, v))
}

// RechargeCodeNEQ applies the NEQ predicate on the "recharge_code" field.
func RechargeCodeNEQ(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldNEQ(FieldRechargeCode, v))
}

// RechargeCodeIn applies the In predicate on the "recharge_code" field.
func RechargeCodeIn(vs ...string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldIn(FieldRechargeCode, vs...))
}

// RechargeCodeNotIn applies the NotIn predicate on the "recharge_code" field.
func RechargeCodeNotIn(vs ...string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldNotIn(FieldRechargeCode, vs...))
}

// RechargeCodeGT applies the GT predicate on the "recharge_code" field.
func RechargeCodeGT(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldGT(FieldRechargeCode, v))
}

// RechargeCodeGTE applies the GTE predicate on the "recharge_code" field.
func RechargeCodeGTE(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldGTE(FieldRechargeCode, v))
}

// RechargeCodeLT applies the LT predicate on the "recharge_code" field.
func RechargeCodeLT(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldLT(FieldRechargeCode, v))
}

// RechargeCodeLTE applies the LTE predicate on the "recharge_code" field.
func RechargeCodeLTE(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldLTE(FieldRechargeCode, v))
}

// RechargeCodeContains applies the Contains predicate on the "recharge_code" field.
func RechargeCodeContains(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldContains(FieldRechargeCode, v))
}

// RechargeCodeHasPrefix applies the HasPrefix predicate on the "recharge_code" field.
func RechargeCodeHasPrefix(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldHasPrefix(FieldRechargeCode, v))
}

// RechargeCodeHasSuffix applies the HasSuffix predicate on the "recharge_code" field.
func RechargeCodeHasSuffix(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldHasSuffix(FieldRechargeCode, v))
}

// RechargeCodeIsNil applies the IsNil predicate on the "recharge_code" field.
func RechargeCodeIsNil() predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldIsNull(FieldRechargeCode))
}

// RechargeCodeNotNil applies the NotNil predicate on the "recharge_code" field.
func RechargeCodeNotNil() predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldNotNull(FieldRechargeCode))
}

// RechargeCodeEqualFold applies the EqualFold predicate on the "recharge_code" field.
func RechargeCodeEqualFold(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldEqualFold(FieldRechargeCode, v))
}

// RechargeCodeContainsFold applies the ContainsFold predicate on the "recharge_code" field.
func RechargeCodeContainsFold(v string) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldContainsFold(FieldRechargeCode, v))
}

// ProductSnapshotIsNil applies the IsNil predicate on the "product_snapshot" field.
func ProductSnapshotIsNil() predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldIsNull(FieldProductSnapshot))
}

// ProductSnapshotNotNil applies the NotNil predicate on the "product_snapshot" field.
func ProductSnapshotNotNil() predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldNotNull(FieldProductSnapshot))
}

// PaidAtEQ applies the EQ predicate on the "paid_at" field.
func PaidAtEQ(v time.Time) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldEQ(FieldPaidAt, v))
}

// PaidAtNEQ applies the NEQ predicate on the "paid_at" field.
func PaidAtNEQ(v time.Time) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldNEQ(FieldPaidAt, v))
}

// PaidAtIn applies the In predicate on the "paid_at" field.
func PaidAtIn(vs ...time.Time) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldIn(FieldPaidAt, vs...))
}

// PaidAtNotIn applies the NotIn predicate on the "paid_at" field.
func PaidAtNotIn(vs ...time.Time) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldNotIn(FieldPaidAt, vs...))
}

// PaidAtGT applies the GT predicate on the "paid_at" field.
func PaidAtGT(v time.Time) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldGT(FieldPaidAt, v))
}

// PaidAtGTE applies the GTE predicate on the "paid_at" field.
func PaidAtGTE(v time.Time) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldGTE(FieldPaidAt, v))
}

// PaidAtLT applies the LT predicate on the "paid_at" field.
func PaidAtLT(v time.Time) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldLT(FieldPaidAt, v))
}

// PaidAtLTE applies the LTE predicate on the "paid_at" field.
func PaidAtLTE(v time.Time) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldLTE(FieldPaidAt, v))
}

// PaidAtIsNil applies the IsNil predicate on the "paid_at" field.
func PaidAtIsNil() predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldIsNull(FieldPaidAt))
}

// PaidAtNotNil applies the NotNil predicate on the "paid_at" field.
func PaidAtNotNil() predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldNotNull(FieldPaidAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InvoiceRequestItem) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InvoiceRequestItem) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InvoiceRequestItem) predicate.InvoiceRequestItem {
	return predicate.InvoiceRequestItem(sql.NotPredicates(p))
}
