// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/BrandonVee/TokenRouter/ent/dashboardad"
)

// DashboardAdCreate is the builder for creating a DashboardAd entity.
type DashboardAdCreate struct {
	config
	mutation *DashboardAdMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetImageURL sets the "image_url" field.
func (_c *DashboardAdCreate) SetImageURL(v string) *DashboardAdCreate {
	_c.mutation.SetImageURL(v)
	return _c
}

// SetLinkURL sets the "link_url" field.
func (_c *DashboardAdCreate) SetLinkURL(v string) *DashboardAdCreate {
	_c.mutation.SetLinkURL(v)
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *DashboardAdCreate) SetStartsAt(v time.Time) *DashboardAdCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_c *DashboardAdCreate) SetNillableStartsAt(v *time.Time) *DashboardAdCreate {
	if v != nil {
		_c.SetStartsAt(*v)
	}
	return _c
}

// SetEndsAt sets the "ends_at" field.
func (_c *DashboardAdCreate) SetEndsAt(v time.Time) *DashboardAdCreate {
	_c.mutation.SetEndsAt(v)
	return _c
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_c *DashboardAdCreate) SetNillableEndsAt(v *time.Time) *DashboardAdCreate {
	if v != nil {
		_c.SetEndsAt(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *DashboardAdCreate) SetEnabled(v bool) *DashboardAdCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *DashboardAdCreate) SetNillableEnabled(v *bool) *DashboardAdCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *DashboardAdCreate) SetSortOrder(v int) *DashboardAdCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *DashboardAdCreate) SetNillableSortOrder(v *int) *DashboardAdCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DashboardAdCreate) SetCreatedAt(v time.Time) *DashboardAdCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DashboardAdCreate) SetNillableCreatedAt(v *time.Time) *DashboardAdCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DashboardAdCreate) SetUpdatedAt(v time.Time) *DashboardAdCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DashboardAdCreate) SetNillableUpdatedAt(v *time.Time) *DashboardAdCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DashboardAdCreate) SetID(v string) *DashboardAdCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the DashboardAdMutation object of the builder.
func (_c *DashboardAdCreate) Mutation() *DashboardAdMutation {
	return _c.mutation
}

// Save creates the DashboardAd in the database.
func (_c *DashboardAdCreate) Save(ctx context.Context) (*DashboardAd, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DashboardAdCreate) SaveX(ctx context.Context) *DashboardAd {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DashboardAdCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DashboardAdCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DashboardAdCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := dashboardad.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := dashboardad.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := dashboardad.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := dashboardad.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DashboardAdCreate) check() error {
	if _, ok := _c.mutation.ImageURL(); !ok {
		return &ValidationError{Name: "image_url", err: errors.New(`ent: missing required field "DashboardAd.image_url"`)}
	}
	if _, ok := _c.mutation.LinkURL(); !ok {
		return &ValidationError{Name: "link_url", err: errors.New(`ent: missing required field "DashboardAd.link_url"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "DashboardAd.enabled"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "DashboardAd.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DashboardAd.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DashboardAd.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := dashboardad.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "DashboardAd.id": %w`, err)}
		}
	}
	return nil
}

func (_c *DashboardAdCreate) sqlSave(ctx context.Context) (*DashboardAd, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected DashboardAd.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DashboardAdCreate) createSpec() (*DashboardAd, *sqlgraph.CreateSpec) {
	var (
		_node = &DashboardAd{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dashboardad.Table, sqlgraph.NewFieldSpec(dashboardad.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ImageURL(); ok {
		_spec.SetField(dashboardad.FieldImageURL, field.TypeString, value)
		_node.ImageURL = value
	}
	if value, ok := _c.mutation.LinkURL(); ok {
		_spec.SetField(dashboardad.FieldLinkURL, field.TypeString, value)
		_node.LinkURL = value
	}
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(dashboardad.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = &value
	}
	if value, ok := _c.mutation.EndsAt(); ok {
		_spec.SetField(dashboardad.FieldEndsAt, field.TypeTime, value)
		_node.EndsAt = &value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(dashboardad.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(dashboardad.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(dashboardad.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(dashboardad.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DashboardAd.Create().
//		SetImageURL(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DashboardAdUpsert) {
//			SetImageURL(v+v).
//		}).
//		Exec(ctx)
func (_c *DashboardAdCreate) OnConflict(opts ...sql.ConflictOption) *DashboardAdUpsertOne {
	_c.conflict = opts
	return &DashboardAdUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DashboardAd.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DashboardAdCreate) OnConflictColumns(columns ...string) *DashboardAdUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DashboardAdUpsertOne{
		create: _c,
	}
}

type (
	// DashboardAdUpsertOne is the builder for "upsert"-ing
	//  one DashboardAd node.
	DashboardAdUpsertOne struct {
		create *DashboardAdCreate
	}

	// DashboardAdUpsert is the "OnConflict" setter.
	DashboardAdUpsert struct {
		*sql.UpdateSet
	}
)

// SetImageURL sets the "image_url" field.
func (u *DashboardAdUpsert) SetImageURL(v string) *DashboardAdUpsert {
	u.Set(dashboardad.FieldImageURL, v)
	return u
}

// UpdateImageURL sets the "image_url" field to the value that was provided on create.
func (u *DashboardAdUpsert) UpdateImageURL() *DashboardAdUpsert {
	u.SetExcluded(dashboardad.FieldImageURL)
	return u
}

// SetLinkURL sets the "link_url" field.
func (u *DashboardAdUpsert) SetLinkURL(v string) *DashboardAdUpsert {
	u.Set(dashboardad.FieldLinkURL, v)
	return u
}

// UpdateLinkURL sets the "link_url" field to the value that was provided on create.
func (u *DashboardAdUpsert) UpdateLinkURL() *DashboardAdUpsert {
	u.SetExcluded(dashboardad.FieldLinkURL)
	return u
}

// SetStartsAt sets the "starts_at" field.
func (u *DashboardAdUpsert) SetStartsAt(v time.Time) *DashboardAdUpsert {
	u.Set(dashboardad.FieldStartsAt, v)
	return u
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *DashboardAdUpsert) UpdateStartsAt() *DashboardAdUpsert {
	u.SetExcluded(dashboardad.FieldStartsAt)
	return u
}

// ClearStartsAt clears the value of the "starts_at" field.
func (u *DashboardAdUpsert) ClearStartsAt() *DashboardAdUpsert {
	u.SetNull(dashboardad.FieldStartsAt)
	return u
}

// SetEndsAt sets the "ends_at" field.
func (u *DashboardAdUpsert) SetEndsAt(v time.Time) *DashboardAdUpsert {
	u.Set(dashboardad.FieldEndsAt, v)
	return u
}

// UpdateEndsAt sets the "ends_at" field to the value that was provided on create.
func (u *DashboardAdUpsert) UpdateEndsAt() *DashboardAdUpsert {
	u.SetExcluded(dashboardad.FieldEndsAt)
	return u
}

// ClearEndsAt clears the value of the "ends_at" field.
func (u *DashboardAdUpsert) ClearEndsAt() *DashboardAdUpsert {
	u.SetNull(dashboardad.FieldEndsAt)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *DashboardAdUpsert) SetEnabled(v bool) *DashboardAdUpsert {
	u.Set(dashboardad.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *DashboardAdUpsert) UpdateEnabled() *DashboardAdUpsert {
	u.SetExcluded(dashboardad.FieldEnabled)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *DashboardAdUpsert) SetSortOrder(v int) *DashboardAdUpsert {
	u.Set(dashboardad.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *DashboardAdUpsert) UpdateSortOrder() *DashboardAdUpsert {
	u.SetExcluded(dashboardad.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *DashboardAdUpsert) AddSortOrder(v int) *DashboardAdUpsert {
	u.Add(dashboardad.FieldSortOrder, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DashboardAdUpsert) SetUpdatedAt(v time.Time) *DashboardAdUpsert {
	u.Set(dashboardad.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DashboardAdUpsert) UpdateUpdatedAt() *DashboardAdUpsert {
	u.SetExcluded(dashboardad.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.DashboardAd.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(dashboardad.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DashboardAdUpsertOne) UpdateNewValues() *DashboardAdUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(dashboardad.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(dashboardad.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DashboardAd.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DashboardAdUpsertOne) Ignore() *DashboardAdUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DashboardAdUpsertOne) DoNothing() *DashboardAdUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DashboardAdCreate.OnConflict
// documentation for more info.
func (u *DashboardAdUpsertOne) Update(set func(*DashboardAdUpsert)) *DashboardAdUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DashboardAdUpsert{UpdateSet: update})
	}))
	return u
}

// SetImageURL sets the "image_url" field.
func (u *DashboardAdUpsertOne) SetImageURL(v string) *DashboardAdUpsertOne {
	return u.Update(func(s *DashboardAdUpsert) {
		s.SetImageURL(v)
	})
}

// UpdateImageURL sets the "image_url" field to the value that was provided on create.
func (u *DashboardAdUpsertOne) UpdateImageURL() *DashboardAdUpsertOne {
	return u.Update(func(s *DashboardAdUpsert) {
		s.UpdateImageURL()
	})
}

// SetLinkURL sets the "link_url" field.
func (u *DashboardAdUpsertOne) SetLinkURL(v string) *DashboardAdUpsertOne {
	return u.Update(func(s *DashboardAdUpsert) {
		s.SetLinkURL(v)
	})
}

// UpdateLinkURL sets the "link_url" field to the value that was provided on create.
func (u *DashboardAdUpsertOne) UpdateLinkURL() *DashboardAdUpsertOne {
	return u.Update(func(s *DashboardAdUpsert) {
		s.UpdateLinkURL()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *DashboardAdUpsertOne) SetStartsAt(v time.Time) *DashboardAdUpsertOne {
	return u.Update(func(s *DashboardAdUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *DashboardAdUpsertOne) UpdateStartsAt() *DashboardAdUpsertOne {
	return u.Update(func(s *DashboardAdUpsert) {
		s.UpdateStartsAt()
	})
}

// ClearStartsAt clears the value of the "starts_at" field.
func (u *DashboardAdUpsertOne) ClearStartsAt() *DashboardAdUpsertOne {
	return u.Update(func(s *DashboardAdUpsert) {
		s.ClearStartsAt()
	})
}

// SetEndsAt sets the "ends_at" field.
func (u *DashboardAdUpsertOne) SetEndsAt(v time.Time) *DashboardAdUpsertOne {
	return u.Update(func(s *DashboardAdUpsert) {
		s.SetEndsAt(v)
	})
}

// UpdateEndsAt sets the "ends_at" field to the value that was provided on create.
func (u *DashboardAdUpsertOne) UpdateEndsAt() *DashboardAdUpsertOne {
	return u.Update(func(s *DashboardAdUpsert) {
		s.UpdateEndsAt()
	})
}

// ClearEndsAt clears the value of the "ends_at" field.
func (u *DashboardAdUpsertOne) ClearEndsAt() *DashboardAdUpsertOne {
	return u.Update(func(s *DashboardAdUpsert) {
		s.ClearEndsAt()
	})
}

// SetEnabled sets the "enabled" field.
func (u *DashboardAdUpsertOne) SetEnabled(v bool) *DashboardAdUpsertOne {
	return u.Update(func(s *DashboardAdUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *DashboardAdUpsertOne) UpdateEnabled() *DashboardAdUpsertOne {
	return u.Update(func(s *DashboardAdUpsert) {
		s.UpdateEnabled()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *DashboardAdUpsertOne) SetSortOrder(v int) *DashboardAdUpsertOne {
	return u.Update(func(s *DashboardAdUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *DashboardAdUpsertOne) AddSortOrder(v int) *DashboardAdUpsertOne {
	return u.Update(func(s *DashboardAdUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *DashboardAdUpsertOne) UpdateSortOrder() *DashboardAdUpsertOne {
	return u.Update(func(s *DashboardAdUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DashboardAdUpsertOne) SetUpdatedAt(v time.Time) *DashboardAdUpsertOne {
	return u.Update(func(s *DashboardAdUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DashboardAdUpsertOne) UpdateUpdatedAt() *DashboardAdUpsertOne {
	return u.Update(func(s *DashboardAdUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *DashboardAdUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DashboardAdCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DashboardAdUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DashboardAdUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: DashboardAdUpsertOne.ID is not supported by MySQL driver. Use DashboardAdUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DashboardAdUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DashboardAdCreateBulk is the builder for creating many DashboardAd entities in bulk.
type DashboardAdCreateBulk struct {
	config
	err      error
	builders []*DashboardAdCreate
	conflict []sql.ConflictOption
}

// Save creates the DashboardAd entities in the database.
func (_c *DashboardAdCreateBulk) Save(ctx context.Context) ([]*DashboardAd, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DashboardAd, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DashboardAdMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DashboardAdCreateBulk) SaveX(ctx context.Context) []*DashboardAd {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DashboardAdCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DashboardAdCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DashboardAd.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DashboardAdUpsert) {
//			SetImageURL(v+v).
//		}).
//		Exec(ctx)
func (_c *DashboardAdCreateBulk) OnConflict(opts ...sql.ConflictOption) *DashboardAdUpsertBulk {
	_c.conflict = opts
	return &DashboardAdUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DashboardAd.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DashboardAdCreateBulk) OnConflictColumns(columns ...string) *DashboardAdUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DashboardAdUpsertBulk{
		create: _c,
	}
}

// DashboardAdUpsertBulk is the builder for "upsert"-ing
// a bulk of DashboardAd nodes.
type DashboardAdUpsertBulk struct {
	create *DashboardAdCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DashboardAd.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(dashboardad.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DashboardAdUpsertBulk) UpdateNewValues() *DashboardAdUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(dashboardad.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(dashboardad.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DashboardAd.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DashboardAdUpsertBulk) Ignore() *DashboardAdUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DashboardAdUpsertBulk) DoNothing() *DashboardAdUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DashboardAdCreateBulk.OnConflict
// documentation for more info.
func (u *DashboardAdUpsertBulk) Update(set func(*DashboardAdUpsert)) *DashboardAdUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DashboardAdUpsert{UpdateSet: update})
	}))
	return u
}

// SetImageURL sets the "image_url" field.
func (u *DashboardAdUpsertBulk) SetImageURL(v string) *DashboardAdUpsertBulk {
	return u.Update(func(s *DashboardAdUpsert) {
		s.SetImageURL(v)
	})
}

// UpdateImageURL sets the "image_url" field to the value that was provided on create.
func (u *DashboardAdUpsertBulk) UpdateImageURL() *DashboardAdUpsertBulk {
	return u.Update(func(s *DashboardAdUpsert) {
		s.UpdateImageURL()
	})
}

// SetLinkURL sets the "link_url" field.
func (u *DashboardAdUpsertBulk) SetLinkURL(v string) *DashboardAdUpsertBulk {
	return u.Update(func(s *DashboardAdUpsert) {
		s.SetLinkURL(v)
	})
}

// UpdateLinkURL sets the "link_url" field to the value that was provided on create.
func (u *DashboardAdUpsertBulk) UpdateLinkURL() *DashboardAdUpsertBulk {
	return u.Update(func(s *DashboardAdUpsert) {
		s.UpdateLinkURL()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *DashboardAdUpsertBulk) SetStartsAt(v time.Time) *DashboardAdUpsertBulk {
	return u.Update(func(s *DashboardAdUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *DashboardAdUpsertBulk) UpdateStartsAt() *DashboardAdUpsertBulk {
	return u.Update(func(s *DashboardAdUpsert) {
		s.UpdateStartsAt()
	})
}

// ClearStartsAt clears the value of the "starts_at" field.
func (u *DashboardAdUpsertBulk) ClearStartsAt() *DashboardAdUpsertBulk {
	return u.Update(func(s *DashboardAdUpsert) {
		s.ClearStartsAt()
	})
}

// SetEndsAt sets the "ends_at" field.
func (u *DashboardAdUpsertBulk) SetEndsAt(v time.Time) *DashboardAdUpsertBulk {
	return u.Update(func(s *DashboardAdUpsert) {
		s.SetEndsAt(v)
	})
}

// UpdateEndsAt sets the "ends_at" field to the value that was provided on create.
func (u *DashboardAdUpsertBulk) UpdateEndsAt() *DashboardAdUpsertBulk {
	return u.Update(func(s *DashboardAdUpsert) {
		s.UpdateEndsAt()
	})
}

// ClearEndsAt clears the value of the "ends_at" field.
func (u *DashboardAdUpsertBulk) ClearEndsAt() *DashboardAdUpsertBulk {
	return u.Update(func(s *DashboardAdUpsert) {
		s.ClearEndsAt()
	})
}

// SetEnabled sets the "enabled" field.
func (u *DashboardAdUpsertBulk) SetEnabled(v bool) *DashboardAdUpsertBulk {
	return u.Update(func(s *DashboardAdUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *DashboardAdUpsertBulk) UpdateEnabled() *DashboardAdUpsertBulk {
	return u.Update(func(s *DashboardAdUpsert) {
		s.UpdateEnabled()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *DashboardAdUpsertBulk) SetSortOrder(v int) *DashboardAdUpsertBulk {
	return u.Update(func(s *DashboardAdUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *DashboardAdUpsertBulk) AddSortOrder(v int) *DashboardAdUpsertBulk {
	return u.Update(func(s *DashboardAdUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *DashboardAdUpsertBulk) UpdateSortOrder() *DashboardAdUpsertBulk {
	return u.Update(func(s *DashboardAdUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DashboardAdUpsertBulk) SetUpdatedAt(v time.Time) *DashboardAdUpsertBulk {
	return u.Update(func(s *DashboardAdUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DashboardAdUpsertBulk) UpdateUpdatedAt() *DashboardAdUpsertBulk {
	return u.Update(func(s *DashboardAdUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *DashboardAdUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DashboardAdCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DashboardAdCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DashboardAdUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
