// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/BrandonVee/TokenRouter/ent/dashboardad"
	"github.com/BrandonVee/TokenRouter/ent/predicate"
)

// DashboardAdDelete is the builder for deleting a DashboardAd entity.
type DashboardAdDelete struct {
	config
	hooks    []Hook
	mutation *DashboardAdMutation
}

// Where appends a list predicates to the DashboardAdDelete builder.
func (_d *DashboardAdDelete) Where(ps ...predicate.DashboardAd) *DashboardAdDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DashboardAdDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DashboardAdDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DashboardAdDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(dashboardad.Table, sqlgraph.NewFieldSpec(dashboardad.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DashboardAdDeleteOne is the builder for deleting a single DashboardAd entity.
type DashboardAdDeleteOne struct {
	_d *DashboardAdDelete
}

// Where appends a list predicates to the DashboardAdDelete builder.
func (_d *DashboardAdDeleteOne) Where(ps ...predicate.DashboardAd) *DashboardAdDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DashboardAdDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{dashboardad.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DashboardAdDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
