// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/BrandonVee/TokenRouter/ent/imagehistory"
	"github.com/BrandonVee/TokenRouter/ent/predicate"
)

// ImageHistoryUpdate is the builder for updating ImageHistory entities.
type ImageHistoryUpdate struct {
	config
	hooks    []Hook
	mutation *ImageHistoryMutation
}

// Where appends a list predicates to the ImageHistoryUpdate builder.
func (_u *ImageHistoryUpdate) Where(ps ...predicate.ImageHistory) *ImageHistoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *ImageHistoryUpdate) SetRequestID(v string) *ImageHistoryUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *ImageHistoryUpdate) SetNillableRequestID(v *string) *ImageHistoryUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *ImageHistoryUpdate) SetSource(v string) *ImageHistoryUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *ImageHistoryUpdate) SetNillableSource(v *string) *ImageHistoryUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *ImageHistoryUpdate) SetEndpoint(v string) *ImageHistoryUpdate {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *ImageHistoryUpdate) SetNillableEndpoint(v *string) *ImageHistoryUpdate {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *ImageHistoryUpdate) SetModel(v string) *ImageHistoryUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *ImageHistoryUpdate) SetNillableModel(v *string) *ImageHistoryUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *ImageHistoryUpdate) SetPrompt(v string) *ImageHistoryUpdate {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *ImageHistoryUpdate) SetNillablePrompt(v *string) *ImageHistoryUpdate {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// SetRevisedPrompt sets the "revised_prompt" field.
func (_u *ImageHistoryUpdate) SetRevisedPrompt(v string) *ImageHistoryUpdate {
	_u.mutation.SetRevisedPrompt(v)
	return _u
}

// SetNillableRevisedPrompt sets the "revised_prompt" field if the given value is not nil.
func (_u *ImageHistoryUpdate) SetNillableRevisedPrompt(v *string) *ImageHistoryUpdate {
	if v != nil {
		_u.SetRevisedPrompt(*v)
	}
	return _u
}

// SetParameters sets the "parameters" field.
func (_u *ImageHistoryUpdate) SetParameters(v string) *ImageHistoryUpdate {
	_u.mutation.SetParameters(v)
	return _u
}

// SetNillableParameters sets the "parameters" field if the given value is not nil.
func (_u *ImageHistoryUpdate) SetNillableParameters(v *string) *ImageHistoryUpdate {
	if v != nil {
		_u.SetParameters(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *ImageHistoryUpdate) SetMimeType(v string) *ImageHistoryUpdate {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *ImageHistoryUpdate) SetNillableMimeType(v *string) *ImageHistoryUpdate {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *ImageHistoryUpdate) SetSizeBytes(v int64) *ImageHistoryUpdate {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *ImageHistoryUpdate) SetNillableSizeBytes(v *int64) *ImageHistoryUpdate {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *ImageHistoryUpdate) AddSizeBytes(v int64) *ImageHistoryUpdate {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetWidth sets the "width" field.
func (_u *ImageHistoryUpdate) SetWidth(v int) *ImageHistoryUpdate {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *ImageHistoryUpdate) SetNillableWidth(v *int) *ImageHistoryUpdate {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *ImageHistoryUpdate) AddWidth(v int) *ImageHistoryUpdate {
	_u.mutation.AddWidth(v)
	return _u
}

// SetHeight sets the "height" field.
func (_u *ImageHistoryUpdate) SetHeight(v int) *ImageHistoryUpdate {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *ImageHistoryUpdate) SetNillableHeight(v *int) *ImageHistoryUpdate {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *ImageHistoryUpdate) AddHeight(v int) *ImageHistoryUpdate {
	_u.mutation.AddHeight(v)
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *ImageHistoryUpdate) SetSha256(v string) *ImageHistoryUpdate {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *ImageHistoryUpdate) SetNillableSha256(v *string) *ImageHistoryUpdate {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// Mutation returns the ImageHistoryMutation object of the builder.
func (_u *ImageHistoryUpdate) Mutation() *ImageHistoryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ImageHistoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ImageHistoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageHistoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageHistoryUpdate) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := imagehistory.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "ImageHistory.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := imagehistory.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "ImageHistory.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Endpoint(); ok {
		if err := imagehistory.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "ImageHistory.endpoint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := imagehistory.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ImageHistory.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := imagehistory.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "ImageHistory.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SizeBytes(); ok {
		if err := imagehistory.SizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "size_bytes", err: fmt.Errorf(`ent: validator failed for field "ImageHistory.size_bytes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Width(); ok {
		if err := imagehistory.WidthValidator(v); err != nil {
			return &ValidationError{Name: "width", err: fmt.Errorf(`ent: validator failed for field "ImageHistory.width": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Height(); ok {
		if err := imagehistory.HeightValidator(v); err != nil {
			return &ValidationError{Name: "height", err: fmt.Errorf(`ent: validator failed for field "ImageHistory.height": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sha256(); ok {
		if err := imagehistory.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "ImageHistory.sha256": %w`, err)}
		}
	}
	return nil
}

func (_u *ImageHistoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(imagehistory.Table, imagehistory.Columns, sqlgraph.NewFieldSpec(imagehistory.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(imagehistory.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(imagehistory.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(imagehistory.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(imagehistory.FieldEndpoint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(imagehistory.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(imagehistory.FieldPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.RevisedPrompt(); ok {
		_spec.SetField(imagehistory.FieldRevisedPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.Parameters(); ok {
		_spec.SetField(imagehistory.FieldParameters, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(imagehistory.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(imagehistory.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(imagehistory.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(imagehistory.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(imagehistory.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(imagehistory.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(imagehistory.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(imagehistory.FieldSha256, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{imagehistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ImageHistoryUpdateOne is the builder for updating a single ImageHistory entity.
type ImageHistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ImageHistoryMutation
}

// SetRequestID sets the "request_id" field.
func (_u *ImageHistoryUpdateOne) SetRequestID(v string) *ImageHistoryUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *ImageHistoryUpdateOne) SetNillableRequestID(v *string) *ImageHistoryUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *ImageHistoryUpdateOne) SetSource(v string) *ImageHistoryUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *ImageHistoryUpdateOne) SetNillableSource(v *string) *ImageHistoryUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *ImageHistoryUpdateOne) SetEndpoint(v string) *ImageHistoryUpdateOne {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *ImageHistoryUpdateOne) SetNillableEndpoint(v *string) *ImageHistoryUpdateOne {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *ImageHistoryUpdateOne) SetModel(v string) *ImageHistoryUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *ImageHistoryUpdateOne) SetNillableModel(v *string) *ImageHistoryUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *ImageHistoryUpdateOne) SetPrompt(v string) *ImageHistoryUpdateOne {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *ImageHistoryUpdateOne) SetNillablePrompt(v *string) *ImageHistoryUpdateOne {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// SetRevisedPrompt sets the "revised_prompt" field.
func (_u *ImageHistoryUpdateOne) SetRevisedPrompt(v string) *ImageHistoryUpdateOne {
	_u.mutation.SetRevisedPrompt(v)
	return _u
}

// SetNillableRevisedPrompt sets the "revised_prompt" field if the given value is not nil.
func (_u *ImageHistoryUpdateOne) SetNillableRevisedPrompt(v *string) *ImageHistoryUpdateOne {
	if v != nil {
		_u.SetRevisedPrompt(*v)
	}
	return _u
}

// SetParameters sets the "parameters" field.
func (_u *ImageHistoryUpdateOne) SetParameters(v string) *ImageHistoryUpdateOne {
	_u.mutation.SetParameters(v)
	return _u
}

// SetNillableParameters sets the "parameters" field if the given value is not nil.
func (_u *ImageHistoryUpdateOne) SetNillableParameters(v *string) *ImageHistoryUpdateOne {
	if v != nil {
		_u.SetParameters(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *ImageHistoryUpdateOne) SetMimeType(v string) *ImageHistoryUpdateOne {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *ImageHistoryUpdateOne) SetNillableMimeType(v *string) *ImageHistoryUpdateOne {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *ImageHistoryUpdateOne) SetSizeBytes(v int64) *ImageHistoryUpdateOne {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *ImageHistoryUpdateOne) SetNillableSizeBytes(v *int64) *ImageHistoryUpdateOne {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *ImageHistoryUpdateOne) AddSizeBytes(v int64) *ImageHistoryUpdateOne {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetWidth sets the "width" field.
func (_u *ImageHistoryUpdateOne) SetWidth(v int) *ImageHistoryUpdateOne {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *ImageHistoryUpdateOne) SetNillableWidth(v *int) *ImageHistoryUpdateOne {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *ImageHistoryUpdateOne) AddWidth(v int) *ImageHistoryUpdateOne {
	_u.mutation.AddWidth(v)
	return _u
}

// SetHeight sets the "height" field.
func (_u *ImageHistoryUpdateOne) SetHeight(v int) *ImageHistoryUpdateOne {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *ImageHistoryUpdateOne) SetNillableHeight(v *int) *ImageHistoryUpdateOne {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *ImageHistoryUpdateOne) AddHeight(v int) *ImageHistoryUpdateOne {
	_u.mutation.AddHeight(v)
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *ImageHistoryUpdateOne) SetSha256(v string) *ImageHistoryUpdateOne {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *ImageHistoryUpdateOne) SetNillableSha256(v *string) *ImageHistoryUpdateOne {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// Mutation returns the ImageHistoryMutation object of the builder.
func (_u *ImageHistoryUpdateOne) Mutation() *ImageHistoryMutation {
	return _u.mutation
}

// Where appends a list predicates to the ImageHistoryUpdate builder.
func (_u *ImageHistoryUpdateOne) Where(ps ...predicate.ImageHistory) *ImageHistoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ImageHistoryUpdateOne) Select(field string, fields ...string) *ImageHistoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ImageHistory entity.
func (_u *ImageHistoryUpdateOne) Save(ctx context.Context) (*ImageHistory, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageHistoryUpdateOne) SaveX(ctx context.Context) *ImageHistory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ImageHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageHistoryUpdateOne) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := imagehistory.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "ImageHistory.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := imagehistory.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "ImageHistory.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Endpoint(); ok {
		if err := imagehistory.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "ImageHistory.endpoint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := imagehistory.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ImageHistory.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := imagehistory.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "ImageHistory.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SizeBytes(); ok {
		if err := imagehistory.SizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "size_bytes", err: fmt.Errorf(`ent: validator failed for field "ImageHistory.size_bytes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Width(); ok {
		if err := imagehistory.WidthValidator(v); err != nil {
			return &ValidationError{Name: "width", err: fmt.Errorf(`ent: validator failed for field "ImageHistory.width": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Height(); ok {
		if err := imagehistory.HeightValidator(v); err != nil {
			return &ValidationError{Name: "height", err: fmt.Errorf(`ent: validator failed for field "ImageHistory.height": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sha256(); ok {
		if err := imagehistory.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "ImageHistory.sha256": %w`, err)}
		}
	}
	return nil
}

func (_u *ImageHistoryUpdateOne) sqlSave(ctx context.Context) (_node *ImageHistory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(imagehistory.Table, imagehistory.Columns, sqlgraph.NewFieldSpec(imagehistory.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ImageHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, imagehistory.FieldID)
		for _, f := range fields {
			if !imagehistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != imagehistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(imagehistory.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(imagehistory.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(imagehistory.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(imagehistory.FieldEndpoint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(imagehistory.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(imagehistory.FieldPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.RevisedPrompt(); ok {
		_spec.SetField(imagehistory.FieldRevisedPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.Parameters(); ok {
		_spec.SetField(imagehistory.FieldParameters, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(imagehistory.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(imagehistory.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(imagehistory.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(imagehistory.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(imagehistory.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(imagehistory.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(imagehistory.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(imagehistory.FieldSha256, field.TypeString, value)
	}
	_node = &ImageHistory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{imagehistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
