// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/BrandonVee/TokenRouter/ent/imagehistory"
)

// ImageHistory is the model entity for the ImageHistory schema.
type ImageHistory struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID *int64 `json:"api_key_id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// Endpoint holds the value of the "endpoint" field.
	Endpoint string `json:"endpoint,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// Prompt holds the value of the "prompt" field.
	Prompt string `json:"prompt,omitempty"`
	// RevisedPrompt holds the value of the "revised_prompt" field.
	RevisedPrompt string `json:"revised_prompt,omitempty"`
	// ObjectKey holds the value of the "object_key" field.
	ObjectKey string `json:"object_key,omitempty"`
	// MimeType holds the value of the "mime_type" field.
	MimeType string `json:"mime_type,omitempty"`
	// SizeBytes holds the value of the "size_bytes" field.
	SizeBytes int64 `json:"size_bytes,omitempty"`
	// Width holds the value of the "width" field.
	Width int `json:"width,omitempty"`
	// Height holds the value of the "height" field.
	Height int `json:"height,omitempty"`
	// Sha256 holds the value of the "sha256" field.
	Sha256 string `json:"sha256,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ImageHistory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case imagehistory.FieldUserID, imagehistory.FieldAPIKeyID, imagehistory.FieldSizeBytes, imagehistory.FieldWidth, imagehistory.FieldHeight:
			values[i] = new(sql.NullInt64)
		case imagehistory.FieldID, imagehistory.FieldRequestID, imagehistory.FieldSource, imagehistory.FieldEndpoint, imagehistory.FieldModel, imagehistory.FieldPrompt, imagehistory.FieldRevisedPrompt, imagehistory.FieldObjectKey, imagehistory.FieldMimeType, imagehistory.FieldSha256:
			values[i] = new(sql.NullString)
		case imagehistory.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ImageHistory fields.
func (_m *ImageHistory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case imagehistory.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case imagehistory.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case imagehistory.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = new(int64)
				*_m.APIKeyID = value.Int64
			}
		case imagehistory.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case imagehistory.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case imagehistory.FieldEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field endpoint", values[i])
			} else if value.Valid {
				_m.Endpoint = value.String
			}
		case imagehistory.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case imagehistory.FieldPrompt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt", values[i])
			} else if value.Valid {
				_m.Prompt = value.String
			}
		case imagehistory.FieldRevisedPrompt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field revised_prompt", values[i])
			} else if value.Valid {
				_m.RevisedPrompt = value.String
			}
		case imagehistory.FieldObjectKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field object_key", values[i])
			} else if value.Valid {
				_m.ObjectKey = value.String
			}
		case imagehistory.FieldMimeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mime_type", values[i])
			} else if value.Valid {
				_m.MimeType = value.String
			}
		case imagehistory.FieldSizeBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size_bytes", values[i])
			} else if value.Valid {
				_m.SizeBytes = value.Int64
			}
		case imagehistory.FieldWidth:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field width", values[i])
			} else if value.Valid {
				_m.Width = int(value.Int64)
			}
		case imagehistory.FieldHeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field height", values[i])
			} else if value.Valid {
				_m.Height = int(value.Int64)
			}
		case imagehistory.FieldSha256:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sha256", values[i])
			} else if value.Valid {
				_m.Sha256 = value.String
			}
		case imagehistory.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ImageHistory.
// This includes values selected through modifiers, order, etc.
func (_m *ImageHistory) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ImageHistory.
// Note that you need to call ImageHistory.Unwrap() before calling this method if this ImageHistory
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ImageHistory) Update() *ImageHistoryUpdateOne {
	return NewImageHistoryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ImageHistory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ImageHistory) Unwrap() *ImageHistory {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ImageHistory is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ImageHistory) String() string {
	var builder strings.Builder
	builder.WriteString("ImageHistory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	if v := _m.APIKeyID; v != nil {
		builder.WriteString("api_key_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("endpoint=")
	builder.WriteString(_m.Endpoint)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("prompt=")
	builder.WriteString(_m.Prompt)
	builder.WriteString(", ")
	builder.WriteString("revised_prompt=")
	builder.WriteString(_m.RevisedPrompt)
	builder.WriteString(", ")
	builder.WriteString("object_key=")
	builder.WriteString(_m.ObjectKey)
	builder.WriteString(", ")
	builder.WriteString("mime_type=")
	builder.WriteString(_m.MimeType)
	builder.WriteString(", ")
	builder.WriteString("size_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.SizeBytes))
	builder.WriteString(", ")
	builder.WriteString("width=")
	builder.WriteString(fmt.Sprintf("%v", _m.Width))
	builder.WriteString(", ")
	builder.WriteString("height=")
	builder.WriteString(fmt.Sprintf("%v", _m.Height))
	builder.WriteString(", ")
	builder.WriteString("sha256=")
	builder.WriteString(_m.Sha256)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ImageHistories is a parsable slice of ImageHistory.
type ImageHistories []*ImageHistory
