// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/BrandonVee/TokenRouter/ent/imagehistory"
)

// ImageHistoryCreate is the builder for creating a ImageHistory entity.
type ImageHistoryCreate struct {
	config
	mutation *ImageHistoryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *ImageHistoryCreate) SetUserID(v int64) *ImageHistoryCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *ImageHistoryCreate) SetAPIKeyID(v int64) *ImageHistoryCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_c *ImageHistoryCreate) SetNillableAPIKeyID(v *int64) *ImageHistoryCreate {
	if v != nil {
		_c.SetAPIKeyID(*v)
	}
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *ImageHistoryCreate) SetRequestID(v string) *ImageHistoryCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *ImageHistoryCreate) SetNillableRequestID(v *string) *ImageHistoryCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *ImageHistoryCreate) SetSource(v string) *ImageHistoryCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetEndpoint sets the "endpoint" field.
func (_c *ImageHistoryCreate) SetEndpoint(v string) *ImageHistoryCreate {
	_c.mutation.SetEndpoint(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *ImageHistoryCreate) SetModel(v string) *ImageHistoryCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *ImageHistoryCreate) SetNillableModel(v *string) *ImageHistoryCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetPrompt sets the "prompt" field.
func (_c *ImageHistoryCreate) SetPrompt(v string) *ImageHistoryCreate {
	_c.mutation.SetPrompt(v)
	return _c
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_c *ImageHistoryCreate) SetNillablePrompt(v *string) *ImageHistoryCreate {
	if v != nil {
		_c.SetPrompt(*v)
	}
	return _c
}

// SetRevisedPrompt sets the "revised_prompt" field.
func (_c *ImageHistoryCreate) SetRevisedPrompt(v string) *ImageHistoryCreate {
	_c.mutation.SetRevisedPrompt(v)
	return _c
}

// SetNillableRevisedPrompt sets the "revised_prompt" field if the given value is not nil.
func (_c *ImageHistoryCreate) SetNillableRevisedPrompt(v *string) *ImageHistoryCreate {
	if v != nil {
		_c.SetRevisedPrompt(*v)
	}
	return _c
}

// SetObjectKey sets the "object_key" field.
func (_c *ImageHistoryCreate) SetObjectKey(v string) *ImageHistoryCreate {
	_c.mutation.SetObjectKey(v)
	return _c
}

// SetMimeType sets the "mime_type" field.
func (_c *ImageHistoryCreate) SetMimeType(v string) *ImageHistoryCreate {
	_c.mutation.SetMimeType(v)
	return _c
}

// SetSizeBytes sets the "size_bytes" field.
func (_c *ImageHistoryCreate) SetSizeBytes(v int64) *ImageHistoryCreate {
	_c.mutation.SetSizeBytes(v)
	return _c
}

// SetWidth sets the "width" field.
func (_c *ImageHistoryCreate) SetWidth(v int) *ImageHistoryCreate {
	_c.mutation.SetWidth(v)
	return _c
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_c *ImageHistoryCreate) SetNillableWidth(v *int) *ImageHistoryCreate {
	if v != nil {
		_c.SetWidth(*v)
	}
	return _c
}

// SetHeight sets the "height" field.
func (_c *ImageHistoryCreate) SetHeight(v int) *ImageHistoryCreate {
	_c.mutation.SetHeight(v)
	return _c
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_c *ImageHistoryCreate) SetNillableHeight(v *int) *ImageHistoryCreate {
	if v != nil {
		_c.SetHeight(*v)
	}
	return _c
}

// SetSha256 sets the "sha256" field.
func (_c *ImageHistoryCreate) SetSha256(v string) *ImageHistoryCreate {
	_c.mutation.SetSha256(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ImageHistoryCreate) SetCreatedAt(v time.Time) *ImageHistoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ImageHistoryCreate) SetNillableCreatedAt(v *time.Time) *ImageHistoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ImageHistoryCreate) SetID(v string) *ImageHistoryCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ImageHistoryMutation object of the builder.
func (_c *ImageHistoryCreate) Mutation() *ImageHistoryMutation {
	return _c.mutation
}

// Save creates the ImageHistory in the database.
func (_c *ImageHistoryCreate) Save(ctx context.Context) (*ImageHistory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ImageHistoryCreate) SaveX(ctx context.Context) *ImageHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImageHistoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImageHistoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ImageHistoryCreate) defaults() {
	if _, ok := _c.mutation.RequestID(); !ok {
		v := imagehistory.DefaultRequestID
		_c.mutation.SetRequestID(v)
	}
	if _, ok := _c.mutation.Model(); !ok {
		v := imagehistory.DefaultModel
		_c.mutation.SetModel(v)
	}
	if _, ok := _c.mutation.Prompt(); !ok {
		v := imagehistory.DefaultPrompt
		_c.mutation.SetPrompt(v)
	}
	if _, ok := _c.mutation.RevisedPrompt(); !ok {
		v := imagehistory.DefaultRevisedPrompt
		_c.mutation.SetRevisedPrompt(v)
	}
	if _, ok := _c.mutation.Width(); !ok {
		v := imagehistory.DefaultWidth
		_c.mutation.SetWidth(v)
	}
	if _, ok := _c.mutation.Height(); !ok {
		v := imagehistory.DefaultHeight
		_c.mutation.SetHeight(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := imagehistory.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ImageHistoryCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ImageHistory.user_id"`)}
	}
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "ImageHistory.request_id"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := imagehistory.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "ImageHistory.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "ImageHistory.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := imagehistory.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "ImageHistory.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Endpoint(); !ok {
		return &ValidationError{Name: "endpoint", err: errors.New(`ent: missing required field "ImageHistory.endpoint"`)}
	}
	if v, ok := _c.mutation.Endpoint(); ok {
		if err := imagehistory.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "ImageHistory.endpoint": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "ImageHistory.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := imagehistory.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ImageHistory.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Prompt(); !ok {
		return &ValidationError{Name: "prompt", err: errors.New(`ent: missing required field "ImageHistory.prompt"`)}
	}
	if _, ok := _c.mutation.RevisedPrompt(); !ok {
		return &ValidationError{Name: "revised_prompt", err: errors.New(`ent: missing required field "ImageHistory.revised_prompt"`)}
	}
	if _, ok := _c.mutation.ObjectKey(); !ok {
		return &ValidationError{Name: "object_key", err: errors.New(`ent: missing required field "ImageHistory.object_key"`)}
	}
	if _, ok := _c.mutation.MimeType(); !ok {
		return &ValidationError{Name: "mime_type", err: errors.New(`ent: missing required field "ImageHistory.mime_type"`)}
	}
	if v, ok := _c.mutation.MimeType(); ok {
		if err := imagehistory.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "ImageHistory.mime_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SizeBytes(); !ok {
		return &ValidationError{Name: "size_bytes", err: errors.New(`ent: missing required field "ImageHistory.size_bytes"`)}
	}
	if v, ok := _c.mutation.SizeBytes(); ok {
		if err := imagehistory.SizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "size_bytes", err: fmt.Errorf(`ent: validator failed for field "ImageHistory.size_bytes": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Width(); !ok {
		return &ValidationError{Name: "width", err: errors.New(`ent: missing required field "ImageHistory.width"`)}
	}
	if v, ok := _c.mutation.Width(); ok {
		if err := imagehistory.WidthValidator(v); err != nil {
			return &ValidationError{Name: "width", err: fmt.Errorf(`ent: validator failed for field "ImageHistory.width": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Height(); !ok {
		return &ValidationError{Name: "height", err: errors.New(`ent: missing required field "ImageHistory.height"`)}
	}
	if v, ok := _c.mutation.Height(); ok {
		if err := imagehistory.HeightValidator(v); err != nil {
			return &ValidationError{Name: "height", err: fmt.Errorf(`ent: validator failed for field "ImageHistory.height": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Sha256(); !ok {
		return &ValidationError{Name: "sha256", err: errors.New(`ent: missing required field "ImageHistory.sha256"`)}
	}
	if v, ok := _c.mutation.Sha256(); ok {
		if err := imagehistory.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "ImageHistory.sha256": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ImageHistory.created_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := imagehistory.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ImageHistory.id": %w`, err)}
		}
	}
	return nil
}

func (_c *ImageHistoryCreate) sqlSave(ctx context.Context) (*ImageHistory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ImageHistory.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ImageHistoryCreate) createSpec() (*ImageHistory, *sqlgraph.CreateSpec) {
	var (
		_node = &ImageHistory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(imagehistory.Table, sqlgraph.NewFieldSpec(imagehistory.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(imagehistory.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(imagehistory.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = &value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(imagehistory.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(imagehistory.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.Endpoint(); ok {
		_spec.SetField(imagehistory.FieldEndpoint, field.TypeString, value)
		_node.Endpoint = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(imagehistory.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Prompt(); ok {
		_spec.SetField(imagehistory.FieldPrompt, field.TypeString, value)
		_node.Prompt = value
	}
	if value, ok := _c.mutation.RevisedPrompt(); ok {
		_spec.SetField(imagehistory.FieldRevisedPrompt, field.TypeString, value)
		_node.RevisedPrompt = value
	}
	if value, ok := _c.mutation.ObjectKey(); ok {
		_spec.SetField(imagehistory.FieldObjectKey, field.TypeString, value)
		_node.ObjectKey = value
	}
	if value, ok := _c.mutation.MimeType(); ok {
		_spec.SetField(imagehistory.FieldMimeType, field.TypeString, value)
		_node.MimeType = value
	}
	if value, ok := _c.mutation.SizeBytes(); ok {
		_spec.SetField(imagehistory.FieldSizeBytes, field.TypeInt64, value)
		_node.SizeBytes = value
	}
	if value, ok := _c.mutation.Width(); ok {
		_spec.SetField(imagehistory.FieldWidth, field.TypeInt, value)
		_node.Width = value
	}
	if value, ok := _c.mutation.Height(); ok {
		_spec.SetField(imagehistory.FieldHeight, field.TypeInt, value)
		_node.Height = value
	}
	if value, ok := _c.mutation.Sha256(); ok {
		_spec.SetField(imagehistory.FieldSha256, field.TypeString, value)
		_node.Sha256 = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(imagehistory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ImageHistory.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ImageHistoryUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *ImageHistoryCreate) OnConflict(opts ...sql.ConflictOption) *ImageHistoryUpsertOne {
	_c.conflict = opts
	return &ImageHistoryUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ImageHistory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ImageHistoryCreate) OnConflictColumns(columns ...string) *ImageHistoryUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ImageHistoryUpsertOne{
		create: _c,
	}
}

type (
	// ImageHistoryUpsertOne is the builder for "upsert"-ing
	//  one ImageHistory node.
	ImageHistoryUpsertOne struct {
		create *ImageHistoryCreate
	}

	// ImageHistoryUpsert is the "OnConflict" setter.
	ImageHistoryUpsert struct {
		*sql.UpdateSet
	}
)

// SetRequestID sets the "request_id" field.
func (u *ImageHistoryUpsert) SetRequestID(v string) *ImageHistoryUpsert {
	u.Set(imagehistory.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *ImageHistoryUpsert) UpdateRequestID() *ImageHistoryUpsert {
	u.SetExcluded(imagehistory.FieldRequestID)
	return u
}

// SetSource sets the "source" field.
func (u *ImageHistoryUpsert) SetSource(v string) *ImageHistoryUpsert {
	u.Set(imagehistory.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *ImageHistoryUpsert) UpdateSource() *ImageHistoryUpsert {
	u.SetExcluded(imagehistory.FieldSource)
	return u
}

// SetEndpoint sets the "endpoint" field.
func (u *ImageHistoryUpsert) SetEndpoint(v string) *ImageHistoryUpsert {
	u.Set(imagehistory.FieldEndpoint, v)
	return u
}

// UpdateEndpoint sets the "endpoint" field to the value that was provided on create.
func (u *ImageHistoryUpsert) UpdateEndpoint() *ImageHistoryUpsert {
	u.SetExcluded(imagehistory.FieldEndpoint)
	return u
}

// SetModel sets the "model" field.
func (u *ImageHistoryUpsert) SetModel(v string) *ImageHistoryUpsert {
	u.Set(imagehistory.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ImageHistoryUpsert) UpdateModel() *ImageHistoryUpsert {
	u.SetExcluded(imagehistory.FieldModel)
	return u
}

// SetPrompt sets the "prompt" field.
func (u *ImageHistoryUpsert) SetPrompt(v string) *ImageHistoryUpsert {
	u.Set(imagehistory.FieldPrompt, v)
	return u
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *ImageHistoryUpsert) UpdatePrompt() *ImageHistoryUpsert {
	u.SetExcluded(imagehistory.FieldPrompt)
	return u
}

// SetRevisedPrompt sets the "revised_prompt" field.
func (u *ImageHistoryUpsert) SetRevisedPrompt(v string) *ImageHistoryUpsert {
	u.Set(imagehistory.FieldRevisedPrompt, v)
	return u
}

// UpdateRevisedPrompt sets the "revised_prompt" field to the value that was provided on create.
func (u *ImageHistoryUpsert) UpdateRevisedPrompt() *ImageHistoryUpsert {
	u.SetExcluded(imagehistory.FieldRevisedPrompt)
	return u
}

// SetMimeType sets the "mime_type" field.
func (u *ImageHistoryUpsert) SetMimeType(v string) *ImageHistoryUpsert {
	u.Set(imagehistory.FieldMimeType, v)
	return u
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *ImageHistoryUpsert) UpdateMimeType() *ImageHistoryUpsert {
	u.SetExcluded(imagehistory.FieldMimeType)
	return u
}

// SetSizeBytes sets the "size_bytes" field.
func (u *ImageHistoryUpsert) SetSizeBytes(v int64) *ImageHistoryUpsert {
	u.Set(imagehistory.FieldSizeBytes, v)
	return u
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *ImageHistoryUpsert) UpdateSizeBytes() *ImageHistoryUpsert {
	u.SetExcluded(imagehistory.FieldSizeBytes)
	return u
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *ImageHistoryUpsert) AddSizeBytes(v int64) *ImageHistoryUpsert {
	u.Add(imagehistory.FieldSizeBytes, v)
	return u
}

// SetWidth sets the "width" field.
func (u *ImageHistoryUpsert) SetWidth(v int) *ImageHistoryUpsert {
	u.Set(imagehistory.FieldWidth, v)
	return u
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *ImageHistoryUpsert) UpdateWidth() *ImageHistoryUpsert {
	u.SetExcluded(imagehistory.FieldWidth)
	return u
}

// AddWidth adds v to the "width" field.
func (u *ImageHistoryUpsert) AddWidth(v int) *ImageHistoryUpsert {
	u.Add(imagehistory.FieldWidth, v)
	return u
}

// SetHeight sets the "height" field.
func (u *ImageHistoryUpsert) SetHeight(v int) *ImageHistoryUpsert {
	u.Set(imagehistory.FieldHeight, v)
	return u
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *ImageHistoryUpsert) UpdateHeight() *ImageHistoryUpsert {
	u.SetExcluded(imagehistory.FieldHeight)
	return u
}

// AddHeight adds v to the "height" field.
func (u *ImageHistoryUpsert) AddHeight(v int) *ImageHistoryUpsert {
	u.Add(imagehistory.FieldHeight, v)
	return u
}

// SetSha256 sets the "sha256" field.
func (u *ImageHistoryUpsert) SetSha256(v string) *ImageHistoryUpsert {
	u.Set(imagehistory.FieldSha256, v)
	return u
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *ImageHistoryUpsert) UpdateSha256() *ImageHistoryUpsert {
	u.SetExcluded(imagehistory.FieldSha256)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ImageHistory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(imagehistory.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ImageHistoryUpsertOne) UpdateNewValues() *ImageHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(imagehistory.FieldID)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(imagehistory.FieldUserID)
		}
		if _, exists := u.create.mutation.APIKeyID(); exists {
			s.SetIgnore(imagehistory.FieldAPIKeyID)
		}
		if _, exists := u.create.mutation.ObjectKey(); exists {
			s.SetIgnore(imagehistory.FieldObjectKey)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(imagehistory.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ImageHistory.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ImageHistoryUpsertOne) Ignore() *ImageHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ImageHistoryUpsertOne) DoNothing() *ImageHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ImageHistoryCreate.OnConflict
// documentation for more info.
func (u *ImageHistoryUpsertOne) Update(set func(*ImageHistoryUpsert)) *ImageHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ImageHistoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *ImageHistoryUpsertOne) SetRequestID(v string) *ImageHistoryUpsertOne {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *ImageHistoryUpsertOne) UpdateRequestID() *ImageHistoryUpsertOne {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.UpdateRequestID()
	})
}

// SetSource sets the "source" field.
func (u *ImageHistoryUpsertOne) SetSource(v string) *ImageHistoryUpsertOne {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *ImageHistoryUpsertOne) UpdateSource() *ImageHistoryUpsertOne {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.UpdateSource()
	})
}

// SetEndpoint sets the "endpoint" field.
func (u *ImageHistoryUpsertOne) SetEndpoint(v string) *ImageHistoryUpsertOne {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.SetEndpoint(v)
	})
}

// UpdateEndpoint sets the "endpoint" field to the value that was provided on create.
func (u *ImageHistoryUpsertOne) UpdateEndpoint() *ImageHistoryUpsertOne {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.UpdateEndpoint()
	})
}

// SetModel sets the "model" field.
func (u *ImageHistoryUpsertOne) SetModel(v string) *ImageHistoryUpsertOne {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ImageHistoryUpsertOne) UpdateModel() *ImageHistoryUpsertOne {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.UpdateModel()
	})
}

// SetPrompt sets the "prompt" field.
func (u *ImageHistoryUpsertOne) SetPrompt(v string) *ImageHistoryUpsertOne {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.SetPrompt(v)
	})
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *ImageHistoryUpsertOne) UpdatePrompt() *ImageHistoryUpsertOne {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.UpdatePrompt()
	})
}

// SetRevisedPrompt sets the "revised_prompt" field.
func (u *ImageHistoryUpsertOne) SetRevisedPrompt(v string) *ImageHistoryUpsertOne {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.SetRevisedPrompt(v)
	})
}

// UpdateRevisedPrompt sets the "revised_prompt" field to the value that was provided on create.
func (u *ImageHistoryUpsertOne) UpdateRevisedPrompt() *ImageHistoryUpsertOne {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.UpdateRevisedPrompt()
	})
}

// SetMimeType sets the "mime_type" field.
func (u *ImageHistoryUpsertOne) SetMimeType(v string) *ImageHistoryUpsertOne {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.SetMimeType(v)
	})
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *ImageHistoryUpsertOne) UpdateMimeType() *ImageHistoryUpsertOne {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.UpdateMimeType()
	})
}

// SetSizeBytes sets the "size_bytes" field.
func (u *ImageHistoryUpsertOne) SetSizeBytes(v int64) *ImageHistoryUpsertOne {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.SetSizeBytes(v)
	})
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *ImageHistoryUpsertOne) AddSizeBytes(v int64) *ImageHistoryUpsertOne {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.AddSizeBytes(v)
	})
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *ImageHistoryUpsertOne) UpdateSizeBytes() *ImageHistoryUpsertOne {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.UpdateSizeBytes()
	})
}

// SetWidth sets the "width" field.
func (u *ImageHistoryUpsertOne) SetWidth(v int) *ImageHistoryUpsertOne {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.SetWidth(v)
	})
}

// AddWidth adds v to the "width" field.
func (u *ImageHistoryUpsertOne) AddWidth(v int) *ImageHistoryUpsertOne {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.AddWidth(v)
	})
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *ImageHistoryUpsertOne) UpdateWidth() *ImageHistoryUpsertOne {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.UpdateWidth()
	})
}

// SetHeight sets the "height" field.
func (u *ImageHistoryUpsertOne) SetHeight(v int) *ImageHistoryUpsertOne {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.SetHeight(v)
	})
}

// AddHeight adds v to the "height" field.
func (u *ImageHistoryUpsertOne) AddHeight(v int) *ImageHistoryUpsertOne {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.AddHeight(v)
	})
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *ImageHistoryUpsertOne) UpdateHeight() *ImageHistoryUpsertOne {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.UpdateHeight()
	})
}

// SetSha256 sets the "sha256" field.
func (u *ImageHistoryUpsertOne) SetSha256(v string) *ImageHistoryUpsertOne {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.SetSha256(v)
	})
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *ImageHistoryUpsertOne) UpdateSha256() *ImageHistoryUpsertOne {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.UpdateSha256()
	})
}

// Exec executes the query.
func (u *ImageHistoryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ImageHistoryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ImageHistoryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ImageHistoryUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ImageHistoryUpsertOne.ID is not supported by MySQL driver. Use ImageHistoryUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ImageHistoryUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ImageHistoryCreateBulk is the builder for creating many ImageHistory entities in bulk.
type ImageHistoryCreateBulk struct {
	config
	err      error
	builders []*ImageHistoryCreate
	conflict []sql.ConflictOption
}

// Save creates the ImageHistory entities in the database.
func (_c *ImageHistoryCreateBulk) Save(ctx context.Context) ([]*ImageHistory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ImageHistory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ImageHistoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ImageHistoryCreateBulk) SaveX(ctx context.Context) []*ImageHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImageHistoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImageHistoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ImageHistory.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ImageHistoryUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *ImageHistoryCreateBulk) OnConflict(opts ...sql.ConflictOption) *ImageHistoryUpsertBulk {
	_c.conflict = opts
	return &ImageHistoryUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ImageHistory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ImageHistoryCreateBulk) OnConflictColumns(columns ...string) *ImageHistoryUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ImageHistoryUpsertBulk{
		create: _c,
	}
}

// ImageHistoryUpsertBulk is the builder for "upsert"-ing
// a bulk of ImageHistory nodes.
type ImageHistoryUpsertBulk struct {
	create *ImageHistoryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ImageHistory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(imagehistory.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ImageHistoryUpsertBulk) UpdateNewValues() *ImageHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(imagehistory.FieldID)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(imagehistory.FieldUserID)
			}
			if _, exists := b.mutation.APIKeyID(); exists {
				s.SetIgnore(imagehistory.FieldAPIKeyID)
			}
			if _, exists := b.mutation.ObjectKey(); exists {
				s.SetIgnore(imagehistory.FieldObjectKey)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(imagehistory.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ImageHistory.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ImageHistoryUpsertBulk) Ignore() *ImageHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ImageHistoryUpsertBulk) DoNothing() *ImageHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ImageHistoryCreateBulk.OnConflict
// documentation for more info.
func (u *ImageHistoryUpsertBulk) Update(set func(*ImageHistoryUpsert)) *ImageHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ImageHistoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *ImageHistoryUpsertBulk) SetRequestID(v string) *ImageHistoryUpsertBulk {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *ImageHistoryUpsertBulk) UpdateRequestID() *ImageHistoryUpsertBulk {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.UpdateRequestID()
	})
}

// SetSource sets the "source" field.
func (u *ImageHistoryUpsertBulk) SetSource(v string) *ImageHistoryUpsertBulk {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *ImageHistoryUpsertBulk) UpdateSource() *ImageHistoryUpsertBulk {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.UpdateSource()
	})
}

// SetEndpoint sets the "endpoint" field.
func (u *ImageHistoryUpsertBulk) SetEndpoint(v string) *ImageHistoryUpsertBulk {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.SetEndpoint(v)
	})
}

// UpdateEndpoint sets the "endpoint" field to the value that was provided on create.
func (u *ImageHistoryUpsertBulk) UpdateEndpoint() *ImageHistoryUpsertBulk {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.UpdateEndpoint()
	})
}

// SetModel sets the "model" field.
func (u *ImageHistoryUpsertBulk) SetModel(v string) *ImageHistoryUpsertBulk {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ImageHistoryUpsertBulk) UpdateModel() *ImageHistoryUpsertBulk {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.UpdateModel()
	})
}

// SetPrompt sets the "prompt" field.
func (u *ImageHistoryUpsertBulk) SetPrompt(v string) *ImageHistoryUpsertBulk {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.SetPrompt(v)
	})
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *ImageHistoryUpsertBulk) UpdatePrompt() *ImageHistoryUpsertBulk {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.UpdatePrompt()
	})
}

// SetRevisedPrompt sets the "revised_prompt" field.
func (u *ImageHistoryUpsertBulk) SetRevisedPrompt(v string) *ImageHistoryUpsertBulk {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.SetRevisedPrompt(v)
	})
}

// UpdateRevisedPrompt sets the "revised_prompt" field to the value that was provided on create.
func (u *ImageHistoryUpsertBulk) UpdateRevisedPrompt() *ImageHistoryUpsertBulk {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.UpdateRevisedPrompt()
	})
}

// SetMimeType sets the "mime_type" field.
func (u *ImageHistoryUpsertBulk) SetMimeType(v string) *ImageHistoryUpsertBulk {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.SetMimeType(v)
	})
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *ImageHistoryUpsertBulk) UpdateMimeType() *ImageHistoryUpsertBulk {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.UpdateMimeType()
	})
}

// SetSizeBytes sets the "size_bytes" field.
func (u *ImageHistoryUpsertBulk) SetSizeBytes(v int64) *ImageHistoryUpsertBulk {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.SetSizeBytes(v)
	})
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *ImageHistoryUpsertBulk) AddSizeBytes(v int64) *ImageHistoryUpsertBulk {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.AddSizeBytes(v)
	})
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *ImageHistoryUpsertBulk) UpdateSizeBytes() *ImageHistoryUpsertBulk {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.UpdateSizeBytes()
	})
}

// SetWidth sets the "width" field.
func (u *ImageHistoryUpsertBulk) SetWidth(v int) *ImageHistoryUpsertBulk {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.SetWidth(v)
	})
}

// AddWidth adds v to the "width" field.
func (u *ImageHistoryUpsertBulk) AddWidth(v int) *ImageHistoryUpsertBulk {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.AddWidth(v)
	})
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *ImageHistoryUpsertBulk) UpdateWidth() *ImageHistoryUpsertBulk {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.UpdateWidth()
	})
}

// SetHeight sets the "height" field.
func (u *ImageHistoryUpsertBulk) SetHeight(v int) *ImageHistoryUpsertBulk {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.SetHeight(v)
	})
}

// AddHeight adds v to the "height" field.
func (u *ImageHistoryUpsertBulk) AddHeight(v int) *ImageHistoryUpsertBulk {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.AddHeight(v)
	})
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *ImageHistoryUpsertBulk) UpdateHeight() *ImageHistoryUpsertBulk {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.UpdateHeight()
	})
}

// SetSha256 sets the "sha256" field.
func (u *ImageHistoryUpsertBulk) SetSha256(v string) *ImageHistoryUpsertBulk {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.SetSha256(v)
	})
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *ImageHistoryUpsertBulk) UpdateSha256() *ImageHistoryUpsertBulk {
	return u.Update(func(s *ImageHistoryUpsert) {
		s.UpdateSha256()
	})
}

// Exec executes the query.
func (u *ImageHistoryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ImageHistoryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ImageHistoryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ImageHistoryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
