// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/BrandonVee/TokenRouter/ent/invoicedelivery"
)

// InvoiceDelivery is the model entity for the InvoiceDelivery schema.
type InvoiceDelivery struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// InvoiceRequestID holds the value of the "invoice_request_id" field.
	InvoiceRequestID int64 `json:"invoice_request_id,omitempty"`
	// RecipientEmail holds the value of the "recipient_email" field.
	RecipientEmail string `json:"recipient_email,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// MessageID holds the value of the "message_id" field.
	MessageID *string `json:"message_id,omitempty"`
	// AttachmentSummary holds the value of the "attachment_summary" field.
	AttachmentSummary *string `json:"attachment_summary,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// SentBy holds the value of the "sent_by" field.
	SentBy *int64 `json:"sent_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InvoiceDelivery) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case invoicedelivery.FieldID, invoicedelivery.FieldInvoiceRequestID, invoicedelivery.FieldSentBy:
			values[i] = new(sql.NullInt64)
		case invoicedelivery.FieldRecipientEmail, invoicedelivery.FieldStatus, invoicedelivery.FieldMessageID, invoicedelivery.FieldAttachmentSummary, invoicedelivery.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case invoicedelivery.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InvoiceDelivery fields.
func (_m *InvoiceDelivery) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case invoicedelivery.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case invoicedelivery.FieldInvoiceRequestID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_request_id", values[i])
			} else if value.Valid {
				_m.InvoiceRequestID = value.Int64
			}
		case invoicedelivery.FieldRecipientEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field recipient_email", values[i])
			} else if value.Valid {
				_m.RecipientEmail = value.String
			}
		case invoicedelivery.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case invoicedelivery.FieldMessageID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message_id", values[i])
			} else if value.Valid {
				_m.MessageID = new(string)
				*_m.MessageID = value.String
			}
		case invoicedelivery.FieldAttachmentSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field attachment_summary", values[i])
			} else if value.Valid {
				_m.AttachmentSummary = new(string)
				*_m.AttachmentSummary = value.String
			}
		case invoicedelivery.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case invoicedelivery.FieldSentBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sent_by", values[i])
			} else if value.Valid {
				_m.SentBy = new(int64)
				*_m.SentBy = value.Int64
			}
		case invoicedelivery.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InvoiceDelivery.
// This includes values selected through modifiers, order, etc.
func (_m *InvoiceDelivery) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this InvoiceDelivery.
// Note that you need to call InvoiceDelivery.Unwrap() before calling this method if this InvoiceDelivery
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InvoiceDelivery) Update() *InvoiceDeliveryUpdateOne {
	return NewInvoiceDeliveryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InvoiceDelivery entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InvoiceDelivery) Unwrap() *InvoiceDelivery {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InvoiceDelivery is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InvoiceDelivery) String() string {
	var builder strings.Builder
	builder.WriteString("InvoiceDelivery(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("invoice_request_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InvoiceRequestID))
	builder.WriteString(", ")
	builder.WriteString("recipient_email=")
	builder.WriteString(_m.RecipientEmail)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.MessageID; v != nil {
		builder.WriteString("message_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AttachmentSummary; v != nil {
		builder.WriteString("attachment_summary=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SentBy; v != nil {
		builder.WriteString("sent_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// InvoiceDeliveries is a parsable slice of InvoiceDelivery.
type InvoiceDeliveries []*InvoiceDelivery
