// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/BrandonVee/TokenRouter/ent/invoicedelivery"
	"github.com/BrandonVee/TokenRouter/ent/predicate"
)

// InvoiceDeliveryDelete is the builder for deleting a InvoiceDelivery entity.
type InvoiceDeliveryDelete struct {
	config
	hooks    []Hook
	mutation *InvoiceDeliveryMutation
}

// Where appends a list predicates to the InvoiceDeliveryDelete builder.
func (_d *InvoiceDeliveryDelete) Where(ps ...predicate.InvoiceDelivery) *InvoiceDeliveryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *InvoiceDeliveryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *InvoiceDeliveryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *InvoiceDeliveryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(invoicedelivery.Table, sqlgraph.NewFieldSpec(invoicedelivery.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// InvoiceDeliveryDeleteOne is the builder for deleting a single InvoiceDelivery entity.
type InvoiceDeliveryDeleteOne struct {
	_d *InvoiceDeliveryDelete
}

// Where appends a list predicates to the InvoiceDeliveryDelete builder.
func (_d *InvoiceDeliveryDeleteOne) Where(ps ...predicate.InvoiceDelivery) *InvoiceDeliveryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *InvoiceDeliveryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{invoicedelivery.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *InvoiceDeliveryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
