// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/BrandonVee/TokenRouter/ent/invoiceattachment"
)

// InvoiceAttachment is the model entity for the InvoiceAttachment schema.
type InvoiceAttachment struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// InvoiceRequestID holds the value of the "invoice_request_id" field.
	InvoiceRequestID int64 `json:"invoice_request_id,omitempty"`
	// FileName holds the value of the "file_name" field.
	FileName string `json:"file_name,omitempty"`
	// ContentType holds the value of the "content_type" field.
	ContentType string `json:"content_type,omitempty"`
	// SizeBytes holds the value of the "size_bytes" field.
	SizeBytes int64 `json:"size_bytes,omitempty"`
	// StorageKey holds the value of the "storage_key" field.
	StorageKey string `json:"storage_key,omitempty"`
	// StorageType holds the value of the "storage_type" field.
	StorageType string `json:"storage_type,omitempty"`
	// StorageProfileID holds the value of the "storage_profile_id" field.
	StorageProfileID string `json:"storage_profile_id,omitempty"`
	// Sha256 holds the value of the "sha256" field.
	Sha256 string `json:"sha256,omitempty"`
	// UploadedBy holds the value of the "uploaded_by" field.
	UploadedBy int64 `json:"uploaded_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InvoiceAttachment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case invoiceattachment.FieldID, invoiceattachment.FieldInvoiceRequestID, invoiceattachment.FieldSizeBytes, invoiceattachment.FieldUploadedBy:
			values[i] = new(sql.NullInt64)
		case invoiceattachment.FieldFileName, invoiceattachment.FieldContentType, invoiceattachment.FieldStorageKey, invoiceattachment.FieldStorageType, invoiceattachment.FieldStorageProfileID, invoiceattachment.FieldSha256:
			values[i] = new(sql.NullString)
		case invoiceattachment.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InvoiceAttachment fields.
func (_m *InvoiceAttachment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case invoiceattachment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case invoiceattachment.FieldInvoiceRequestID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_request_id", values[i])
			} else if value.Valid {
				_m.InvoiceRequestID = value.Int64
			}
		case invoiceattachment.FieldFileName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_name", values[i])
			} else if value.Valid {
				_m.FileName = value.String
			}
		case invoiceattachment.FieldContentType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_type", values[i])
			} else if value.Valid {
				_m.ContentType = value.String
			}
		case invoiceattachment.FieldSizeBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size_bytes", values[i])
			} else if value.Valid {
				_m.SizeBytes = value.Int64
			}
		case invoiceattachment.FieldStorageKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field storage_key", values[i])
			} else if value.Valid {
				_m.StorageKey = value.String
			}
		case invoiceattachment.FieldStorageType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field storage_type", values[i])
			} else if value.Valid {
				_m.StorageType = value.String
			}
		case invoiceattachment.FieldStorageProfileID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field storage_profile_id", values[i])
			} else if value.Valid {
				_m.StorageProfileID = value.String
			}
		case invoiceattachment.FieldSha256:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sha256", values[i])
			} else if value.Valid {
				_m.Sha256 = value.String
			}
		case invoiceattachment.FieldUploadedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field uploaded_by", values[i])
			} else if value.Valid {
				_m.UploadedBy = value.Int64
			}
		case invoiceattachment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InvoiceAttachment.
// This includes values selected through modifiers, order, etc.
func (_m *InvoiceAttachment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this InvoiceAttachment.
// Note that you need to call InvoiceAttachment.Unwrap() before calling this method if this InvoiceAttachment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InvoiceAttachment) Update() *InvoiceAttachmentUpdateOne {
	return NewInvoiceAttachmentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InvoiceAttachment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InvoiceAttachment) Unwrap() *InvoiceAttachment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InvoiceAttachment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InvoiceAttachment) String() string {
	var builder strings.Builder
	builder.WriteString("InvoiceAttachment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("invoice_request_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InvoiceRequestID))
	builder.WriteString(", ")
	builder.WriteString("file_name=")
	builder.WriteString(_m.FileName)
	builder.WriteString(", ")
	builder.WriteString("content_type=")
	builder.WriteString(_m.ContentType)
	builder.WriteString(", ")
	builder.WriteString("size_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.SizeBytes))
	builder.WriteString(", ")
	builder.WriteString("storage_key=")
	builder.WriteString(_m.StorageKey)
	builder.WriteString(", ")
	builder.WriteString("storage_type=")
	builder.WriteString(_m.StorageType)
	builder.WriteString(", ")
	builder.WriteString("storage_profile_id=")
	builder.WriteString(_m.StorageProfileID)
	builder.WriteString(", ")
	builder.WriteString("sha256=")
	builder.WriteString(_m.Sha256)
	builder.WriteString(", ")
	builder.WriteString("uploaded_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.UploadedBy))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// InvoiceAttachments is a parsable slice of InvoiceAttachment.
type InvoiceAttachments []*InvoiceAttachment
