// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/BrandonVee/TokenRouter/ent/invoicerequest"
)

// InvoiceRequestCreate is the builder for creating a InvoiceRequest entity.
type InvoiceRequestCreate struct {
	config
	mutation *InvoiceRequestMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *InvoiceRequestCreate) SetUserID(v int64) *InvoiceRequestCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRequestNo sets the "request_no" field.
func (_c *InvoiceRequestCreate) SetRequestNo(v string) *InvoiceRequestCreate {
	_c.mutation.SetRequestNo(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *InvoiceRequestCreate) SetStatus(v string) *InvoiceRequestCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableStatus(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *InvoiceRequestCreate) SetCurrency(v string) *InvoiceRequestCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetTotalAmount sets the "total_amount" field.
func (_c *InvoiceRequestCreate) SetTotalAmount(v float64) *InvoiceRequestCreate {
	_c.mutation.SetTotalAmount(v)
	return _c
}

// SetInvoiceType sets the "invoice_type" field.
func (_c *InvoiceRequestCreate) SetInvoiceType(v string) *InvoiceRequestCreate {
	_c.mutation.SetInvoiceType(v)
	return _c
}

// SetNillableInvoiceType sets the "invoice_type" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableInvoiceType(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetInvoiceType(*v)
	}
	return _c
}

// SetInvoiceTitle sets the "invoice_title" field.
func (_c *InvoiceRequestCreate) SetInvoiceTitle(v string) *InvoiceRequestCreate {
	_c.mutation.SetInvoiceTitle(v)
	return _c
}

// SetTaxID sets the "tax_id" field.
func (_c *InvoiceRequestCreate) SetTaxID(v string) *InvoiceRequestCreate {
	_c.mutation.SetTaxID(v)
	return _c
}

// SetNillableTaxID sets the "tax_id" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableTaxID(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetTaxID(*v)
	}
	return _c
}

// SetBankName sets the "bank_name" field.
func (_c *InvoiceRequestCreate) SetBankName(v string) *InvoiceRequestCreate {
	_c.mutation.SetBankName(v)
	return _c
}

// SetNillableBankName sets the "bank_name" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableBankName(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetBankName(*v)
	}
	return _c
}

// SetBankAccount sets the "bank_account" field.
func (_c *InvoiceRequestCreate) SetBankAccount(v string) *InvoiceRequestCreate {
	_c.mutation.SetBankAccount(v)
	return _c
}

// SetNillableBankAccount sets the "bank_account" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableBankAccount(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetBankAccount(*v)
	}
	return _c
}

// SetRecipientEmail sets the "recipient_email" field.
func (_c *InvoiceRequestCreate) SetRecipientEmail(v string) *InvoiceRequestCreate {
	_c.mutation.SetRecipientEmail(v)
	return _c
}

// SetAccountEmail sets the "account_email" field.
func (_c *InvoiceRequestCreate) SetAccountEmail(v string) *InvoiceRequestCreate {
	_c.mutation.SetAccountEmail(v)
	return _c
}

// SetRemark sets the "remark" field.
func (_c *InvoiceRequestCreate) SetRemark(v string) *InvoiceRequestCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableRemark(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetRejectionReason sets the "rejection_reason" field.
func (_c *InvoiceRequestCreate) SetRejectionReason(v string) *InvoiceRequestCreate {
	_c.mutation.SetRejectionReason(v)
	return _c
}

// SetNillableRejectionReason sets the "rejection_reason" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableRejectionReason(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetRejectionReason(*v)
	}
	return _c
}

// SetReviewedBy sets the "reviewed_by" field.
func (_c *InvoiceRequestCreate) SetReviewedBy(v int64) *InvoiceRequestCreate {
	_c.mutation.SetReviewedBy(v)
	return _c
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableReviewedBy(v *int64) *InvoiceRequestCreate {
	if v != nil {
		_c.SetReviewedBy(*v)
	}
	return _c
}

// SetReviewedAt sets the "reviewed_at" field.
func (_c *InvoiceRequestCreate) SetReviewedAt(v time.Time) *InvoiceRequestCreate {
	_c.mutation.SetReviewedAt(v)
	return _c
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableReviewedAt(v *time.Time) *InvoiceRequestCreate {
	if v != nil {
		_c.SetReviewedAt(*v)
	}
	return _c
}

// SetInvoiceNumber sets the "invoice_number" field.
func (_c *InvoiceRequestCreate) SetInvoiceNumber(v string) *InvoiceRequestCreate {
	_c.mutation.SetInvoiceNumber(v)
	return _c
}

// SetNillableInvoiceNumber sets the "invoice_number" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableInvoiceNumber(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetInvoiceNumber(*v)
	}
	return _c
}

// SetIssuedAt sets the "issued_at" field.
func (_c *InvoiceRequestCreate) SetIssuedAt(v time.Time) *InvoiceRequestCreate {
	_c.mutation.SetIssuedAt(v)
	return _c
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableIssuedAt(v *time.Time) *InvoiceRequestCreate {
	if v != nil {
		_c.SetIssuedAt(*v)
	}
	return _c
}

// SetIssueRemark sets the "issue_remark" field.
func (_c *InvoiceRequestCreate) SetIssueRemark(v string) *InvoiceRequestCreate {
	_c.mutation.SetIssueRemark(v)
	return _c
}

// SetNillableIssueRemark sets the "issue_remark" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableIssueRemark(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetIssueRemark(*v)
	}
	return _c
}

// SetSentAt sets the "sent_at" field.
func (_c *InvoiceRequestCreate) SetSentAt(v time.Time) *InvoiceRequestCreate {
	_c.mutation.SetSentAt(v)
	return _c
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableSentAt(v *time.Time) *InvoiceRequestCreate {
	if v != nil {
		_c.SetSentAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InvoiceRequestCreate) SetCreatedAt(v time.Time) *InvoiceRequestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableCreatedAt(v *time.Time) *InvoiceRequestCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InvoiceRequestCreate) SetUpdatedAt(v time.Time) *InvoiceRequestCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableUpdatedAt(v *time.Time) *InvoiceRequestCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the InvoiceRequestMutation object of the builder.
func (_c *InvoiceRequestCreate) Mutation() *InvoiceRequestMutation {
	return _c.mutation
}

// Save creates the InvoiceRequest in the database.
func (_c *InvoiceRequestCreate) Save(ctx context.Context) (*InvoiceRequest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InvoiceRequestCreate) SaveX(ctx context.Context) *InvoiceRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceRequestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceRequestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InvoiceRequestCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := invoicerequest.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.InvoiceType(); !ok {
		v := invoicerequest.DefaultInvoiceType
		_c.mutation.SetInvoiceType(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := invoicerequest.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := invoicerequest.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InvoiceRequestCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "InvoiceRequest.user_id"`)}
	}
	if _, ok := _c.mutation.RequestNo(); !ok {
		return &ValidationError{Name: "request_no", err: errors.New(`ent: missing required field "InvoiceRequest.request_no"`)}
	}
	if v, ok := _c.mutation.RequestNo(); ok {
		if err := invoicerequest.RequestNoValidator(v); err != nil {
			return &ValidationError{Name: "request_no", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.request_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "InvoiceRequest.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := invoicerequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "InvoiceRequest.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := invoicerequest.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TotalAmount(); !ok {
		return &ValidationError{Name: "total_amount", err: errors.New(`ent: missing required field "InvoiceRequest.total_amount"`)}
	}
	if _, ok := _c.mutation.InvoiceType(); !ok {
		return &ValidationError{Name: "invoice_type", err: errors.New(`ent: missing required field "InvoiceRequest.invoice_type"`)}
	}
	if v, ok := _c.mutation.InvoiceType(); ok {
		if err := invoicerequest.InvoiceTypeValidator(v); err != nil {
			return &ValidationError{Name: "invoice_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.invoice_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InvoiceTitle(); !ok {
		return &ValidationError{Name: "invoice_title", err: errors.New(`ent: missing required field "InvoiceRequest.invoice_title"`)}
	}
	if v, ok := _c.mutation.InvoiceTitle(); ok {
		if err := invoicerequest.InvoiceTitleValidator(v); err != nil {
			return &ValidationError{Name: "invoice_title", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.invoice_title": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TaxID(); ok {
		if err := invoicerequest.TaxIDValidator(v); err != nil {
			return &ValidationError{Name: "tax_id", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.tax_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.BankName(); ok {
		if err := invoicerequest.BankNameValidator(v); err != nil {
			return &ValidationError{Name: "bank_name", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.bank_name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.BankAccount(); ok {
		if err := invoicerequest.BankAccountValidator(v); err != nil {
			return &ValidationError{Name: "bank_account", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.bank_account": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RecipientEmail(); !ok {
		return &ValidationError{Name: "recipient_email", err: errors.New(`ent: missing required field "InvoiceRequest.recipient_email"`)}
	}
	if v, ok := _c.mutation.RecipientEmail(); ok {
		if err := invoicerequest.RecipientEmailValidator(v); err != nil {
			return &ValidationError{Name: "recipient_email", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.recipient_email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccountEmail(); !ok {
		return &ValidationError{Name: "account_email", err: errors.New(`ent: missing required field "InvoiceRequest.account_email"`)}
	}
	if v, ok := _c.mutation.AccountEmail(); ok {
		if err := invoicerequest.AccountEmailValidator(v); err != nil {
			return &ValidationError{Name: "account_email", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.account_email": %w`, err)}
		}
	}
	if v, ok := _c.mutation.InvoiceNumber(); ok {
		if err := invoicerequest.InvoiceNumberValidator(v); err != nil {
			return &ValidationError{Name: "invoice_number", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.invoice_number": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InvoiceRequest.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "InvoiceRequest.updated_at"`)}
	}
	return nil
}

func (_c *InvoiceRequestCreate) sqlSave(ctx context.Context) (*InvoiceRequest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InvoiceRequestCreate) createSpec() (*InvoiceRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &InvoiceRequest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invoicerequest.Table, sqlgraph.NewFieldSpec(invoicerequest.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(invoicerequest.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.RequestNo(); ok {
		_spec.SetField(invoicerequest.FieldRequestNo, field.TypeString, value)
		_node.RequestNo = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(invoicerequest.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(invoicerequest.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.TotalAmount(); ok {
		_spec.SetField(invoicerequest.FieldTotalAmount, field.TypeFloat64, value)
		_node.TotalAmount = value
	}
	if value, ok := _c.mutation.InvoiceType(); ok {
		_spec.SetField(invoicerequest.FieldInvoiceType, field.TypeString, value)
		_node.InvoiceType = value
	}
	if value, ok := _c.mutation.InvoiceTitle(); ok {
		_spec.SetField(invoicerequest.FieldInvoiceTitle, field.TypeString, value)
		_node.InvoiceTitle = value
	}
	if value, ok := _c.mutation.TaxID(); ok {
		_spec.SetField(invoicerequest.FieldTaxID, field.TypeString, value)
		_node.TaxID = &value
	}
	if value, ok := _c.mutation.BankName(); ok {
		_spec.SetField(invoicerequest.FieldBankName, field.TypeString, value)
		_node.BankName = &value
	}
	if value, ok := _c.mutation.BankAccount(); ok {
		_spec.SetField(invoicerequest.FieldBankAccount, field.TypeString, value)
		_node.BankAccount = &value
	}
	if value, ok := _c.mutation.RecipientEmail(); ok {
		_spec.SetField(invoicerequest.FieldRecipientEmail, field.TypeString, value)
		_node.RecipientEmail = value
	}
	if value, ok := _c.mutation.AccountEmail(); ok {
		_spec.SetField(invoicerequest.FieldAccountEmail, field.TypeString, value)
		_node.AccountEmail = value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(invoicerequest.FieldRemark, field.TypeString, value)
		_node.Remark = &value
	}
	if value, ok := _c.mutation.RejectionReason(); ok {
		_spec.SetField(invoicerequest.FieldRejectionReason, field.TypeString, value)
		_node.RejectionReason = &value
	}
	if value, ok := _c.mutation.ReviewedBy(); ok {
		_spec.SetField(invoicerequest.FieldReviewedBy, field.TypeInt64, value)
		_node.ReviewedBy = &value
	}
	if value, ok := _c.mutation.ReviewedAt(); ok {
		_spec.SetField(invoicerequest.FieldReviewedAt, field.TypeTime, value)
		_node.ReviewedAt = &value
	}
	if value, ok := _c.mutation.InvoiceNumber(); ok {
		_spec.SetField(invoicerequest.FieldInvoiceNumber, field.TypeString, value)
		_node.InvoiceNumber = &value
	}
	if value, ok := _c.mutation.IssuedAt(); ok {
		_spec.SetField(invoicerequest.FieldIssuedAt, field.TypeTime, value)
		_node.IssuedAt = &value
	}
	if value, ok := _c.mutation.IssueRemark(); ok {
		_spec.SetField(invoicerequest.FieldIssueRemark, field.TypeString, value)
		_node.IssueRemark = &value
	}
	if value, ok := _c.mutation.SentAt(); ok {
		_spec.SetField(invoicerequest.FieldSentAt, field.TypeTime, value)
		_node.SentAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(invoicerequest.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(invoicerequest.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceRequest.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceRequestUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceRequestCreate) OnConflict(opts ...sql.ConflictOption) *InvoiceRequestUpsertOne {
	_c.conflict = opts
	return &InvoiceRequestUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceRequestCreate) OnConflictColumns(columns ...string) *InvoiceRequestUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceRequestUpsertOne{
		create: _c,
	}
}

type (
	// InvoiceRequestUpsertOne is the builder for "upsert"-ing
	//  one InvoiceRequest node.
	InvoiceRequestUpsertOne struct {
		create *InvoiceRequestCreate
	}

	// InvoiceRequestUpsert is the "OnConflict" setter.
	InvoiceRequestUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *InvoiceRequestUpsert) SetUserID(v int64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateUserID() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *InvoiceRequestUpsert) AddUserID(v int64) *InvoiceRequestUpsert {
	u.Add(invoicerequest.FieldUserID, v)
	return u
}

// SetRequestNo sets the "request_no" field.
func (u *InvoiceRequestUpsert) SetRequestNo(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldRequestNo, v)
	return u
}

// UpdateRequestNo sets the "request_no" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateRequestNo() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldRequestNo)
	return u
}

// SetStatus sets the "status" field.
func (u *InvoiceRequestUpsert) SetStatus(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateStatus() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldStatus)
	return u
}

// SetCurrency sets the "currency" field.
func (u *InvoiceRequestUpsert) SetCurrency(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateCurrency() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldCurrency)
	return u
}

// SetTotalAmount sets the "total_amount" field.
func (u *InvoiceRequestUpsert) SetTotalAmount(v float64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldTotalAmount, v)
	return u
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateTotalAmount() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldTotalAmount)
	return u
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *InvoiceRequestUpsert) AddTotalAmount(v float64) *InvoiceRequestUpsert {
	u.Add(invoicerequest.FieldTotalAmount, v)
	return u
}

// SetInvoiceType sets the "invoice_type" field.
func (u *InvoiceRequestUpsert) SetInvoiceType(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldInvoiceType, v)
	return u
}

// UpdateInvoiceType sets the "invoice_type" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateInvoiceType() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldInvoiceType)
	return u
}

// SetInvoiceTitle sets the "invoice_title" field.
func (u *InvoiceRequestUpsert) SetInvoiceTitle(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldInvoiceTitle, v)
	return u
}

// UpdateInvoiceTitle sets the "invoice_title" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateInvoiceTitle() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldInvoiceTitle)
	return u
}

// SetTaxID sets the "tax_id" field.
func (u *InvoiceRequestUpsert) SetTaxID(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldTaxID, v)
	return u
}

// UpdateTaxID sets the "tax_id" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateTaxID() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldTaxID)
	return u
}

// ClearTaxID clears the value of the "tax_id" field.
func (u *InvoiceRequestUpsert) ClearTaxID() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldTaxID)
	return u
}

// SetBankName sets the "bank_name" field.
func (u *InvoiceRequestUpsert) SetBankName(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldBankName, v)
	return u
}

// UpdateBankName sets the "bank_name" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateBankName() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldBankName)
	return u
}

// ClearBankName clears the value of the "bank_name" field.
func (u *InvoiceRequestUpsert) ClearBankName() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldBankName)
	return u
}

// SetBankAccount sets the "bank_account" field.
func (u *InvoiceRequestUpsert) SetBankAccount(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldBankAccount, v)
	return u
}

// UpdateBankAccount sets the "bank_account" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateBankAccount() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldBankAccount)
	return u
}

// ClearBankAccount clears the value of the "bank_account" field.
func (u *InvoiceRequestUpsert) ClearBankAccount() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldBankAccount)
	return u
}

// SetRecipientEmail sets the "recipient_email" field.
func (u *InvoiceRequestUpsert) SetRecipientEmail(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldRecipientEmail, v)
	return u
}

// UpdateRecipientEmail sets the "recipient_email" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateRecipientEmail() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldRecipientEmail)
	return u
}

// SetAccountEmail sets the "account_email" field.
func (u *InvoiceRequestUpsert) SetAccountEmail(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldAccountEmail, v)
	return u
}

// UpdateAccountEmail sets the "account_email" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateAccountEmail() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldAccountEmail)
	return u
}

// SetRemark sets the "remark" field.
func (u *InvoiceRequestUpsert) SetRemark(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldRemark, v)
	return u
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateRemark() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldRemark)
	return u
}

// ClearRemark clears the value of the "remark" field.
func (u *InvoiceRequestUpsert) ClearRemark() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldRemark)
	return u
}

// SetRejectionReason sets the "rejection_reason" field.
func (u *InvoiceRequestUpsert) SetRejectionReason(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldRejectionReason, v)
	return u
}

// UpdateRejectionReason sets the "rejection_reason" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateRejectionReason() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldRejectionReason)
	return u
}

// ClearRejectionReason clears the value of the "rejection_reason" field.
func (u *InvoiceRequestUpsert) ClearRejectionReason() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldRejectionReason)
	return u
}

// SetReviewedBy sets the "reviewed_by" field.
func (u *InvoiceRequestUpsert) SetReviewedBy(v int64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldReviewedBy, v)
	return u
}

// UpdateReviewedBy sets the "reviewed_by" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateReviewedBy() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldReviewedBy)
	return u
}

// AddReviewedBy adds v to the "reviewed_by" field.
func (u *InvoiceRequestUpsert) AddReviewedBy(v int64) *InvoiceRequestUpsert {
	u.Add(invoicerequest.FieldReviewedBy, v)
	return u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (u *InvoiceRequestUpsert) ClearReviewedBy() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldReviewedBy)
	return u
}

// SetReviewedAt sets the "reviewed_at" field.
func (u *InvoiceRequestUpsert) SetReviewedAt(v time.Time) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldReviewedAt, v)
	return u
}

// UpdateReviewedAt sets the "reviewed_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateReviewedAt() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldReviewedAt)
	return u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (u *InvoiceRequestUpsert) ClearReviewedAt() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldReviewedAt)
	return u
}

// SetInvoiceNumber sets the "invoice_number" field.
func (u *InvoiceRequestUpsert) SetInvoiceNumber(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldInvoiceNumber, v)
	return u
}

// UpdateInvoiceNumber sets the "invoice_number" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateInvoiceNumber() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldInvoiceNumber)
	return u
}

// ClearInvoiceNumber clears the value of the "invoice_number" field.
func (u *InvoiceRequestUpsert) ClearInvoiceNumber() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldInvoiceNumber)
	return u
}

// SetIssuedAt sets the "issued_at" field.
func (u *InvoiceRequestUpsert) SetIssuedAt(v time.Time) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldIssuedAt, v)
	return u
}

// UpdateIssuedAt sets the "issued_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateIssuedAt() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldIssuedAt)
	return u
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (u *InvoiceRequestUpsert) ClearIssuedAt() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldIssuedAt)
	return u
}

// SetIssueRemark sets the "issue_remark" field.
func (u *InvoiceRequestUpsert) SetIssueRemark(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldIssueRemark, v)
	return u
}

// UpdateIssueRemark sets the "issue_remark" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateIssueRemark() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldIssueRemark)
	return u
}

// ClearIssueRemark clears the value of the "issue_remark" field.
func (u *InvoiceRequestUpsert) ClearIssueRemark() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldIssueRemark)
	return u
}

// SetSentAt sets the "sent_at" field.
func (u *InvoiceRequestUpsert) SetSentAt(v time.Time) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldSentAt, v)
	return u
}

// UpdateSentAt sets the "sent_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateSentAt() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldSentAt)
	return u
}

// ClearSentAt clears the value of the "sent_at" field.
func (u *InvoiceRequestUpsert) ClearSentAt() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldSentAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceRequestUpsert) SetUpdatedAt(v time.Time) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateUpdatedAt() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceRequestUpsertOne) UpdateNewValues() *InvoiceRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(invoicerequest.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InvoiceRequestUpsertOne) Ignore() *InvoiceRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceRequestUpsertOne) DoNothing() *InvoiceRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceRequestCreate.OnConflict
// documentation for more info.
func (u *InvoiceRequestUpsertOne) Update(set func(*InvoiceRequestUpsert)) *InvoiceRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *InvoiceRequestUpsertOne) SetUserID(v int64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *InvoiceRequestUpsertOne) AddUserID(v int64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateUserID() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateUserID()
	})
}

// SetRequestNo sets the "request_no" field.
func (u *InvoiceRequestUpsertOne) SetRequestNo(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetRequestNo(v)
	})
}

// UpdateRequestNo sets the "request_no" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateRequestNo() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateRequestNo()
	})
}

// SetStatus sets the "status" field.
func (u *InvoiceRequestUpsertOne) SetStatus(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateStatus() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateStatus()
	})
}

// SetCurrency sets the "currency" field.
func (u *InvoiceRequestUpsertOne) SetCurrency(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateCurrency() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateCurrency()
	})
}

// SetTotalAmount sets the "total_amount" field.
func (u *InvoiceRequestUpsertOne) SetTotalAmount(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetTotalAmount(v)
	})
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *InvoiceRequestUpsertOne) AddTotalAmount(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddTotalAmount(v)
	})
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateTotalAmount() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateTotalAmount()
	})
}

// SetInvoiceType sets the "invoice_type" field.
func (u *InvoiceRequestUpsertOne) SetInvoiceType(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetInvoiceType(v)
	})
}

// UpdateInvoiceType sets the "invoice_type" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateInvoiceType() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateInvoiceType()
	})
}

// SetInvoiceTitle sets the "invoice_title" field.
func (u *InvoiceRequestUpsertOne) SetInvoiceTitle(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetInvoiceTitle(v)
	})
}

// UpdateInvoiceTitle sets the "invoice_title" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateInvoiceTitle() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateInvoiceTitle()
	})
}

// SetTaxID sets the "tax_id" field.
func (u *InvoiceRequestUpsertOne) SetTaxID(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetTaxID(v)
	})
}

// UpdateTaxID sets the "tax_id" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateTaxID() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateTaxID()
	})
}

// ClearTaxID clears the value of the "tax_id" field.
func (u *InvoiceRequestUpsertOne) ClearTaxID() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearTaxID()
	})
}

// SetBankName sets the "bank_name" field.
func (u *InvoiceRequestUpsertOne) SetBankName(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetBankName(v)
	})
}

// UpdateBankName sets the "bank_name" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateBankName() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateBankName()
	})
}

// ClearBankName clears the value of the "bank_name" field.
func (u *InvoiceRequestUpsertOne) ClearBankName() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearBankName()
	})
}

// SetBankAccount sets the "bank_account" field.
func (u *InvoiceRequestUpsertOne) SetBankAccount(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetBankAccount(v)
	})
}

// UpdateBankAccount sets the "bank_account" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateBankAccount() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateBankAccount()
	})
}

// ClearBankAccount clears the value of the "bank_account" field.
func (u *InvoiceRequestUpsertOne) ClearBankAccount() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearBankAccount()
	})
}

// SetRecipientEmail sets the "recipient_email" field.
func (u *InvoiceRequestUpsertOne) SetRecipientEmail(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetRecipientEmail(v)
	})
}

// UpdateRecipientEmail sets the "recipient_email" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateRecipientEmail() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateRecipientEmail()
	})
}

// SetAccountEmail sets the "account_email" field.
func (u *InvoiceRequestUpsertOne) SetAccountEmail(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetAccountEmail(v)
	})
}

// UpdateAccountEmail sets the "account_email" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateAccountEmail() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateAccountEmail()
	})
}

// SetRemark sets the "remark" field.
func (u *InvoiceRequestUpsertOne) SetRemark(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateRemark() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *InvoiceRequestUpsertOne) ClearRemark() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearRemark()
	})
}

// SetRejectionReason sets the "rejection_reason" field.
func (u *InvoiceRequestUpsertOne) SetRejectionReason(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetRejectionReason(v)
	})
}

// UpdateRejectionReason sets the "rejection_reason" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateRejectionReason() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateRejectionReason()
	})
}

// ClearRejectionReason clears the value of the "rejection_reason" field.
func (u *InvoiceRequestUpsertOne) ClearRejectionReason() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearRejectionReason()
	})
}

// SetReviewedBy sets the "reviewed_by" field.
func (u *InvoiceRequestUpsertOne) SetReviewedBy(v int64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetReviewedBy(v)
	})
}

// AddReviewedBy adds v to the "reviewed_by" field.
func (u *InvoiceRequestUpsertOne) AddReviewedBy(v int64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddReviewedBy(v)
	})
}

// UpdateReviewedBy sets the "reviewed_by" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateReviewedBy() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateReviewedBy()
	})
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (u *InvoiceRequestUpsertOne) ClearReviewedBy() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearReviewedBy()
	})
}

// SetReviewedAt sets the "reviewed_at" field.
func (u *InvoiceRequestUpsertOne) SetReviewedAt(v time.Time) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetReviewedAt(v)
	})
}

// UpdateReviewedAt sets the "reviewed_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateReviewedAt() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateReviewedAt()
	})
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (u *InvoiceRequestUpsertOne) ClearReviewedAt() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearReviewedAt()
	})
}

// SetInvoiceNumber sets the "invoice_number" field.
func (u *InvoiceRequestUpsertOne) SetInvoiceNumber(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetInvoiceNumber(v)
	})
}

// UpdateInvoiceNumber sets the "invoice_number" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateInvoiceNumber() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateInvoiceNumber()
	})
}

// ClearInvoiceNumber clears the value of the "invoice_number" field.
func (u *InvoiceRequestUpsertOne) ClearInvoiceNumber() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearInvoiceNumber()
	})
}

// SetIssuedAt sets the "issued_at" field.
func (u *InvoiceRequestUpsertOne) SetIssuedAt(v time.Time) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetIssuedAt(v)
	})
}

// UpdateIssuedAt sets the "issued_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateIssuedAt() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateIssuedAt()
	})
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (u *InvoiceRequestUpsertOne) ClearIssuedAt() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearIssuedAt()
	})
}

// SetIssueRemark sets the "issue_remark" field.
func (u *InvoiceRequestUpsertOne) SetIssueRemark(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetIssueRemark(v)
	})
}

// UpdateIssueRemark sets the "issue_remark" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateIssueRemark() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateIssueRemark()
	})
}

// ClearIssueRemark clears the value of the "issue_remark" field.
func (u *InvoiceRequestUpsertOne) ClearIssueRemark() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearIssueRemark()
	})
}

// SetSentAt sets the "sent_at" field.
func (u *InvoiceRequestUpsertOne) SetSentAt(v time.Time) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetSentAt(v)
	})
}

// UpdateSentAt sets the "sent_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateSentAt() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateSentAt()
	})
}

// ClearSentAt clears the value of the "sent_at" field.
func (u *InvoiceRequestUpsertOne) ClearSentAt() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearSentAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceRequestUpsertOne) SetUpdatedAt(v time.Time) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateUpdatedAt() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *InvoiceRequestUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceRequestCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceRequestUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InvoiceRequestUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InvoiceRequestUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InvoiceRequestCreateBulk is the builder for creating many InvoiceRequest entities in bulk.
type InvoiceRequestCreateBulk struct {
	config
	err      error
	builders []*InvoiceRequestCreate
	conflict []sql.ConflictOption
}

// Save creates the InvoiceRequest entities in the database.
func (_c *InvoiceRequestCreateBulk) Save(ctx context.Context) ([]*InvoiceRequest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InvoiceRequest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvoiceRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InvoiceRequestCreateBulk) SaveX(ctx context.Context) []*InvoiceRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceRequestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceRequest.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceRequestUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceRequestCreateBulk) OnConflict(opts ...sql.ConflictOption) *InvoiceRequestUpsertBulk {
	_c.conflict = opts
	return &InvoiceRequestUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceRequestCreateBulk) OnConflictColumns(columns ...string) *InvoiceRequestUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceRequestUpsertBulk{
		create: _c,
	}
}

// InvoiceRequestUpsertBulk is the builder for "upsert"-ing
// a bulk of InvoiceRequest nodes.
type InvoiceRequestUpsertBulk struct {
	create *InvoiceRequestCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceRequestUpsertBulk) UpdateNewValues() *InvoiceRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(invoicerequest.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InvoiceRequestUpsertBulk) Ignore() *InvoiceRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceRequestUpsertBulk) DoNothing() *InvoiceRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceRequestCreateBulk.OnConflict
// documentation for more info.
func (u *InvoiceRequestUpsertBulk) Update(set func(*InvoiceRequestUpsert)) *InvoiceRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *InvoiceRequestUpsertBulk) SetUserID(v int64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *InvoiceRequestUpsertBulk) AddUserID(v int64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateUserID() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateUserID()
	})
}

// SetRequestNo sets the "request_no" field.
func (u *InvoiceRequestUpsertBulk) SetRequestNo(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetRequestNo(v)
	})
}

// UpdateRequestNo sets the "request_no" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateRequestNo() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateRequestNo()
	})
}

// SetStatus sets the "status" field.
func (u *InvoiceRequestUpsertBulk) SetStatus(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateStatus() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateStatus()
	})
}

// SetCurrency sets the "currency" field.
func (u *InvoiceRequestUpsertBulk) SetCurrency(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateCurrency() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateCurrency()
	})
}

// SetTotalAmount sets the "total_amount" field.
func (u *InvoiceRequestUpsertBulk) SetTotalAmount(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetTotalAmount(v)
	})
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *InvoiceRequestUpsertBulk) AddTotalAmount(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddTotalAmount(v)
	})
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateTotalAmount() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateTotalAmount()
	})
}

// SetInvoiceType sets the "invoice_type" field.
func (u *InvoiceRequestUpsertBulk) SetInvoiceType(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetInvoiceType(v)
	})
}

// UpdateInvoiceType sets the "invoice_type" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateInvoiceType() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateInvoiceType()
	})
}

// SetInvoiceTitle sets the "invoice_title" field.
func (u *InvoiceRequestUpsertBulk) SetInvoiceTitle(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetInvoiceTitle(v)
	})
}

// UpdateInvoiceTitle sets the "invoice_title" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateInvoiceTitle() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateInvoiceTitle()
	})
}

// SetTaxID sets the "tax_id" field.
func (u *InvoiceRequestUpsertBulk) SetTaxID(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetTaxID(v)
	})
}

// UpdateTaxID sets the "tax_id" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateTaxID() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateTaxID()
	})
}

// ClearTaxID clears the value of the "tax_id" field.
func (u *InvoiceRequestUpsertBulk) ClearTaxID() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearTaxID()
	})
}

// SetBankName sets the "bank_name" field.
func (u *InvoiceRequestUpsertBulk) SetBankName(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetBankName(v)
	})
}

// UpdateBankName sets the "bank_name" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateBankName() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateBankName()
	})
}

// ClearBankName clears the value of the "bank_name" field.
func (u *InvoiceRequestUpsertBulk) ClearBankName() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearBankName()
	})
}

// SetBankAccount sets the "bank_account" field.
func (u *InvoiceRequestUpsertBulk) SetBankAccount(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetBankAccount(v)
	})
}

// UpdateBankAccount sets the "bank_account" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateBankAccount() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateBankAccount()
	})
}

// ClearBankAccount clears the value of the "bank_account" field.
func (u *InvoiceRequestUpsertBulk) ClearBankAccount() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearBankAccount()
	})
}

// SetRecipientEmail sets the "recipient_email" field.
func (u *InvoiceRequestUpsertBulk) SetRecipientEmail(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetRecipientEmail(v)
	})
}

// UpdateRecipientEmail sets the "recipient_email" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateRecipientEmail() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateRecipientEmail()
	})
}

// SetAccountEmail sets the "account_email" field.
func (u *InvoiceRequestUpsertBulk) SetAccountEmail(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetAccountEmail(v)
	})
}

// UpdateAccountEmail sets the "account_email" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateAccountEmail() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateAccountEmail()
	})
}

// SetRemark sets the "remark" field.
func (u *InvoiceRequestUpsertBulk) SetRemark(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateRemark() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *InvoiceRequestUpsertBulk) ClearRemark() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearRemark()
	})
}

// SetRejectionReason sets the "rejection_reason" field.
func (u *InvoiceRequestUpsertBulk) SetRejectionReason(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetRejectionReason(v)
	})
}

// UpdateRejectionReason sets the "rejection_reason" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateRejectionReason() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateRejectionReason()
	})
}

// ClearRejectionReason clears the value of the "rejection_reason" field.
func (u *InvoiceRequestUpsertBulk) ClearRejectionReason() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearRejectionReason()
	})
}

// SetReviewedBy sets the "reviewed_by" field.
func (u *InvoiceRequestUpsertBulk) SetReviewedBy(v int64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetReviewedBy(v)
	})
}

// AddReviewedBy adds v to the "reviewed_by" field.
func (u *InvoiceRequestUpsertBulk) AddReviewedBy(v int64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddReviewedBy(v)
	})
}

// UpdateReviewedBy sets the "reviewed_by" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateReviewedBy() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateReviewedBy()
	})
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (u *InvoiceRequestUpsertBulk) ClearReviewedBy() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearReviewedBy()
	})
}

// SetReviewedAt sets the "reviewed_at" field.
func (u *InvoiceRequestUpsertBulk) SetReviewedAt(v time.Time) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetReviewedAt(v)
	})
}

// UpdateReviewedAt sets the "reviewed_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateReviewedAt() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateReviewedAt()
	})
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (u *InvoiceRequestUpsertBulk) ClearReviewedAt() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearReviewedAt()
	})
}

// SetInvoiceNumber sets the "invoice_number" field.
func (u *InvoiceRequestUpsertBulk) SetInvoiceNumber(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetInvoiceNumber(v)
	})
}

// UpdateInvoiceNumber sets the "invoice_number" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateInvoiceNumber() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateInvoiceNumber()
	})
}

// ClearInvoiceNumber clears the value of the "invoice_number" field.
func (u *InvoiceRequestUpsertBulk) ClearInvoiceNumber() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearInvoiceNumber()
	})
}

// SetIssuedAt sets the "issued_at" field.
func (u *InvoiceRequestUpsertBulk) SetIssuedAt(v time.Time) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetIssuedAt(v)
	})
}

// UpdateIssuedAt sets the "issued_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateIssuedAt() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateIssuedAt()
	})
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (u *InvoiceRequestUpsertBulk) ClearIssuedAt() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearIssuedAt()
	})
}

// SetIssueRemark sets the "issue_remark" field.
func (u *InvoiceRequestUpsertBulk) SetIssueRemark(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetIssueRemark(v)
	})
}

// UpdateIssueRemark sets the "issue_remark" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateIssueRemark() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateIssueRemark()
	})
}

// ClearIssueRemark clears the value of the "issue_remark" field.
func (u *InvoiceRequestUpsertBulk) ClearIssueRemark() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearIssueRemark()
	})
}

// SetSentAt sets the "sent_at" field.
func (u *InvoiceRequestUpsertBulk) SetSentAt(v time.Time) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetSentAt(v)
	})
}

// UpdateSentAt sets the "sent_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateSentAt() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateSentAt()
	})
}

// ClearSentAt clears the value of the "sent_at" field.
func (u *InvoiceRequestUpsertBulk) ClearSentAt() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearSentAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceRequestUpsertBulk) SetUpdatedAt(v time.Time) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateUpdatedAt() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *InvoiceRequestUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InvoiceRequestCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceRequestCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceRequestUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
