// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/BrandonVee/TokenRouter/ent/invoiceattachment"
	"github.com/BrandonVee/TokenRouter/ent/predicate"
)

// InvoiceAttachmentUpdate is the builder for updating InvoiceAttachment entities.
type InvoiceAttachmentUpdate struct {
	config
	hooks    []Hook
	mutation *InvoiceAttachmentMutation
}

// Where appends a list predicates to the InvoiceAttachmentUpdate builder.
func (_u *InvoiceAttachmentUpdate) Where(ps ...predicate.InvoiceAttachment) *InvoiceAttachmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetInvoiceRequestID sets the "invoice_request_id" field.
func (_u *InvoiceAttachmentUpdate) SetInvoiceRequestID(v int64) *InvoiceAttachmentUpdate {
	_u.mutation.ResetInvoiceRequestID()
	_u.mutation.SetInvoiceRequestID(v)
	return _u
}

// SetNillableInvoiceRequestID sets the "invoice_request_id" field if the given value is not nil.
func (_u *InvoiceAttachmentUpdate) SetNillableInvoiceRequestID(v *int64) *InvoiceAttachmentUpdate {
	if v != nil {
		_u.SetInvoiceRequestID(*v)
	}
	return _u
}

// AddInvoiceRequestID adds value to the "invoice_request_id" field.
func (_u *InvoiceAttachmentUpdate) AddInvoiceRequestID(v int64) *InvoiceAttachmentUpdate {
	_u.mutation.AddInvoiceRequestID(v)
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *InvoiceAttachmentUpdate) SetFileName(v string) *InvoiceAttachmentUpdate {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *InvoiceAttachmentUpdate) SetNillableFileName(v *string) *InvoiceAttachmentUpdate {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *InvoiceAttachmentUpdate) SetContentType(v string) *InvoiceAttachmentUpdate {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *InvoiceAttachmentUpdate) SetNillableContentType(v *string) *InvoiceAttachmentUpdate {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *InvoiceAttachmentUpdate) SetSizeBytes(v int64) *InvoiceAttachmentUpdate {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *InvoiceAttachmentUpdate) SetNillableSizeBytes(v *int64) *InvoiceAttachmentUpdate {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *InvoiceAttachmentUpdate) AddSizeBytes(v int64) *InvoiceAttachmentUpdate {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetStorageKey sets the "storage_key" field.
func (_u *InvoiceAttachmentUpdate) SetStorageKey(v string) *InvoiceAttachmentUpdate {
	_u.mutation.SetStorageKey(v)
	return _u
}

// SetNillableStorageKey sets the "storage_key" field if the given value is not nil.
func (_u *InvoiceAttachmentUpdate) SetNillableStorageKey(v *string) *InvoiceAttachmentUpdate {
	if v != nil {
		_u.SetStorageKey(*v)
	}
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *InvoiceAttachmentUpdate) SetSha256(v string) *InvoiceAttachmentUpdate {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *InvoiceAttachmentUpdate) SetNillableSha256(v *string) *InvoiceAttachmentUpdate {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// SetUploadedBy sets the "uploaded_by" field.
func (_u *InvoiceAttachmentUpdate) SetUploadedBy(v int64) *InvoiceAttachmentUpdate {
	_u.mutation.ResetUploadedBy()
	_u.mutation.SetUploadedBy(v)
	return _u
}

// SetNillableUploadedBy sets the "uploaded_by" field if the given value is not nil.
func (_u *InvoiceAttachmentUpdate) SetNillableUploadedBy(v *int64) *InvoiceAttachmentUpdate {
	if v != nil {
		_u.SetUploadedBy(*v)
	}
	return _u
}

// AddUploadedBy adds value to the "uploaded_by" field.
func (_u *InvoiceAttachmentUpdate) AddUploadedBy(v int64) *InvoiceAttachmentUpdate {
	_u.mutation.AddUploadedBy(v)
	return _u
}

// Mutation returns the InvoiceAttachmentMutation object of the builder.
func (_u *InvoiceAttachmentUpdate) Mutation() *InvoiceAttachmentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InvoiceAttachmentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceAttachmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InvoiceAttachmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceAttachmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceAttachmentUpdate) check() error {
	if v, ok := _u.mutation.FileName(); ok {
		if err := invoiceattachment.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "InvoiceAttachment.file_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentType(); ok {
		if err := invoiceattachment.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceAttachment.content_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StorageKey(); ok {
		if err := invoiceattachment.StorageKeyValidator(v); err != nil {
			return &ValidationError{Name: "storage_key", err: fmt.Errorf(`ent: validator failed for field "InvoiceAttachment.storage_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sha256(); ok {
		if err := invoiceattachment.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "InvoiceAttachment.sha256": %w`, err)}
		}
	}
	return nil
}

func (_u *InvoiceAttachmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoiceattachment.Table, invoiceattachment.Columns, sqlgraph.NewFieldSpec(invoiceattachment.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.InvoiceRequestID(); ok {
		_spec.SetField(invoiceattachment.FieldInvoiceRequestID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInvoiceRequestID(); ok {
		_spec.AddField(invoiceattachment.FieldInvoiceRequestID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(invoiceattachment.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(invoiceattachment.FieldContentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(invoiceattachment.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(invoiceattachment.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StorageKey(); ok {
		_spec.SetField(invoiceattachment.FieldStorageKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(invoiceattachment.FieldSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.UploadedBy(); ok {
		_spec.SetField(invoiceattachment.FieldUploadedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUploadedBy(); ok {
		_spec.AddField(invoiceattachment.FieldUploadedBy, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoiceattachment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InvoiceAttachmentUpdateOne is the builder for updating a single InvoiceAttachment entity.
type InvoiceAttachmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InvoiceAttachmentMutation
}

// SetInvoiceRequestID sets the "invoice_request_id" field.
func (_u *InvoiceAttachmentUpdateOne) SetInvoiceRequestID(v int64) *InvoiceAttachmentUpdateOne {
	_u.mutation.ResetInvoiceRequestID()
	_u.mutation.SetInvoiceRequestID(v)
	return _u
}

// SetNillableInvoiceRequestID sets the "invoice_request_id" field if the given value is not nil.
func (_u *InvoiceAttachmentUpdateOne) SetNillableInvoiceRequestID(v *int64) *InvoiceAttachmentUpdateOne {
	if v != nil {
		_u.SetInvoiceRequestID(*v)
	}
	return _u
}

// AddInvoiceRequestID adds value to the "invoice_request_id" field.
func (_u *InvoiceAttachmentUpdateOne) AddInvoiceRequestID(v int64) *InvoiceAttachmentUpdateOne {
	_u.mutation.AddInvoiceRequestID(v)
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *InvoiceAttachmentUpdateOne) SetFileName(v string) *InvoiceAttachmentUpdateOne {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *InvoiceAttachmentUpdateOne) SetNillableFileName(v *string) *InvoiceAttachmentUpdateOne {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *InvoiceAttachmentUpdateOne) SetContentType(v string) *InvoiceAttachmentUpdateOne {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *InvoiceAttachmentUpdateOne) SetNillableContentType(v *string) *InvoiceAttachmentUpdateOne {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *InvoiceAttachmentUpdateOne) SetSizeBytes(v int64) *InvoiceAttachmentUpdateOne {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *InvoiceAttachmentUpdateOne) SetNillableSizeBytes(v *int64) *InvoiceAttachmentUpdateOne {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *InvoiceAttachmentUpdateOne) AddSizeBytes(v int64) *InvoiceAttachmentUpdateOne {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetStorageKey sets the "storage_key" field.
func (_u *InvoiceAttachmentUpdateOne) SetStorageKey(v string) *InvoiceAttachmentUpdateOne {
	_u.mutation.SetStorageKey(v)
	return _u
}

// SetNillableStorageKey sets the "storage_key" field if the given value is not nil.
func (_u *InvoiceAttachmentUpdateOne) SetNillableStorageKey(v *string) *InvoiceAttachmentUpdateOne {
	if v != nil {
		_u.SetStorageKey(*v)
	}
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *InvoiceAttachmentUpdateOne) SetSha256(v string) *InvoiceAttachmentUpdateOne {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *InvoiceAttachmentUpdateOne) SetNillableSha256(v *string) *InvoiceAttachmentUpdateOne {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// SetUploadedBy sets the "uploaded_by" field.
func (_u *InvoiceAttachmentUpdateOne) SetUploadedBy(v int64) *InvoiceAttachmentUpdateOne {
	_u.mutation.ResetUploadedBy()
	_u.mutation.SetUploadedBy(v)
	return _u
}

// SetNillableUploadedBy sets the "uploaded_by" field if the given value is not nil.
func (_u *InvoiceAttachmentUpdateOne) SetNillableUploadedBy(v *int64) *InvoiceAttachmentUpdateOne {
	if v != nil {
		_u.SetUploadedBy(*v)
	}
	return _u
}

// AddUploadedBy adds value to the "uploaded_by" field.
func (_u *InvoiceAttachmentUpdateOne) AddUploadedBy(v int64) *InvoiceAttachmentUpdateOne {
	_u.mutation.AddUploadedBy(v)
	return _u
}

// Mutation returns the InvoiceAttachmentMutation object of the builder.
func (_u *InvoiceAttachmentUpdateOne) Mutation() *InvoiceAttachmentMutation {
	return _u.mutation
}

// Where appends a list predicates to the InvoiceAttachmentUpdate builder.
func (_u *InvoiceAttachmentUpdateOne) Where(ps ...predicate.InvoiceAttachment) *InvoiceAttachmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InvoiceAttachmentUpdateOne) Select(field string, fields ...string) *InvoiceAttachmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InvoiceAttachment entity.
func (_u *InvoiceAttachmentUpdateOne) Save(ctx context.Context) (*InvoiceAttachment, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceAttachmentUpdateOne) SaveX(ctx context.Context) *InvoiceAttachment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InvoiceAttachmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceAttachmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceAttachmentUpdateOne) check() error {
	if v, ok := _u.mutation.FileName(); ok {
		if err := invoiceattachment.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "InvoiceAttachment.file_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentType(); ok {
		if err := invoiceattachment.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceAttachment.content_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StorageKey(); ok {
		if err := invoiceattachment.StorageKeyValidator(v); err != nil {
			return &ValidationError{Name: "storage_key", err: fmt.Errorf(`ent: validator failed for field "InvoiceAttachment.storage_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sha256(); ok {
		if err := invoiceattachment.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "InvoiceAttachment.sha256": %w`, err)}
		}
	}
	return nil
}

func (_u *InvoiceAttachmentUpdateOne) sqlSave(ctx context.Context) (_node *InvoiceAttachment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoiceattachment.Table, invoiceattachment.Columns, sqlgraph.NewFieldSpec(invoiceattachment.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InvoiceAttachment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invoiceattachment.FieldID)
		for _, f := range fields {
			if !invoiceattachment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invoiceattachment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.InvoiceRequestID(); ok {
		_spec.SetField(invoiceattachment.FieldInvoiceRequestID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInvoiceRequestID(); ok {
		_spec.AddField(invoiceattachment.FieldInvoiceRequestID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(invoiceattachment.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(invoiceattachment.FieldContentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(invoiceattachment.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(invoiceattachment.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StorageKey(); ok {
		_spec.SetField(invoiceattachment.FieldStorageKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(invoiceattachment.FieldSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.UploadedBy(); ok {
		_spec.SetField(invoiceattachment.FieldUploadedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUploadedBy(); ok {
		_spec.AddField(invoiceattachment.FieldUploadedBy, field.TypeInt64, value)
	}
	_node = &InvoiceAttachment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoiceattachment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
