// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/BrandonVee/TokenRouter/ent/invoicedelivery"
)

// InvoiceDeliveryCreate is the builder for creating a InvoiceDelivery entity.
type InvoiceDeliveryCreate struct {
	config
	mutation *InvoiceDeliveryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetInvoiceRequestID sets the "invoice_request_id" field.
func (_c *InvoiceDeliveryCreate) SetInvoiceRequestID(v int64) *InvoiceDeliveryCreate {
	_c.mutation.SetInvoiceRequestID(v)
	return _c
}

// SetRecipientEmail sets the "recipient_email" field.
func (_c *InvoiceDeliveryCreate) SetRecipientEmail(v string) *InvoiceDeliveryCreate {
	_c.mutation.SetRecipientEmail(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *InvoiceDeliveryCreate) SetStatus(v string) *InvoiceDeliveryCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetMessageID sets the "message_id" field.
func (_c *InvoiceDeliveryCreate) SetMessageID(v string) *InvoiceDeliveryCreate {
	_c.mutation.SetMessageID(v)
	return _c
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_c *InvoiceDeliveryCreate) SetNillableMessageID(v *string) *InvoiceDeliveryCreate {
	if v != nil {
		_c.SetMessageID(*v)
	}
	return _c
}

// SetAttachmentSummary sets the "attachment_summary" field.
func (_c *InvoiceDeliveryCreate) SetAttachmentSummary(v string) *InvoiceDeliveryCreate {
	_c.mutation.SetAttachmentSummary(v)
	return _c
}

// SetNillableAttachmentSummary sets the "attachment_summary" field if the given value is not nil.
func (_c *InvoiceDeliveryCreate) SetNillableAttachmentSummary(v *string) *InvoiceDeliveryCreate {
	if v != nil {
		_c.SetAttachmentSummary(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *InvoiceDeliveryCreate) SetErrorMessage(v string) *InvoiceDeliveryCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *InvoiceDeliveryCreate) SetNillableErrorMessage(v *string) *InvoiceDeliveryCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetSentBy sets the "sent_by" field.
func (_c *InvoiceDeliveryCreate) SetSentBy(v int64) *InvoiceDeliveryCreate {
	_c.mutation.SetSentBy(v)
	return _c
}

// SetNillableSentBy sets the "sent_by" field if the given value is not nil.
func (_c *InvoiceDeliveryCreate) SetNillableSentBy(v *int64) *InvoiceDeliveryCreate {
	if v != nil {
		_c.SetSentBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InvoiceDeliveryCreate) SetCreatedAt(v time.Time) *InvoiceDeliveryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InvoiceDeliveryCreate) SetNillableCreatedAt(v *time.Time) *InvoiceDeliveryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the InvoiceDeliveryMutation object of the builder.
func (_c *InvoiceDeliveryCreate) Mutation() *InvoiceDeliveryMutation {
	return _c.mutation
}

// Save creates the InvoiceDelivery in the database.
func (_c *InvoiceDeliveryCreate) Save(ctx context.Context) (*InvoiceDelivery, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InvoiceDeliveryCreate) SaveX(ctx context.Context) *InvoiceDelivery {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceDeliveryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceDeliveryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InvoiceDeliveryCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := invoicedelivery.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InvoiceDeliveryCreate) check() error {
	if _, ok := _c.mutation.InvoiceRequestID(); !ok {
		return &ValidationError{Name: "invoice_request_id", err: errors.New(`ent: missing required field "InvoiceDelivery.invoice_request_id"`)}
	}
	if _, ok := _c.mutation.RecipientEmail(); !ok {
		return &ValidationError{Name: "recipient_email", err: errors.New(`ent: missing required field "InvoiceDelivery.recipient_email"`)}
	}
	if v, ok := _c.mutation.RecipientEmail(); ok {
		if err := invoicedelivery.RecipientEmailValidator(v); err != nil {
			return &ValidationError{Name: "recipient_email", err: fmt.Errorf(`ent: validator failed for field "InvoiceDelivery.recipient_email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "InvoiceDelivery.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := invoicedelivery.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InvoiceDelivery.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.MessageID(); ok {
		if err := invoicedelivery.MessageIDValidator(v); err != nil {
			return &ValidationError{Name: "message_id", err: fmt.Errorf(`ent: validator failed for field "InvoiceDelivery.message_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InvoiceDelivery.created_at"`)}
	}
	return nil
}

func (_c *InvoiceDeliveryCreate) sqlSave(ctx context.Context) (*InvoiceDelivery, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InvoiceDeliveryCreate) createSpec() (*InvoiceDelivery, *sqlgraph.CreateSpec) {
	var (
		_node = &InvoiceDelivery{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invoicedelivery.Table, sqlgraph.NewFieldSpec(invoicedelivery.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.InvoiceRequestID(); ok {
		_spec.SetField(invoicedelivery.FieldInvoiceRequestID, field.TypeInt64, value)
		_node.InvoiceRequestID = value
	}
	if value, ok := _c.mutation.RecipientEmail(); ok {
		_spec.SetField(invoicedelivery.FieldRecipientEmail, field.TypeString, value)
		_node.RecipientEmail = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(invoicedelivery.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.MessageID(); ok {
		_spec.SetField(invoicedelivery.FieldMessageID, field.TypeString, value)
		_node.MessageID = &value
	}
	if value, ok := _c.mutation.AttachmentSummary(); ok {
		_spec.SetField(invoicedelivery.FieldAttachmentSummary, field.TypeString, value)
		_node.AttachmentSummary = &value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(invoicedelivery.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.SentBy(); ok {
		_spec.SetField(invoicedelivery.FieldSentBy, field.TypeInt64, value)
		_node.SentBy = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(invoicedelivery.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceDelivery.Create().
//		SetInvoiceRequestID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceDeliveryUpsert) {
//			SetInvoiceRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceDeliveryCreate) OnConflict(opts ...sql.ConflictOption) *InvoiceDeliveryUpsertOne {
	_c.conflict = opts
	return &InvoiceDeliveryUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceDelivery.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceDeliveryCreate) OnConflictColumns(columns ...string) *InvoiceDeliveryUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceDeliveryUpsertOne{
		create: _c,
	}
}

type (
	// InvoiceDeliveryUpsertOne is the builder for "upsert"-ing
	//  one InvoiceDelivery node.
	InvoiceDeliveryUpsertOne struct {
		create *InvoiceDeliveryCreate
	}

	// InvoiceDeliveryUpsert is the "OnConflict" setter.
	InvoiceDeliveryUpsert struct {
		*sql.UpdateSet
	}
)

// SetInvoiceRequestID sets the "invoice_request_id" field.
func (u *InvoiceDeliveryUpsert) SetInvoiceRequestID(v int64) *InvoiceDeliveryUpsert {
	u.Set(invoicedelivery.FieldInvoiceRequestID, v)
	return u
}

// UpdateInvoiceRequestID sets the "invoice_request_id" field to the value that was provided on create.
func (u *InvoiceDeliveryUpsert) UpdateInvoiceRequestID() *InvoiceDeliveryUpsert {
	u.SetExcluded(invoicedelivery.FieldInvoiceRequestID)
	return u
}

// AddInvoiceRequestID adds v to the "invoice_request_id" field.
func (u *InvoiceDeliveryUpsert) AddInvoiceRequestID(v int64) *InvoiceDeliveryUpsert {
	u.Add(invoicedelivery.FieldInvoiceRequestID, v)
	return u
}

// SetRecipientEmail sets the "recipient_email" field.
func (u *InvoiceDeliveryUpsert) SetRecipientEmail(v string) *InvoiceDeliveryUpsert {
	u.Set(invoicedelivery.FieldRecipientEmail, v)
	return u
}

// UpdateRecipientEmail sets the "recipient_email" field to the value that was provided on create.
func (u *InvoiceDeliveryUpsert) UpdateRecipientEmail() *InvoiceDeliveryUpsert {
	u.SetExcluded(invoicedelivery.FieldRecipientEmail)
	return u
}

// SetStatus sets the "status" field.
func (u *InvoiceDeliveryUpsert) SetStatus(v string) *InvoiceDeliveryUpsert {
	u.Set(invoicedelivery.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceDeliveryUpsert) UpdateStatus() *InvoiceDeliveryUpsert {
	u.SetExcluded(invoicedelivery.FieldStatus)
	return u
}

// SetMessageID sets the "message_id" field.
func (u *InvoiceDeliveryUpsert) SetMessageID(v string) *InvoiceDeliveryUpsert {
	u.Set(invoicedelivery.FieldMessageID, v)
	return u
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *InvoiceDeliveryUpsert) UpdateMessageID() *InvoiceDeliveryUpsert {
	u.SetExcluded(invoicedelivery.FieldMessageID)
	return u
}

// ClearMessageID clears the value of the "message_id" field.
func (u *InvoiceDeliveryUpsert) ClearMessageID() *InvoiceDeliveryUpsert {
	u.SetNull(invoicedelivery.FieldMessageID)
	return u
}

// SetAttachmentSummary sets the "attachment_summary" field.
func (u *InvoiceDeliveryUpsert) SetAttachmentSummary(v string) *InvoiceDeliveryUpsert {
	u.Set(invoicedelivery.FieldAttachmentSummary, v)
	return u
}

// UpdateAttachmentSummary sets the "attachment_summary" field to the value that was provided on create.
func (u *InvoiceDeliveryUpsert) UpdateAttachmentSummary() *InvoiceDeliveryUpsert {
	u.SetExcluded(invoicedelivery.FieldAttachmentSummary)
	return u
}

// ClearAttachmentSummary clears the value of the "attachment_summary" field.
func (u *InvoiceDeliveryUpsert) ClearAttachmentSummary() *InvoiceDeliveryUpsert {
	u.SetNull(invoicedelivery.FieldAttachmentSummary)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *InvoiceDeliveryUpsert) SetErrorMessage(v string) *InvoiceDeliveryUpsert {
	u.Set(invoicedelivery.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *InvoiceDeliveryUpsert) UpdateErrorMessage() *InvoiceDeliveryUpsert {
	u.SetExcluded(invoicedelivery.FieldErrorMessage)
	return u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *InvoiceDeliveryUpsert) ClearErrorMessage() *InvoiceDeliveryUpsert {
	u.SetNull(invoicedelivery.FieldErrorMessage)
	return u
}

// SetSentBy sets the "sent_by" field.
func (u *InvoiceDeliveryUpsert) SetSentBy(v int64) *InvoiceDeliveryUpsert {
	u.Set(invoicedelivery.FieldSentBy, v)
	return u
}

// UpdateSentBy sets the "sent_by" field to the value that was provided on create.
func (u *InvoiceDeliveryUpsert) UpdateSentBy() *InvoiceDeliveryUpsert {
	u.SetExcluded(invoicedelivery.FieldSentBy)
	return u
}

// AddSentBy adds v to the "sent_by" field.
func (u *InvoiceDeliveryUpsert) AddSentBy(v int64) *InvoiceDeliveryUpsert {
	u.Add(invoicedelivery.FieldSentBy, v)
	return u
}

// ClearSentBy clears the value of the "sent_by" field.
func (u *InvoiceDeliveryUpsert) ClearSentBy() *InvoiceDeliveryUpsert {
	u.SetNull(invoicedelivery.FieldSentBy)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.InvoiceDelivery.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceDeliveryUpsertOne) UpdateNewValues() *InvoiceDeliveryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(invoicedelivery.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceDelivery.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InvoiceDeliveryUpsertOne) Ignore() *InvoiceDeliveryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceDeliveryUpsertOne) DoNothing() *InvoiceDeliveryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceDeliveryCreate.OnConflict
// documentation for more info.
func (u *InvoiceDeliveryUpsertOne) Update(set func(*InvoiceDeliveryUpsert)) *InvoiceDeliveryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceDeliveryUpsert{UpdateSet: update})
	}))
	return u
}

// SetInvoiceRequestID sets the "invoice_request_id" field.
func (u *InvoiceDeliveryUpsertOne) SetInvoiceRequestID(v int64) *InvoiceDeliveryUpsertOne {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.SetInvoiceRequestID(v)
	})
}

// AddInvoiceRequestID adds v to the "invoice_request_id" field.
func (u *InvoiceDeliveryUpsertOne) AddInvoiceRequestID(v int64) *InvoiceDeliveryUpsertOne {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.AddInvoiceRequestID(v)
	})
}

// UpdateInvoiceRequestID sets the "invoice_request_id" field to the value that was provided on create.
func (u *InvoiceDeliveryUpsertOne) UpdateInvoiceRequestID() *InvoiceDeliveryUpsertOne {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.UpdateInvoiceRequestID()
	})
}

// SetRecipientEmail sets the "recipient_email" field.
func (u *InvoiceDeliveryUpsertOne) SetRecipientEmail(v string) *InvoiceDeliveryUpsertOne {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.SetRecipientEmail(v)
	})
}

// UpdateRecipientEmail sets the "recipient_email" field to the value that was provided on create.
func (u *InvoiceDeliveryUpsertOne) UpdateRecipientEmail() *InvoiceDeliveryUpsertOne {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.UpdateRecipientEmail()
	})
}

// SetStatus sets the "status" field.
func (u *InvoiceDeliveryUpsertOne) SetStatus(v string) *InvoiceDeliveryUpsertOne {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceDeliveryUpsertOne) UpdateStatus() *InvoiceDeliveryUpsertOne {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.UpdateStatus()
	})
}

// SetMessageID sets the "message_id" field.
func (u *InvoiceDeliveryUpsertOne) SetMessageID(v string) *InvoiceDeliveryUpsertOne {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.SetMessageID(v)
	})
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *InvoiceDeliveryUpsertOne) UpdateMessageID() *InvoiceDeliveryUpsertOne {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.UpdateMessageID()
	})
}

// ClearMessageID clears the value of the "message_id" field.
func (u *InvoiceDeliveryUpsertOne) ClearMessageID() *InvoiceDeliveryUpsertOne {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.ClearMessageID()
	})
}

// SetAttachmentSummary sets the "attachment_summary" field.
func (u *InvoiceDeliveryUpsertOne) SetAttachmentSummary(v string) *InvoiceDeliveryUpsertOne {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.SetAttachmentSummary(v)
	})
}

// UpdateAttachmentSummary sets the "attachment_summary" field to the value that was provided on create.
func (u *InvoiceDeliveryUpsertOne) UpdateAttachmentSummary() *InvoiceDeliveryUpsertOne {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.UpdateAttachmentSummary()
	})
}

// ClearAttachmentSummary clears the value of the "attachment_summary" field.
func (u *InvoiceDeliveryUpsertOne) ClearAttachmentSummary() *InvoiceDeliveryUpsertOne {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.ClearAttachmentSummary()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *InvoiceDeliveryUpsertOne) SetErrorMessage(v string) *InvoiceDeliveryUpsertOne {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *InvoiceDeliveryUpsertOne) UpdateErrorMessage() *InvoiceDeliveryUpsertOne {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *InvoiceDeliveryUpsertOne) ClearErrorMessage() *InvoiceDeliveryUpsertOne {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.ClearErrorMessage()
	})
}

// SetSentBy sets the "sent_by" field.
func (u *InvoiceDeliveryUpsertOne) SetSentBy(v int64) *InvoiceDeliveryUpsertOne {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.SetSentBy(v)
	})
}

// AddSentBy adds v to the "sent_by" field.
func (u *InvoiceDeliveryUpsertOne) AddSentBy(v int64) *InvoiceDeliveryUpsertOne {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.AddSentBy(v)
	})
}

// UpdateSentBy sets the "sent_by" field to the value that was provided on create.
func (u *InvoiceDeliveryUpsertOne) UpdateSentBy() *InvoiceDeliveryUpsertOne {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.UpdateSentBy()
	})
}

// ClearSentBy clears the value of the "sent_by" field.
func (u *InvoiceDeliveryUpsertOne) ClearSentBy() *InvoiceDeliveryUpsertOne {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.ClearSentBy()
	})
}

// Exec executes the query.
func (u *InvoiceDeliveryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceDeliveryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceDeliveryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InvoiceDeliveryUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InvoiceDeliveryUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InvoiceDeliveryCreateBulk is the builder for creating many InvoiceDelivery entities in bulk.
type InvoiceDeliveryCreateBulk struct {
	config
	err      error
	builders []*InvoiceDeliveryCreate
	conflict []sql.ConflictOption
}

// Save creates the InvoiceDelivery entities in the database.
func (_c *InvoiceDeliveryCreateBulk) Save(ctx context.Context) ([]*InvoiceDelivery, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InvoiceDelivery, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvoiceDeliveryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InvoiceDeliveryCreateBulk) SaveX(ctx context.Context) []*InvoiceDelivery {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceDeliveryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceDeliveryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceDelivery.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceDeliveryUpsert) {
//			SetInvoiceRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceDeliveryCreateBulk) OnConflict(opts ...sql.ConflictOption) *InvoiceDeliveryUpsertBulk {
	_c.conflict = opts
	return &InvoiceDeliveryUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceDelivery.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceDeliveryCreateBulk) OnConflictColumns(columns ...string) *InvoiceDeliveryUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceDeliveryUpsertBulk{
		create: _c,
	}
}

// InvoiceDeliveryUpsertBulk is the builder for "upsert"-ing
// a bulk of InvoiceDelivery nodes.
type InvoiceDeliveryUpsertBulk struct {
	create *InvoiceDeliveryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.InvoiceDelivery.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceDeliveryUpsertBulk) UpdateNewValues() *InvoiceDeliveryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(invoicedelivery.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceDelivery.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InvoiceDeliveryUpsertBulk) Ignore() *InvoiceDeliveryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceDeliveryUpsertBulk) DoNothing() *InvoiceDeliveryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceDeliveryCreateBulk.OnConflict
// documentation for more info.
func (u *InvoiceDeliveryUpsertBulk) Update(set func(*InvoiceDeliveryUpsert)) *InvoiceDeliveryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceDeliveryUpsert{UpdateSet: update})
	}))
	return u
}

// SetInvoiceRequestID sets the "invoice_request_id" field.
func (u *InvoiceDeliveryUpsertBulk) SetInvoiceRequestID(v int64) *InvoiceDeliveryUpsertBulk {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.SetInvoiceRequestID(v)
	})
}

// AddInvoiceRequestID adds v to the "invoice_request_id" field.
func (u *InvoiceDeliveryUpsertBulk) AddInvoiceRequestID(v int64) *InvoiceDeliveryUpsertBulk {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.AddInvoiceRequestID(v)
	})
}

// UpdateInvoiceRequestID sets the "invoice_request_id" field to the value that was provided on create.
func (u *InvoiceDeliveryUpsertBulk) UpdateInvoiceRequestID() *InvoiceDeliveryUpsertBulk {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.UpdateInvoiceRequestID()
	})
}

// SetRecipientEmail sets the "recipient_email" field.
func (u *InvoiceDeliveryUpsertBulk) SetRecipientEmail(v string) *InvoiceDeliveryUpsertBulk {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.SetRecipientEmail(v)
	})
}

// UpdateRecipientEmail sets the "recipient_email" field to the value that was provided on create.
func (u *InvoiceDeliveryUpsertBulk) UpdateRecipientEmail() *InvoiceDeliveryUpsertBulk {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.UpdateRecipientEmail()
	})
}

// SetStatus sets the "status" field.
func (u *InvoiceDeliveryUpsertBulk) SetStatus(v string) *InvoiceDeliveryUpsertBulk {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceDeliveryUpsertBulk) UpdateStatus() *InvoiceDeliveryUpsertBulk {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.UpdateStatus()
	})
}

// SetMessageID sets the "message_id" field.
func (u *InvoiceDeliveryUpsertBulk) SetMessageID(v string) *InvoiceDeliveryUpsertBulk {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.SetMessageID(v)
	})
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *InvoiceDeliveryUpsertBulk) UpdateMessageID() *InvoiceDeliveryUpsertBulk {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.UpdateMessageID()
	})
}

// ClearMessageID clears the value of the "message_id" field.
func (u *InvoiceDeliveryUpsertBulk) ClearMessageID() *InvoiceDeliveryUpsertBulk {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.ClearMessageID()
	})
}

// SetAttachmentSummary sets the "attachment_summary" field.
func (u *InvoiceDeliveryUpsertBulk) SetAttachmentSummary(v string) *InvoiceDeliveryUpsertBulk {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.SetAttachmentSummary(v)
	})
}

// UpdateAttachmentSummary sets the "attachment_summary" field to the value that was provided on create.
func (u *InvoiceDeliveryUpsertBulk) UpdateAttachmentSummary() *InvoiceDeliveryUpsertBulk {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.UpdateAttachmentSummary()
	})
}

// ClearAttachmentSummary clears the value of the "attachment_summary" field.
func (u *InvoiceDeliveryUpsertBulk) ClearAttachmentSummary() *InvoiceDeliveryUpsertBulk {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.ClearAttachmentSummary()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *InvoiceDeliveryUpsertBulk) SetErrorMessage(v string) *InvoiceDeliveryUpsertBulk {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *InvoiceDeliveryUpsertBulk) UpdateErrorMessage() *InvoiceDeliveryUpsertBulk {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *InvoiceDeliveryUpsertBulk) ClearErrorMessage() *InvoiceDeliveryUpsertBulk {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.ClearErrorMessage()
	})
}

// SetSentBy sets the "sent_by" field.
func (u *InvoiceDeliveryUpsertBulk) SetSentBy(v int64) *InvoiceDeliveryUpsertBulk {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.SetSentBy(v)
	})
}

// AddSentBy adds v to the "sent_by" field.
func (u *InvoiceDeliveryUpsertBulk) AddSentBy(v int64) *InvoiceDeliveryUpsertBulk {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.AddSentBy(v)
	})
}

// UpdateSentBy sets the "sent_by" field to the value that was provided on create.
func (u *InvoiceDeliveryUpsertBulk) UpdateSentBy() *InvoiceDeliveryUpsertBulk {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.UpdateSentBy()
	})
}

// ClearSentBy clears the value of the "sent_by" field.
func (u *InvoiceDeliveryUpsertBulk) ClearSentBy() *InvoiceDeliveryUpsertBulk {
	return u.Update(func(s *InvoiceDeliveryUpsert) {
		s.ClearSentBy()
	})
}

// Exec executes the query.
func (u *InvoiceDeliveryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InvoiceDeliveryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceDeliveryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceDeliveryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
