// Code generated by ent, DO NOT EDIT.

package imagehistory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/BrandonVee/TokenRouter/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldContainsFold(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEQ(FieldUserID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEQ(FieldAPIKeyID, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEQ(FieldRequestID, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEQ(FieldSource, v))
}

// Endpoint applies equality check predicate on the "endpoint" field. It's identical to EndpointEQ.
func Endpoint(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEQ(FieldEndpoint, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEQ(FieldModel, v))
}

// Prompt applies equality check predicate on the "prompt" field. It's identical to PromptEQ.
func Prompt(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEQ(FieldPrompt, v))
}

// RevisedPrompt applies equality check predicate on the "revised_prompt" field. It's identical to RevisedPromptEQ.
func RevisedPrompt(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEQ(FieldRevisedPrompt, v))
}

// ObjectKey applies equality check predicate on the "object_key" field. It's identical to ObjectKeyEQ.
func ObjectKey(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEQ(FieldObjectKey, v))
}

// MimeType applies equality check predicate on the "mime_type" field. It's identical to MimeTypeEQ.
func MimeType(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEQ(FieldMimeType, v))
}

// SizeBytes applies equality check predicate on the "size_bytes" field. It's identical to SizeBytesEQ.
func SizeBytes(v int64) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEQ(FieldSizeBytes, v))
}

// Width applies equality check predicate on the "width" field. It's identical to WidthEQ.
func Width(v int) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEQ(FieldWidth, v))
}

// Height applies equality check predicate on the "height" field. It's identical to HeightEQ.
func Height(v int) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEQ(FieldHeight, v))
}

// Sha256 applies equality check predicate on the "sha256" field. It's identical to Sha256EQ.
func Sha256(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEQ(FieldSha256, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldLTE(FieldUserID, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldLTE(FieldAPIKeyID, v))
}

// APIKeyIDIsNil applies the IsNil predicate on the "api_key_id" field.
func APIKeyIDIsNil() predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldIsNull(FieldAPIKeyID))
}

// APIKeyIDNotNil applies the NotNil predicate on the "api_key_id" field.
func APIKeyIDNotNil() predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNotNull(FieldAPIKeyID))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldContainsFold(FieldRequestID, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldContainsFold(FieldSource, v))
}

// EndpointEQ applies the EQ predicate on the "endpoint" field.
func EndpointEQ(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEQ(FieldEndpoint, v))
}

// EndpointNEQ applies the NEQ predicate on the "endpoint" field.
func EndpointNEQ(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNEQ(FieldEndpoint, v))
}

// EndpointIn applies the In predicate on the "endpoint" field.
func EndpointIn(vs ...string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldIn(FieldEndpoint, vs...))
}

// EndpointNotIn applies the NotIn predicate on the "endpoint" field.
func EndpointNotIn(vs ...string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNotIn(FieldEndpoint, vs...))
}

// EndpointGT applies the GT predicate on the "endpoint" field.
func EndpointGT(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldGT(FieldEndpoint, v))
}

// EndpointGTE applies the GTE predicate on the "endpoint" field.
func EndpointGTE(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldGTE(FieldEndpoint, v))
}

// EndpointLT applies the LT predicate on the "endpoint" field.
func EndpointLT(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldLT(FieldEndpoint, v))
}

// EndpointLTE applies the LTE predicate on the "endpoint" field.
func EndpointLTE(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldLTE(FieldEndpoint, v))
}

// EndpointContains applies the Contains predicate on the "endpoint" field.
func EndpointContains(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldContains(FieldEndpoint, v))
}

// EndpointHasPrefix applies the HasPrefix predicate on the "endpoint" field.
func EndpointHasPrefix(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldHasPrefix(FieldEndpoint, v))
}

// EndpointHasSuffix applies the HasSuffix predicate on the "endpoint" field.
func EndpointHasSuffix(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldHasSuffix(FieldEndpoint, v))
}

// EndpointEqualFold applies the EqualFold predicate on the "endpoint" field.
func EndpointEqualFold(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEqualFold(FieldEndpoint, v))
}

// EndpointContainsFold applies the ContainsFold predicate on the "endpoint" field.
func EndpointContainsFold(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldContainsFold(FieldEndpoint, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldContainsFold(FieldModel, v))
}

// PromptEQ applies the EQ predicate on the "prompt" field.
func PromptEQ(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEQ(FieldPrompt, v))
}

// PromptNEQ applies the NEQ predicate on the "prompt" field.
func PromptNEQ(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNEQ(FieldPrompt, v))
}

// PromptIn applies the In predicate on the "prompt" field.
func PromptIn(vs ...string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldIn(FieldPrompt, vs...))
}

// PromptNotIn applies the NotIn predicate on the "prompt" field.
func PromptNotIn(vs ...string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNotIn(FieldPrompt, vs...))
}

// PromptGT applies the GT predicate on the "prompt" field.
func PromptGT(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldGT(FieldPrompt, v))
}

// PromptGTE applies the GTE predicate on the "prompt" field.
func PromptGTE(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldGTE(FieldPrompt, v))
}

// PromptLT applies the LT predicate on the "prompt" field.
func PromptLT(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldLT(FieldPrompt, v))
}

// PromptLTE applies the LTE predicate on the "prompt" field.
func PromptLTE(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldLTE(FieldPrompt, v))
}

// PromptContains applies the Contains predicate on the "prompt" field.
func PromptContains(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldContains(FieldPrompt, v))
}

// PromptHasPrefix applies the HasPrefix predicate on the "prompt" field.
func PromptHasPrefix(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldHasPrefix(FieldPrompt, v))
}

// PromptHasSuffix applies the HasSuffix predicate on the "prompt" field.
func PromptHasSuffix(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldHasSuffix(FieldPrompt, v))
}

// PromptEqualFold applies the EqualFold predicate on the "prompt" field.
func PromptEqualFold(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEqualFold(FieldPrompt, v))
}

// PromptContainsFold applies the ContainsFold predicate on the "prompt" field.
func PromptContainsFold(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldContainsFold(FieldPrompt, v))
}

// RevisedPromptEQ applies the EQ predicate on the "revised_prompt" field.
func RevisedPromptEQ(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEQ(FieldRevisedPrompt, v))
}

// RevisedPromptNEQ applies the NEQ predicate on the "revised_prompt" field.
func RevisedPromptNEQ(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNEQ(FieldRevisedPrompt, v))
}

// RevisedPromptIn applies the In predicate on the "revised_prompt" field.
func RevisedPromptIn(vs ...string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldIn(FieldRevisedPrompt, vs...))
}

// RevisedPromptNotIn applies the NotIn predicate on the "revised_prompt" field.
func RevisedPromptNotIn(vs ...string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNotIn(FieldRevisedPrompt, vs...))
}

// RevisedPromptGT applies the GT predicate on the "revised_prompt" field.
func RevisedPromptGT(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldGT(FieldRevisedPrompt, v))
}

// RevisedPromptGTE applies the GTE predicate on the "revised_prompt" field.
func RevisedPromptGTE(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldGTE(FieldRevisedPrompt, v))
}

// RevisedPromptLT applies the LT predicate on the "revised_prompt" field.
func RevisedPromptLT(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldLT(FieldRevisedPrompt, v))
}

// RevisedPromptLTE applies the LTE predicate on the "revised_prompt" field.
func RevisedPromptLTE(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldLTE(FieldRevisedPrompt, v))
}

// RevisedPromptContains applies the Contains predicate on the "revised_prompt" field.
func RevisedPromptContains(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldContains(FieldRevisedPrompt, v))
}

// RevisedPromptHasPrefix applies the HasPrefix predicate on the "revised_prompt" field.
func RevisedPromptHasPrefix(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldHasPrefix(FieldRevisedPrompt, v))
}

// RevisedPromptHasSuffix applies the HasSuffix predicate on the "revised_prompt" field.
func RevisedPromptHasSuffix(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldHasSuffix(FieldRevisedPrompt, v))
}

// RevisedPromptEqualFold applies the EqualFold predicate on the "revised_prompt" field.
func RevisedPromptEqualFold(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEqualFold(FieldRevisedPrompt, v))
}

// RevisedPromptContainsFold applies the ContainsFold predicate on the "revised_prompt" field.
func RevisedPromptContainsFold(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldContainsFold(FieldRevisedPrompt, v))
}

// ObjectKeyEQ applies the EQ predicate on the "object_key" field.
func ObjectKeyEQ(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEQ(FieldObjectKey, v))
}

// ObjectKeyNEQ applies the NEQ predicate on the "object_key" field.
func ObjectKeyNEQ(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNEQ(FieldObjectKey, v))
}

// ObjectKeyIn applies the In predicate on the "object_key" field.
func ObjectKeyIn(vs ...string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldIn(FieldObjectKey, vs...))
}

// ObjectKeyNotIn applies the NotIn predicate on the "object_key" field.
func ObjectKeyNotIn(vs ...string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNotIn(FieldObjectKey, vs...))
}

// ObjectKeyGT applies the GT predicate on the "object_key" field.
func ObjectKeyGT(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldGT(FieldObjectKey, v))
}

// ObjectKeyGTE applies the GTE predicate on the "object_key" field.
func ObjectKeyGTE(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldGTE(FieldObjectKey, v))
}

// ObjectKeyLT applies the LT predicate on the "object_key" field.
func ObjectKeyLT(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldLT(FieldObjectKey, v))
}

// ObjectKeyLTE applies the LTE predicate on the "object_key" field.
func ObjectKeyLTE(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldLTE(FieldObjectKey, v))
}

// ObjectKeyContains applies the Contains predicate on the "object_key" field.
func ObjectKeyContains(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldContains(FieldObjectKey, v))
}

// ObjectKeyHasPrefix applies the HasPrefix predicate on the "object_key" field.
func ObjectKeyHasPrefix(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldHasPrefix(FieldObjectKey, v))
}

// ObjectKeyHasSuffix applies the HasSuffix predicate on the "object_key" field.
func ObjectKeyHasSuffix(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldHasSuffix(FieldObjectKey, v))
}

// ObjectKeyEqualFold applies the EqualFold predicate on the "object_key" field.
func ObjectKeyEqualFold(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEqualFold(FieldObjectKey, v))
}

// ObjectKeyContainsFold applies the ContainsFold predicate on the "object_key" field.
func ObjectKeyContainsFold(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldContainsFold(FieldObjectKey, v))
}

// MimeTypeEQ applies the EQ predicate on the "mime_type" field.
func MimeTypeEQ(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEQ(FieldMimeType, v))
}

// MimeTypeNEQ applies the NEQ predicate on the "mime_type" field.
func MimeTypeNEQ(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNEQ(FieldMimeType, v))
}

// MimeTypeIn applies the In predicate on the "mime_type" field.
func MimeTypeIn(vs ...string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldIn(FieldMimeType, vs...))
}

// MimeTypeNotIn applies the NotIn predicate on the "mime_type" field.
func MimeTypeNotIn(vs ...string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNotIn(FieldMimeType, vs...))
}

// MimeTypeGT applies the GT predicate on the "mime_type" field.
func MimeTypeGT(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldGT(FieldMimeType, v))
}

// MimeTypeGTE applies the GTE predicate on the "mime_type" field.
func MimeTypeGTE(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldGTE(FieldMimeType, v))
}

// MimeTypeLT applies the LT predicate on the "mime_type" field.
func MimeTypeLT(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldLT(FieldMimeType, v))
}

// MimeTypeLTE applies the LTE predicate on the "mime_type" field.
func MimeTypeLTE(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldLTE(FieldMimeType, v))
}

// MimeTypeContains applies the Contains predicate on the "mime_type" field.
func MimeTypeContains(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldContains(FieldMimeType, v))
}

// MimeTypeHasPrefix applies the HasPrefix predicate on the "mime_type" field.
func MimeTypeHasPrefix(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldHasPrefix(FieldMimeType, v))
}

// MimeTypeHasSuffix applies the HasSuffix predicate on the "mime_type" field.
func MimeTypeHasSuffix(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldHasSuffix(FieldMimeType, v))
}

// MimeTypeEqualFold applies the EqualFold predicate on the "mime_type" field.
func MimeTypeEqualFold(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEqualFold(FieldMimeType, v))
}

// MimeTypeContainsFold applies the ContainsFold predicate on the "mime_type" field.
func MimeTypeContainsFold(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldContainsFold(FieldMimeType, v))
}

// SizeBytesEQ applies the EQ predicate on the "size_bytes" field.
func SizeBytesEQ(v int64) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEQ(FieldSizeBytes, v))
}

// SizeBytesNEQ applies the NEQ predicate on the "size_bytes" field.
func SizeBytesNEQ(v int64) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNEQ(FieldSizeBytes, v))
}

// SizeBytesIn applies the In predicate on the "size_bytes" field.
func SizeBytesIn(vs ...int64) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldIn(FieldSizeBytes, vs...))
}

// SizeBytesNotIn applies the NotIn predicate on the "size_bytes" field.
func SizeBytesNotIn(vs ...int64) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNotIn(FieldSizeBytes, vs...))
}

// SizeBytesGT applies the GT predicate on the "size_bytes" field.
func SizeBytesGT(v int64) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldGT(FieldSizeBytes, v))
}

// SizeBytesGTE applies the GTE predicate on the "size_bytes" field.
func SizeBytesGTE(v int64) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldGTE(FieldSizeBytes, v))
}

// SizeBytesLT applies the LT predicate on the "size_bytes" field.
func SizeBytesLT(v int64) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldLT(FieldSizeBytes, v))
}

// SizeBytesLTE applies the LTE predicate on the "size_bytes" field.
func SizeBytesLTE(v int64) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldLTE(FieldSizeBytes, v))
}

// WidthEQ applies the EQ predicate on the "width" field.
func WidthEQ(v int) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEQ(FieldWidth, v))
}

// WidthNEQ applies the NEQ predicate on the "width" field.
func WidthNEQ(v int) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNEQ(FieldWidth, v))
}

// WidthIn applies the In predicate on the "width" field.
func WidthIn(vs ...int) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldIn(FieldWidth, vs...))
}

// WidthNotIn applies the NotIn predicate on the "width" field.
func WidthNotIn(vs ...int) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNotIn(FieldWidth, vs...))
}

// WidthGT applies the GT predicate on the "width" field.
func WidthGT(v int) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldGT(FieldWidth, v))
}

// WidthGTE applies the GTE predicate on the "width" field.
func WidthGTE(v int) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldGTE(FieldWidth, v))
}

// WidthLT applies the LT predicate on the "width" field.
func WidthLT(v int) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldLT(FieldWidth, v))
}

// WidthLTE applies the LTE predicate on the "width" field.
func WidthLTE(v int) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldLTE(FieldWidth, v))
}

// HeightEQ applies the EQ predicate on the "height" field.
func HeightEQ(v int) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEQ(FieldHeight, v))
}

// HeightNEQ applies the NEQ predicate on the "height" field.
func HeightNEQ(v int) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNEQ(FieldHeight, v))
}

// HeightIn applies the In predicate on the "height" field.
func HeightIn(vs ...int) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldIn(FieldHeight, vs...))
}

// HeightNotIn applies the NotIn predicate on the "height" field.
func HeightNotIn(vs ...int) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNotIn(FieldHeight, vs...))
}

// HeightGT applies the GT predicate on the "height" field.
func HeightGT(v int) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldGT(FieldHeight, v))
}

// HeightGTE applies the GTE predicate on the "height" field.
func HeightGTE(v int) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldGTE(FieldHeight, v))
}

// HeightLT applies the LT predicate on the "height" field.
func HeightLT(v int) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldLT(FieldHeight, v))
}

// HeightLTE applies the LTE predicate on the "height" field.
func HeightLTE(v int) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldLTE(FieldHeight, v))
}

// Sha256EQ applies the EQ predicate on the "sha256" field.
func Sha256EQ(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEQ(FieldSha256, v))
}

// Sha256NEQ applies the NEQ predicate on the "sha256" field.
func Sha256NEQ(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNEQ(FieldSha256, v))
}

// Sha256In applies the In predicate on the "sha256" field.
func Sha256In(vs ...string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldIn(FieldSha256, vs...))
}

// Sha256NotIn applies the NotIn predicate on the "sha256" field.
func Sha256NotIn(vs ...string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNotIn(FieldSha256, vs...))
}

// Sha256GT applies the GT predicate on the "sha256" field.
func Sha256GT(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldGT(FieldSha256, v))
}

// Sha256GTE applies the GTE predicate on the "sha256" field.
func Sha256GTE(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldGTE(FieldSha256, v))
}

// Sha256LT applies the LT predicate on the "sha256" field.
func Sha256LT(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldLT(FieldSha256, v))
}

// Sha256LTE applies the LTE predicate on the "sha256" field.
func Sha256LTE(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldLTE(FieldSha256, v))
}

// Sha256Contains applies the Contains predicate on the "sha256" field.
func Sha256Contains(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldContains(FieldSha256, v))
}

// Sha256HasPrefix applies the HasPrefix predicate on the "sha256" field.
func Sha256HasPrefix(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldHasPrefix(FieldSha256, v))
}

// Sha256HasSuffix applies the HasSuffix predicate on the "sha256" field.
func Sha256HasSuffix(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldHasSuffix(FieldSha256, v))
}

// Sha256EqualFold applies the EqualFold predicate on the "sha256" field.
func Sha256EqualFold(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEqualFold(FieldSha256, v))
}

// Sha256ContainsFold applies the ContainsFold predicate on the "sha256" field.
func Sha256ContainsFold(v string) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldContainsFold(FieldSha256, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ImageHistory {
	return predicate.ImageHistory(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ImageHistory) predicate.ImageHistory {
	return predicate.ImageHistory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ImageHistory) predicate.ImageHistory {
	return predicate.ImageHistory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ImageHistory) predicate.ImageHistory {
	return predicate.ImageHistory(sql.NotPredicates(p))
}
