// Code generated by ent, DO NOT EDIT.

package invoiceattachment

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the invoiceattachment type in the database.
	Label = "invoice_attachment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInvoiceRequestID holds the string denoting the invoice_request_id field in the database.
	FieldInvoiceRequestID = "invoice_request_id"
	// FieldFileName holds the string denoting the file_name field in the database.
	FieldFileName = "file_name"
	// FieldContentType holds the string denoting the content_type field in the database.
	FieldContentType = "content_type"
	// FieldSizeBytes holds the string denoting the size_bytes field in the database.
	FieldSizeBytes = "size_bytes"
	// FieldStorageKey holds the string denoting the storage_key field in the database.
	FieldStorageKey = "storage_key"
	// FieldStorageType holds the string denoting the storage_type field in the database.
	FieldStorageType = "storage_type"
	// FieldStorageProfileID holds the string denoting the storage_profile_id field in the database.
	FieldStorageProfileID = "storage_profile_id"
	// FieldSha256 holds the string denoting the sha256 field in the database.
	FieldSha256 = "sha256"
	// FieldUploadedBy holds the string denoting the uploaded_by field in the database.
	FieldUploadedBy = "uploaded_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the invoiceattachment in the database.
	Table = "invoice_attachments"
)

// Columns holds all SQL columns for invoiceattachment fields.
var Columns = []string{
	FieldID,
	FieldInvoiceRequestID,
	FieldFileName,
	FieldContentType,
	FieldSizeBytes,
	FieldStorageKey,
	FieldStorageType,
	FieldStorageProfileID,
	FieldSha256,
	FieldUploadedBy,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// FileNameValidator is a validator for the "file_name" field. It is called by the builders before save.
	FileNameValidator func(string) error
	// ContentTypeValidator is a validator for the "content_type" field. It is called by the builders before save.
	ContentTypeValidator func(string) error
	// StorageKeyValidator is a validator for the "storage_key" field. It is called by the builders before save.
	StorageKeyValidator func(string) error
	// DefaultStorageType holds the default value on creation for the "storage_type" field.
	DefaultStorageType string
	// StorageTypeValidator is a validator for the "storage_type" field. It is called by the builders before save.
	StorageTypeValidator func(string) error
	// DefaultStorageProfileID holds the default value on creation for the "storage_profile_id" field.
	DefaultStorageProfileID string
	// StorageProfileIDValidator is a validator for the "storage_profile_id" field. It is called by the builders before save.
	StorageProfileIDValidator func(string) error
	// Sha256Validator is a validator for the "sha256" field. It is called by the builders before save.
	Sha256Validator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the InvoiceAttachment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByInvoiceRequestID orders the results by the invoice_request_id field.
func ByInvoiceRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceRequestID, opts...).ToFunc()
}

// ByFileName orders the results by the file_name field.
func ByFileName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileName, opts...).ToFunc()
}

// ByContentType orders the results by the content_type field.
func ByContentType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentType, opts...).ToFunc()
}

// BySizeBytes orders the results by the size_bytes field.
func BySizeBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSizeBytes, opts...).ToFunc()
}

// ByStorageKey orders the results by the storage_key field.
func ByStorageKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStorageKey, opts...).ToFunc()
}

// ByStorageType orders the results by the storage_type field.
func ByStorageType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStorageType, opts...).ToFunc()
}

// ByStorageProfileID orders the results by the storage_profile_id field.
func ByStorageProfileID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStorageProfileID, opts...).ToFunc()
}

// BySha256 orders the results by the sha256 field.
func BySha256(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSha256, opts...).ToFunc()
}

// ByUploadedBy orders the results by the uploaded_by field.
func ByUploadedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUploadedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
