// Code generated by ent, DO NOT EDIT.

package invoiceattachment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/BrandonVee/TokenRouter/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldLTE(FieldID, id))
}

// InvoiceRequestID applies equality check predicate on the "invoice_request_id" field. It's identical to InvoiceRequestIDEQ.
func InvoiceRequestID(v int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldEQ(FieldInvoiceRequestID, v))
}

// FileName applies equality check predicate on the "file_name" field. It's identical to FileNameEQ.
func FileName(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldEQ(FieldFileName, v))
}

// ContentType applies equality check predicate on the "content_type" field. It's identical to ContentTypeEQ.
func ContentType(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldEQ(FieldContentType, v))
}

// SizeBytes applies equality check predicate on the "size_bytes" field. It's identical to SizeBytesEQ.
func SizeBytes(v int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldEQ(FieldSizeBytes, v))
}

// StorageKey applies equality check predicate on the "storage_key" field. It's identical to StorageKeyEQ.
func StorageKey(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldEQ(FieldStorageKey, v))
}

// StorageType applies equality check predicate on the "storage_type" field. It's identical to StorageTypeEQ.
func StorageType(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldEQ(FieldStorageType, v))
}

// StorageProfileID applies equality check predicate on the "storage_profile_id" field. It's identical to StorageProfileIDEQ.
func StorageProfileID(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldEQ(FieldStorageProfileID, v))
}

// Sha256 applies equality check predicate on the "sha256" field. It's identical to Sha256EQ.
func Sha256(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldEQ(FieldSha256, v))
}

// UploadedBy applies equality check predicate on the "uploaded_by" field. It's identical to UploadedByEQ.
func UploadedBy(v int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldEQ(FieldUploadedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldEQ(FieldCreatedAt, v))
}

// InvoiceRequestIDEQ applies the EQ predicate on the "invoice_request_id" field.
func InvoiceRequestIDEQ(v int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldEQ(FieldInvoiceRequestID, v))
}

// InvoiceRequestIDNEQ applies the NEQ predicate on the "invoice_request_id" field.
func InvoiceRequestIDNEQ(v int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldNEQ(FieldInvoiceRequestID, v))
}

// InvoiceRequestIDIn applies the In predicate on the "invoice_request_id" field.
func InvoiceRequestIDIn(vs ...int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldIn(FieldInvoiceRequestID, vs...))
}

// InvoiceRequestIDNotIn applies the NotIn predicate on the "invoice_request_id" field.
func InvoiceRequestIDNotIn(vs ...int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldNotIn(FieldInvoiceRequestID, vs...))
}

// InvoiceRequestIDGT applies the GT predicate on the "invoice_request_id" field.
func InvoiceRequestIDGT(v int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldGT(FieldInvoiceRequestID, v))
}

// InvoiceRequestIDGTE applies the GTE predicate on the "invoice_request_id" field.
func InvoiceRequestIDGTE(v int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldGTE(FieldInvoiceRequestID, v))
}

// InvoiceRequestIDLT applies the LT predicate on the "invoice_request_id" field.
func InvoiceRequestIDLT(v int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldLT(FieldInvoiceRequestID, v))
}

// InvoiceRequestIDLTE applies the LTE predicate on the "invoice_request_id" field.
func InvoiceRequestIDLTE(v int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldLTE(FieldInvoiceRequestID, v))
}

// FileNameEQ applies the EQ predicate on the "file_name" field.
func FileNameEQ(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldEQ(FieldFileName, v))
}

// FileNameNEQ applies the NEQ predicate on the "file_name" field.
func FileNameNEQ(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldNEQ(FieldFileName, v))
}

// FileNameIn applies the In predicate on the "file_name" field.
func FileNameIn(vs ...string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldIn(FieldFileName, vs...))
}

// FileNameNotIn applies the NotIn predicate on the "file_name" field.
func FileNameNotIn(vs ...string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldNotIn(FieldFileName, vs...))
}

// FileNameGT applies the GT predicate on the "file_name" field.
func FileNameGT(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldGT(FieldFileName, v))
}

// FileNameGTE applies the GTE predicate on the "file_name" field.
func FileNameGTE(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldGTE(FieldFileName, v))
}

// FileNameLT applies the LT predicate on the "file_name" field.
func FileNameLT(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldLT(FieldFileName, v))
}

// FileNameLTE applies the LTE predicate on the "file_name" field.
func FileNameLTE(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldLTE(FieldFileName, v))
}

// FileNameContains applies the Contains predicate on the "file_name" field.
func FileNameContains(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldContains(FieldFileName, v))
}

// FileNameHasPrefix applies the HasPrefix predicate on the "file_name" field.
func FileNameHasPrefix(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldHasPrefix(FieldFileName, v))
}

// FileNameHasSuffix applies the HasSuffix predicate on the "file_name" field.
func FileNameHasSuffix(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldHasSuffix(FieldFileName, v))
}

// FileNameEqualFold applies the EqualFold predicate on the "file_name" field.
func FileNameEqualFold(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldEqualFold(FieldFileName, v))
}

// FileNameContainsFold applies the ContainsFold predicate on the "file_name" field.
func FileNameContainsFold(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldContainsFold(FieldFileName, v))
}

// ContentTypeEQ applies the EQ predicate on the "content_type" field.
func ContentTypeEQ(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldEQ(FieldContentType, v))
}

// ContentTypeNEQ applies the NEQ predicate on the "content_type" field.
func ContentTypeNEQ(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldNEQ(FieldContentType, v))
}

// ContentTypeIn applies the In predicate on the "content_type" field.
func ContentTypeIn(vs ...string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldIn(FieldContentType, vs...))
}

// ContentTypeNotIn applies the NotIn predicate on the "content_type" field.
func ContentTypeNotIn(vs ...string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldNotIn(FieldContentType, vs...))
}

// ContentTypeGT applies the GT predicate on the "content_type" field.
func ContentTypeGT(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldGT(FieldContentType, v))
}

// ContentTypeGTE applies the GTE predicate on the "content_type" field.
func ContentTypeGTE(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldGTE(FieldContentType, v))
}

// ContentTypeLT applies the LT predicate on the "content_type" field.
func ContentTypeLT(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldLT(FieldContentType, v))
}

// ContentTypeLTE applies the LTE predicate on the "content_type" field.
func ContentTypeLTE(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldLTE(FieldContentType, v))
}

// ContentTypeContains applies the Contains predicate on the "content_type" field.
func ContentTypeContains(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldContains(FieldContentType, v))
}

// ContentTypeHasPrefix applies the HasPrefix predicate on the "content_type" field.
func ContentTypeHasPrefix(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldHasPrefix(FieldContentType, v))
}

// ContentTypeHasSuffix applies the HasSuffix predicate on the "content_type" field.
func ContentTypeHasSuffix(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldHasSuffix(FieldContentType, v))
}

// ContentTypeEqualFold applies the EqualFold predicate on the "content_type" field.
func ContentTypeEqualFold(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldEqualFold(FieldContentType, v))
}

// ContentTypeContainsFold applies the ContainsFold predicate on the "content_type" field.
func ContentTypeContainsFold(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldContainsFold(FieldContentType, v))
}

// SizeBytesEQ applies the EQ predicate on the "size_bytes" field.
func SizeBytesEQ(v int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldEQ(FieldSizeBytes, v))
}

// SizeBytesNEQ applies the NEQ predicate on the "size_bytes" field.
func SizeBytesNEQ(v int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldNEQ(FieldSizeBytes, v))
}

// SizeBytesIn applies the In predicate on the "size_bytes" field.
func SizeBytesIn(vs ...int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldIn(FieldSizeBytes, vs...))
}

// SizeBytesNotIn applies the NotIn predicate on the "size_bytes" field.
func SizeBytesNotIn(vs ...int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldNotIn(FieldSizeBytes, vs...))
}

// SizeBytesGT applies the GT predicate on the "size_bytes" field.
func SizeBytesGT(v int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldGT(FieldSizeBytes, v))
}

// SizeBytesGTE applies the GTE predicate on the "size_bytes" field.
func SizeBytesGTE(v int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldGTE(FieldSizeBytes, v))
}

// SizeBytesLT applies the LT predicate on the "size_bytes" field.
func SizeBytesLT(v int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldLT(FieldSizeBytes, v))
}

// SizeBytesLTE applies the LTE predicate on the "size_bytes" field.
func SizeBytesLTE(v int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldLTE(FieldSizeBytes, v))
}

// StorageKeyEQ applies the EQ predicate on the "storage_key" field.
func StorageKeyEQ(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldEQ(FieldStorageKey, v))
}

// StorageKeyNEQ applies the NEQ predicate on the "storage_key" field.
func StorageKeyNEQ(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldNEQ(FieldStorageKey, v))
}

// StorageKeyIn applies the In predicate on the "storage_key" field.
func StorageKeyIn(vs ...string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldIn(FieldStorageKey, vs...))
}

// StorageKeyNotIn applies the NotIn predicate on the "storage_key" field.
func StorageKeyNotIn(vs ...string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldNotIn(FieldStorageKey, vs...))
}

// StorageKeyGT applies the GT predicate on the "storage_key" field.
func StorageKeyGT(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldGT(FieldStorageKey, v))
}

// StorageKeyGTE applies the GTE predicate on the "storage_key" field.
func StorageKeyGTE(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldGTE(FieldStorageKey, v))
}

// StorageKeyLT applies the LT predicate on the "storage_key" field.
func StorageKeyLT(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldLT(FieldStorageKey, v))
}

// StorageKeyLTE applies the LTE predicate on the "storage_key" field.
func StorageKeyLTE(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldLTE(FieldStorageKey, v))
}

// StorageKeyContains applies the Contains predicate on the "storage_key" field.
func StorageKeyContains(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldContains(FieldStorageKey, v))
}

// StorageKeyHasPrefix applies the HasPrefix predicate on the "storage_key" field.
func StorageKeyHasPrefix(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldHasPrefix(FieldStorageKey, v))
}

// StorageKeyHasSuffix applies the HasSuffix predicate on the "storage_key" field.
func StorageKeyHasSuffix(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldHasSuffix(FieldStorageKey, v))
}

// StorageKeyEqualFold applies the EqualFold predicate on the "storage_key" field.
func StorageKeyEqualFold(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldEqualFold(FieldStorageKey, v))
}

// StorageKeyContainsFold applies the ContainsFold predicate on the "storage_key" field.
func StorageKeyContainsFold(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldContainsFold(FieldStorageKey, v))
}

// StorageTypeEQ applies the EQ predicate on the "storage_type" field.
func StorageTypeEQ(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldEQ(FieldStorageType, v))
}

// StorageTypeNEQ applies the NEQ predicate on the "storage_type" field.
func StorageTypeNEQ(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldNEQ(FieldStorageType, v))
}

// StorageTypeIn applies the In predicate on the "storage_type" field.
func StorageTypeIn(vs ...string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldIn(FieldStorageType, vs...))
}

// StorageTypeNotIn applies the NotIn predicate on the "storage_type" field.
func StorageTypeNotIn(vs ...string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldNotIn(FieldStorageType, vs...))
}

// StorageTypeGT applies the GT predicate on the "storage_type" field.
func StorageTypeGT(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldGT(FieldStorageType, v))
}

// StorageTypeGTE applies the GTE predicate on the "storage_type" field.
func StorageTypeGTE(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldGTE(FieldStorageType, v))
}

// StorageTypeLT applies the LT predicate on the "storage_type" field.
func StorageTypeLT(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldLT(FieldStorageType, v))
}

// StorageTypeLTE applies the LTE predicate on the "storage_type" field.
func StorageTypeLTE(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldLTE(FieldStorageType, v))
}

// StorageTypeContains applies the Contains predicate on the "storage_type" field.
func StorageTypeContains(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldContains(FieldStorageType, v))
}

// StorageTypeHasPrefix applies the HasPrefix predicate on the "storage_type" field.
func StorageTypeHasPrefix(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldHasPrefix(FieldStorageType, v))
}

// StorageTypeHasSuffix applies the HasSuffix predicate on the "storage_type" field.
func StorageTypeHasSuffix(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldHasSuffix(FieldStorageType, v))
}

// StorageTypeEqualFold applies the EqualFold predicate on the "storage_type" field.
func StorageTypeEqualFold(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldEqualFold(FieldStorageType, v))
}

// StorageTypeContainsFold applies the ContainsFold predicate on the "storage_type" field.
func StorageTypeContainsFold(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldContainsFold(FieldStorageType, v))
}

// StorageProfileIDEQ applies the EQ predicate on the "storage_profile_id" field.
func StorageProfileIDEQ(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldEQ(FieldStorageProfileID, v))
}

// StorageProfileIDNEQ applies the NEQ predicate on the "storage_profile_id" field.
func StorageProfileIDNEQ(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldNEQ(FieldStorageProfileID, v))
}

// StorageProfileIDIn applies the In predicate on the "storage_profile_id" field.
func StorageProfileIDIn(vs ...string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldIn(FieldStorageProfileID, vs...))
}

// StorageProfileIDNotIn applies the NotIn predicate on the "storage_profile_id" field.
func StorageProfileIDNotIn(vs ...string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldNotIn(FieldStorageProfileID, vs...))
}

// StorageProfileIDGT applies the GT predicate on the "storage_profile_id" field.
func StorageProfileIDGT(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldGT(FieldStorageProfileID, v))
}

// StorageProfileIDGTE applies the GTE predicate on the "storage_profile_id" field.
func StorageProfileIDGTE(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldGTE(FieldStorageProfileID, v))
}

// StorageProfileIDLT applies the LT predicate on the "storage_profile_id" field.
func StorageProfileIDLT(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldLT(FieldStorageProfileID, v))
}

// StorageProfileIDLTE applies the LTE predicate on the "storage_profile_id" field.
func StorageProfileIDLTE(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldLTE(FieldStorageProfileID, v))
}

// StorageProfileIDContains applies the Contains predicate on the "storage_profile_id" field.
func StorageProfileIDContains(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldContains(FieldStorageProfileID, v))
}

// StorageProfileIDHasPrefix applies the HasPrefix predicate on the "storage_profile_id" field.
func StorageProfileIDHasPrefix(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldHasPrefix(FieldStorageProfileID, v))
}

// StorageProfileIDHasSuffix applies the HasSuffix predicate on the "storage_profile_id" field.
func StorageProfileIDHasSuffix(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldHasSuffix(FieldStorageProfileID, v))
}

// StorageProfileIDEqualFold applies the EqualFold predicate on the "storage_profile_id" field.
func StorageProfileIDEqualFold(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldEqualFold(FieldStorageProfileID, v))
}

// StorageProfileIDContainsFold applies the ContainsFold predicate on the "storage_profile_id" field.
func StorageProfileIDContainsFold(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldContainsFold(FieldStorageProfileID, v))
}

// Sha256EQ applies the EQ predicate on the "sha256" field.
func Sha256EQ(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldEQ(FieldSha256, v))
}

// Sha256NEQ applies the NEQ predicate on the "sha256" field.
func Sha256NEQ(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldNEQ(FieldSha256, v))
}

// Sha256In applies the In predicate on the "sha256" field.
func Sha256In(vs ...string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldIn(FieldSha256, vs...))
}

// Sha256NotIn applies the NotIn predicate on the "sha256" field.
func Sha256NotIn(vs ...string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldNotIn(FieldSha256, vs...))
}

// Sha256GT applies the GT predicate on the "sha256" field.
func Sha256GT(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldGT(FieldSha256, v))
}

// Sha256GTE applies the GTE predicate on the "sha256" field.
func Sha256GTE(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldGTE(FieldSha256, v))
}

// Sha256LT applies the LT predicate on the "sha256" field.
func Sha256LT(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldLT(FieldSha256, v))
}

// Sha256LTE applies the LTE predicate on the "sha256" field.
func Sha256LTE(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldLTE(FieldSha256, v))
}

// Sha256Contains applies the Contains predicate on the "sha256" field.
func Sha256Contains(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldContains(FieldSha256, v))
}

// Sha256HasPrefix applies the HasPrefix predicate on the "sha256" field.
func Sha256HasPrefix(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldHasPrefix(FieldSha256, v))
}

// Sha256HasSuffix applies the HasSuffix predicate on the "sha256" field.
func Sha256HasSuffix(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldHasSuffix(FieldSha256, v))
}

// Sha256EqualFold applies the EqualFold predicate on the "sha256" field.
func Sha256EqualFold(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldEqualFold(FieldSha256, v))
}

// Sha256ContainsFold applies the ContainsFold predicate on the "sha256" field.
func Sha256ContainsFold(v string) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldContainsFold(FieldSha256, v))
}

// UploadedByEQ applies the EQ predicate on the "uploaded_by" field.
func UploadedByEQ(v int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldEQ(FieldUploadedBy, v))
}

// UploadedByNEQ applies the NEQ predicate on the "uploaded_by" field.
func UploadedByNEQ(v int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldNEQ(FieldUploadedBy, v))
}

// UploadedByIn applies the In predicate on the "uploaded_by" field.
func UploadedByIn(vs ...int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldIn(FieldUploadedBy, vs...))
}

// UploadedByNotIn applies the NotIn predicate on the "uploaded_by" field.
func UploadedByNotIn(vs ...int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldNotIn(FieldUploadedBy, vs...))
}

// UploadedByGT applies the GT predicate on the "uploaded_by" field.
func UploadedByGT(v int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldGT(FieldUploadedBy, v))
}

// UploadedByGTE applies the GTE predicate on the "uploaded_by" field.
func UploadedByGTE(v int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldGTE(FieldUploadedBy, v))
}

// UploadedByLT applies the LT predicate on the "uploaded_by" field.
func UploadedByLT(v int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldLT(FieldUploadedBy, v))
}

// UploadedByLTE applies the LTE predicate on the "uploaded_by" field.
func UploadedByLTE(v int64) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldLTE(FieldUploadedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InvoiceAttachment) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InvoiceAttachment) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InvoiceAttachment) predicate.InvoiceAttachment {
	return predicate.InvoiceAttachment(sql.NotPredicates(p))
}
